using System.Collections.Generic;

namespace Viktor.Localization;

/// <summary>
/// Chinese text for the action catalogue. Keys are
/// <c>{actionKey}.name</c>, <c>{actionKey}.desc</c> and
/// <c>{actionKey}.{parameter}.label</c> / <c>.hint</c>; anything missing falls
/// back to the English text stored in the catalogue itself.
/// </summary>
internal static class ActionStrings
{
    /// <summary>
    /// The hint the thirteen input actions share for their input-mode picker. They were written
    /// once rather than thirteen times, so a change to how input is described stays in one place.
    /// </summary>
    private const string InputModeHint =
        "这一步的输入怎么送出去。前台发给当前有焦点的窗口；后台把消息投给下面的目标窗口，"
        + "不用抢焦点，屏幕上的鼠标也不会真的移动；驱动级通过虚拟 USB 设备发送，"
        + "需要先启动 VIIPER 服务端。";

    /// <summary>The matching hint for the window background input posts its messages at.</summary>
    private const string TargetWindowHint =
        "后台输入把消息投给哪个窗口，填标题的一部分即可。其他输入方式用不到。";

    /// <summary>
    /// The hint every action that takes a position or a rectangle shares for its coordinate-origin
    /// picker, written once for the same reason the input-mode hint is.
    /// </summary>
    private const string AnchorModeHint =
        "这一步的坐标从哪里量起。屏幕＝桌面上的像素位置，也是以前所有宏的写法；"
        + "窗口左上角＝从目标窗口外框的左上角算起；窗口客户区＝从窗口边框里面算起。"
        + "后两种会让这一步跟着窗口走，窗口移动或缩放之后仍然落在窗口里的同一个位置。";

    /// <summary>The matching hint for the window those coordinates are measured from.</summary>
    private const string AnchorWindowHint =
        "坐标从哪个窗口量起，填标题的一部分即可。留空表示运行时最前面那个窗口；"
        + "选“屏幕像素”时用不到它。";

    /// <summary>The hint every window action shares for the text it recognises a window by.</summary>
    private const string WindowTitleHint =
        "靠什么认出这个窗口，不区分大小写。留空表示最前面那个窗口。";

    /// <summary>The matching hint for the part of a window that text is compared with.</summary>
    private const string WindowMatchByHint =
        "上面的文字和窗口的哪一部分比较。标题是标题栏上看到的字；进程名是拥有这个窗口的程序名"
        + "（不含 .exe），标题换了它也不变；窗口类名是程序注册的那一类窗口，比如记事本都是 Notepad。";

    private const string WindowMatchByTitle = "标题";
    private const string WindowMatchByProcess = "进程名";
    private const string WindowMatchByClass = "窗口类名";

    /// <summary>The hint the four text-file actions share for their encoding picker.</summary>
    private const string EncodingHintText =
        "文件里的文字按什么编码变成字节。UTF-8 是现在通用的写法；带 BOM 的是记事本默认保存的样子；"
        + "GBK 是中文 Windows 自己写文本文件用的编码；UTF-16 是一些老 Windows 程序认的。"
        + "读取时如果文件开头有 BOM，会以 BOM 为准。";

    private const string EncodingUtf8 = "UTF-8";
    private const string EncodingUtf8Bom = "UTF-8（带 BOM）";
    private const string EncodingGbk = "GBK（中文）";
    private const string EncodingUtf16 = "UTF-16";

    /// <summary>
    /// The hint the actions that can measure from a control share for the control they measure from,
    /// written once for the same reason the coordinate-origin hint is.
    /// </summary>
    private const string AnchorElementHint =
        "坐标从这个控件量起，例如 Button[name='Save']，可以点“拾取元素”直接从屏幕上抓；"
        + "这一步每次运行都会重新找它，控件移动之后数字仍然落在它身上。"
        + "选其他坐标基准时用不到它。";

    /// <summary>The hint every search-region field shares, in the wording the English one uses.</summary>
    private const string RegionHintText =
        "可选，格式 x,y,width,height，也可写成 $变量；一次要看几块区域就用分号隔开，每块都会搜；"
        + "留空表示全屏搜索。";

    /// <summary>The hint the "which hit" fields share.</summary>
    private const string MatchIndexHint = "从左到右、从上往下数第几个命中，1 是第一个。";

    /// <summary>The hint the "record every match" switches share.</summary>
    private const string AllMatchesHint =
        "勾上以后把命中的数量和位置都记下来：$变量名.count 是数量，$变量名.list 是每次命中的 “x,y”，"
        + "可以配合 count()、get()、forEach 使用。";

    internal static readonly Dictionary<string, string> Chinese = new()
    {
        // ------------------------------------------------------------------ control
        ["control.waitUntil.name"] = "等待直到",
        ["control.waitUntil.desc"] = "反复判断一个条件，成立之后再继续往下走。",
        ["control.waitUntil.condition.label"] = "条件",
        ["control.waitUntil.condition.hint"] = "会一遍遍判断这个条件，直到它成立。颜色、图片、文字、界面元素、变量比较都可以用来等。",
        ["control.waitUntil.timeoutMs.label"] = "超时毫秒",
        ["control.waitUntil.timeoutMs.hint"] = "超过这个时长就放弃。",
        ["control.waitUntil.pollMs.label"] = "检查间隔毫秒",
        ["control.waitUntil.pollMs.hint"] = "两次判断之间等待多久。",
        ["control.waitUntil.onTimeout.label"] = "一直不成立时",
        ["control.waitUntil.onTimeout.hint"] = "时间到了以后这个宏怎么做。",
        ["control.waitUntil.onTimeout.option.stop"] = "停止整个宏",
        ["control.waitUntil.onTimeout.option.continue"] = "忽略并继续下一步",
        ["control.waitUntil.elapsedVariable.label"] = "等待时长毫秒",
        ["control.waitUntil.elapsedVariable.hint"] = "用来接收这次等待实际花了多少毫秒；等到和超时都会写入。",

        ["control.sequence.name"] = "顺序执行",
        ["control.sequence.desc"] = "按顺序依次执行子步骤。",
        ["control.sequence.name.label"] = "名称",
        ["control.sequence.name.hint"] = "可选，列表里显示的名称。",
        ["control.sequence.steps.label"] = "子步骤",
        ["control.sequence.steps.hint"] = "按顺序执行的子步骤。",

        ["control.delay.name"] = "延迟",
        ["control.delay.desc"] = "执行下一步之前等待固定时长。",
        ["control.delay.ms.label"] = "毫秒",
        ["control.delay.ms.hint"] = "等待时长，单位毫秒。",

        ["control.delayRandom.name"] = "随机延迟",
        ["control.delayRandom.desc"] = "等待一个随机时长，让宏看起来不像机械执行。",
        ["control.delayRandom.minMs.label"] = "最短毫秒",
        ["control.delayRandom.minMs.hint"] = "最短等待时长，单位毫秒。",
        ["control.delayRandom.maxMs.label"] = "最长毫秒",
        ["control.delayRandom.maxMs.hint"] = "最长等待时长，单位毫秒。",

        ["control.repeat.name"] = "重复",
        ["control.repeat.desc"] = "把子步骤重复执行固定次数。",
        ["control.repeat.times.label"] = "次数",
        ["control.repeat.times.hint"] = "重复执行的次数。",
        ["control.repeat.intervalMs.label"] = "间隔毫秒",
        ["control.repeat.intervalMs.hint"] = "每轮之间的等待时间。",
        ["control.repeat.body.label"] = "循环体步骤",
        ["control.repeat.body.hint"] = "每轮执行一次的子步骤。",

        ["control.while.name"] = "当…时循环",
        ["control.while.desc"] = "条件成立期间，反复执行子步骤。",
        ["control.while.condition.label"] = "条件",
        ["control.while.condition.hint"] = "每轮开始前判断一次。",
        ["control.while.maxIterations.label"] = "最大轮数",
        ["control.while.maxIterations.hint"] = "安全上限，避免死循环停不下来。",
        ["control.while.body.label"] = "循环体步骤",
        ["control.while.body.hint"] = "条件成立时执行的子步骤。",

        ["control.forEach.name"] = "遍历",
        ["control.forEach.desc"] = "对列表或变量中的每一项执行一次子步骤。",
        ["control.forEach.items.label"] = "列表项",
        ["control.forEach.items.hint"] = "一个列表，或保存列表的 $变量。例如 [1, 2, 3]、split($text, \",\") 或 $names。",
        ["control.forEach.itemVariable.label"] = "当前项变量",
        ["control.forEach.itemVariable.hint"] = "用于接收当前项的变量名。",
        ["control.forEach.indexVariable.label"] = "序号变量",
        ["control.forEach.indexVariable.hint"] = "可选，用来接收当前是第几轮（从 0 开始），留空就不记轮次。",
        ["control.forEach.reverse.label"] = "倒序遍历",
        ["control.forEach.reverse.hint"] = "从最后一项往前遍历。",
        ["control.forEach.body.label"] = "循环体步骤",
        ["control.forEach.body.hint"] = "每一项执行一次的子步骤。",

        ["control.for.name"] = "计数循环",
        ["control.for.desc"] = "从一个数数到另一个数，每数一个就执行一遍子步骤。",
        ["control.for.from.label"] = "起始值",
        ["control.for.from.hint"] = "计数器第一次取的值。",
        ["control.for.to.label"] = "结束值",
        ["control.for.to.hint"] = "计数器最后一次取的值，包含它本身：从 1 数到 3 会执行三次。",
        ["control.for.step.label"] = "步长",
        ["control.for.step.hint"] = "每轮计数器增加多少。填负数就是往下数；填 0 表示“往上数，起始值大于结束值时往下数”。",
        ["control.for.intervalMs.label"] = "间隔毫秒",
        ["control.for.intervalMs.hint"] = "每轮之间的等待时间。",
        ["control.for.variable.label"] = "计数器变量",
        ["control.for.variable.hint"] = "用来接收本轮数值的变量，子步骤里可以读它。",
        ["control.for.body.label"] = "循环体步骤",
        ["control.for.body.hint"] = "每轮执行一次的子步骤。",

        ["control.if.name"] = "条件分支",
        ["control.if.desc"] = "根据条件在两个子步骤块中选择一个执行。",
        ["control.if.condition.label"] = "条件",
        ["control.if.condition.hint"] = "执行到这一步时判断一次。",
        ["control.if.then.label"] = "满足时步骤",
        ["control.if.then.hint"] = "条件成立时执行的子步骤。",
        ["control.if.else.label"] = "不满足时步骤",
        ["control.if.else.hint"] = "条件不成立时执行的子步骤。",

        ["control.switch.name"] = "多分支",
        ["control.switch.desc"] = "拿一个值从上到下比对各分支，命中第一个就执行它的步骤，都没命中就走“其他情况”。",
        ["control.switch.value.label"] = "要比对的值",
        ["control.switch.value.hint"] = "执行到这一步时读取一次，用来和各分支填的值比较。",
        ["control.switch.matchMode.label"] = "比对方式",
        ["control.switch.matchMode.hint"] = "决定分支里填的值怎么和上面的值比较。",
        ["control.switch.matchMode.option.equals"] = "等于",
        ["control.switch.matchMode.option.contains"] = "包含",
        ["control.switch.matchMode.option.startsWith"] = "以…开头",
        ["control.switch.matchMode.option.regex"] = "正则匹配",
        ["control.switch.cases.label"] = "分支",
        ["control.switch.cases.hint"] = "一条一个分支，从上往下比对；命中第一条就执行它，后面的不再看。",
        ["control.switch.otherwise.label"] = "其他情况步骤",
        ["control.switch.otherwise.hint"] = "所有分支都没命中时执行的子步骤。",

        ["control.case.name"] = "分支",
        ["control.case.desc"] = "多分支里的一条：它应答哪些值，以及命中后要执行的步骤。",
        ["control.case.values.label"] = "分支值",
        ["control.case.values.hint"] = "这条分支应答的值，用“;”隔开；每个值都按上面的比对方式和要比对的值比较。",
        ["control.case.body.label"] = "分支步骤",
        ["control.case.body.hint"] = "这条分支命中时执行的子步骤。",

        ["control.try.name"] = "尝试 / 捕获 / 收尾",
        ["control.try.desc"] = "先执行尝试的步骤，失败时改走捕获的步骤，最后无论如何都执行收尾的步骤。",
        ["control.try.body.label"] = "尝试步骤",
        ["control.try.body.hint"] = "先尝试执行的子步骤。",
        ["control.try.catch.label"] = "捕获步骤",
        ["control.try.catch.hint"] = "尝试失败时执行的子步骤。",
        ["control.try.finally.label"] = "收尾步骤",
        ["control.try.finally.hint"] = "无论成功、失败还是被跳过都会执行的子步骤。",
        ["control.try.errorVariable.label"] = "失败原因变量",
        ["control.try.errorVariable.hint"] = "用来接收失败原因；没有失败时会被清空。",

        ["control.break.name"] = "跳出循环",
        ["control.break.desc"] = "立即跳出最内层循环。",

        ["control.continue.name"] = "继续下一轮",
        ["control.continue.desc"] = "跳过本轮剩余步骤，直接开始下一轮。",

        ["control.stop.name"] = "停止宏",
        ["control.stop.desc"] = "停止正在运行的宏。",
        ["control.stop.reason.label"] = "原因",
        ["control.stop.reason.hint"] = "可选，会写入日志。",

        ["control.setVariable.name"] = "设置变量",
        ["control.setVariable.desc"] = "保存一个值，供后面的步骤使用。",
        ["control.setVariable.name.label"] = "变量名",
        ["control.setVariable.name.hint"] = "局部变量在这里命名即可；全局变量必须先在变量中心创建。",
        ["control.setVariable.value.label"] = "值",
        ["control.setVariable.value.hint"] = "数字、文本、$变量，或公式，例如 $count + 1、upper($name)。",
        ["control.setVariable.scope.label"] = "作用范围",
        ["control.setVariable.scope.hint"] = "局部变量只属于本宏，全局变量由所有宏共享。",
        ["control.setVariable.scope.option.local"] = "局部变量（仅本宏）",
        ["control.setVariable.scope.option.global"] = "全局变量（所有宏共享）",

        ["control.listCreate.name"] = "创建列表",
        ["control.listCreate.desc"] = "建立一个列表变量，覆盖它原来的内容。",
        ["control.listCreate.name.label"] = "变量名",
        ["control.listCreate.name.hint"] = "局部列表只属于本宏，全局列表由所有宏共享。列表里可以放任意类型的值。",
        ["control.listCreate.scope.label"] = "作用范围",
        ["control.listCreate.scope.hint"] = "局部列表只属于本宏，全局列表由所有宏共享。",
        ["control.listCreate.scope.option.local"] = "局部列表（仅本宏）",
        ["control.listCreate.scope.option.global"] = "全局列表（所有宏共享）",
        ["control.listCreate.items.label"] = "初始项",
        ["control.listCreate.items.hint"] = "列表一开始包含的值。留空则建立空列表。",

        ["control.listAdd.name"] = "列表追加",
        ["control.listAdd.desc"] = "在一个列表的末尾加入一个或多个值。",
        ["control.listAdd.name.label"] = "列表变量",
        ["control.listAdd.name.hint"] = "宏当前可见的列表。",
        ["control.listAdd.value.label"] = "追加的值",
        ["control.listAdd.value.hint"] = "放到列表末尾的值。",

        ["control.listInsert.name"] = "列表插入",
        ["control.listInsert.desc"] = "把值插入到列表的指定位置。",
        ["control.listInsert.name.label"] = "列表变量",
        ["control.listInsert.name.hint"] = "宏当前可见的列表。",
        ["control.listInsert.index.label"] = "位置",
        ["control.listInsert.index.hint"] = "插入位置，0 表示最前面。",
        ["control.listInsert.value.label"] = "值",
        ["control.listInsert.value.hint"] = "插入到该位置的值。",

        ["control.listRemoveAt.name"] = "列表移除",
        ["control.listRemoveAt.desc"] = "把列表指定位置的项移除。",
        ["control.listRemoveAt.name.label"] = "列表变量",
        ["control.listRemoveAt.name.hint"] = "宏当前可见的列表。",
        ["control.listRemoveAt.index.label"] = "位置",
        ["control.listRemoveAt.index.hint"] = "要移除的位置；-1 表示最后一项。",

        ["control.listClear.name"] = "清空列表",
        ["control.listClear.desc"] = "清空列表内容，变量本身保留。",
        ["control.listClear.name.label"] = "列表变量",
        ["control.listClear.name.hint"] = "宏当前可见的列表。",

        ["control.log.name"] = "写日志",
        ["control.log.desc"] = "向 Viktor 日志写入一条消息。",
        ["control.log.message.label"] = "消息",
        ["control.log.message.hint"] = "写入日志的文本。",
        ["control.log.level.label"] = "级别",

        ["control.runMacro.name"] = "执行其他宏",
        ["control.runMacro.desc"] = "运行本项目里的另一个宏，就像把它的步骤写在这里一样。"
            + "被调用的宏与调用它的宏共用变量，所以它能读取调用者准备的数据，也能把结果留在变量里。",
        ["control.runMacro.macro.label"] = "宏",
        ["control.runMacro.macro.hint"] = "本项目里的另一个宏。改名或删除后这里需要跟着改。",

        // --------------------------------------------------------------------- file
        ["file.readText.name"] = "读取文本",
        ["file.readText.desc"] = "把文本文件读入变量。",
        ["file.readText.path.label"] = "文件",
        ["file.readText.path.hint"] = "要读取的文件。只写文件名时会相对宏文件夹解析。",
        ["file.readText.resultVariable.label"] = "结果变量",
        ["file.readText.resultVariable.hint"] = "接收文件内容的变量。",
        ["file.readText.encoding.label"] = "编码",
        ["file.readText.encoding.hint"] = EncodingHintText,
        ["file.readText.encoding.option.utf8"] = EncodingUtf8,
        ["file.readText.encoding.option.utf8bom"] = EncodingUtf8Bom,
        ["file.readText.encoding.option.gbk"] = EncodingGbk,
        ["file.readText.encoding.option.utf16"] = EncodingUtf16,

        ["file.writeText.name"] = "写入文本",
        ["file.writeText.desc"] = "把文本写入文件，可以替换原内容或追加到末尾。",
        ["file.writeText.path.label"] = "文件",
        ["file.writeText.path.hint"] = "要写入的文件。只写文件名时会相对宏文件夹解析。",
        ["file.writeText.text.label"] = "文本",
        ["file.writeText.text.hint"] = "要写入的文本。",
        ["file.writeText.mode.label"] = "方式",
        ["file.writeText.mode.hint"] = "替换原文件，或追加到已有内容后面。",
        ["file.writeText.mode.option.overwrite"] = "替换原内容",
        ["file.writeText.mode.option.append"] = "追加到末尾",
        ["file.writeText.encoding.label"] = "编码",
        ["file.writeText.encoding.hint"] = EncodingHintText,
        ["file.writeText.encoding.option.utf8"] = EncodingUtf8,
        ["file.writeText.encoding.option.utf8bom"] = EncodingUtf8Bom,
        ["file.writeText.encoding.option.gbk"] = EncodingGbk,
        ["file.writeText.encoding.option.utf16"] = EncodingUtf16,

        ["file.exists.name"] = "文件是否存在",
        ["file.exists.desc"] = "检查文件或文件夹是否存在。",
        ["file.exists.path.label"] = "文件",
        ["file.exists.path.hint"] = "要查找的文件或文件夹。只写名称时会相对宏文件夹解析。",
        ["file.exists.resultVariable.label"] = "结果变量",
        ["file.exists.resultVariable.hint"] = "接收 true 或 false 的变量。",

        ["file.delete.name"] = "删除文件",
        ["file.delete.desc"] = "删除一个文件。",
        ["file.delete.path.label"] = "文件",
        ["file.delete.path.hint"] = "要删除的文件。只写文件名时会相对宏文件夹解析。",

        ["file.copy.name"] = "复制文件",
        ["file.copy.desc"] = "把文件复制到另一个位置。",
        ["file.copy.from.label"] = "源文件",
        ["file.copy.from.hint"] = "要复制的文件。只写文件名时会相对宏文件夹解析。",
        ["file.copy.to.label"] = "目标",
        ["file.copy.to.hint"] = "副本要放到哪里。只写文件名时会相对宏文件夹解析。",
        ["file.copy.overwrite.label"] = "覆盖",
        ["file.copy.overwrite.hint"] = "目标已存在时是否替换。",

        ["file.move.name"] = "移动 / 重命名文件",
        ["file.move.desc"] = "把文件移到别处，同名目录里换个名字就是重命名。",
        ["file.move.from.label"] = "源文件",
        ["file.move.from.hint"] = "要移动的文件。只写文件名时会相对宏文件夹解析。",
        ["file.move.to.label"] = "目标",
        ["file.move.to.hint"] = "移到哪里，连文件名一起写。只写文件名时会相对宏文件夹解析。",
        ["file.move.overwrite.label"] = "覆盖",
        ["file.move.overwrite.hint"] = "目标已存在时是否替换。",

        ["file.createFolder.name"] = "新建文件夹",
        ["file.createFolder.desc"] = "创建文件夹，上面缺的目录会一起建出来。",
        ["file.createFolder.path.label"] = "文件夹",
        ["file.createFolder.path.hint"] = "要创建的文件夹。只写名字时会相对宏文件夹解析。",

        ["file.path.name"] = "路径处理",
        ["file.path.desc"] = "算出路径的一部分：拼接、拆开，或者看它指向哪里。",
        ["file.path.operation.label"] = "要算什么",
        ["file.path.operation.hint"] = "“拼接文件夹和文件名”把路径和下面的名字接起来；其余几项各取路径的一部分，或者给出固定位置的文件夹。",
        ["file.path.operation.option.combine"] = "拼接文件夹和文件名",
        ["file.path.operation.option.folder"] = "所在的文件夹",
        ["file.path.operation.option.name"] = "文件名",
        ["file.path.operation.option.baseName"] = "文件名（不带扩展名）",
        ["file.path.operation.option.extension"] = "扩展名",
        ["file.path.operation.option.full"] = "完整路径",
        ["file.path.operation.option.temp"] = "临时文件夹",
        ["file.path.operation.option.macros"] = "宏文件夹",
        ["file.path.path.label"] = "路径",
        ["file.path.path.hint"] = "要处理的路径。选两个文件夹相关的项时用不到它。",
        ["file.path.name.label"] = "名字",
        ["file.path.name.hint"] = "拼接时接在后面的部分，只有“拼接文件夹和文件名”用得到。",
        ["file.path.resultVariable.label"] = "结果变量",
        ["file.path.resultVariable.hint"] = "接收算出来的结果的变量。",

        ["file.unzip.name"] = "解压",
        ["file.unzip.desc"] = "把 zip 压缩包解压到文件夹。",
        ["file.unzip.from.label"] = "压缩包",
        ["file.unzip.from.hint"] = "要解压的 zip 文件。只写文件名时会相对宏文件夹解析。",
        ["file.unzip.folder.label"] = "解压到",
        ["file.unzip.folder.hint"] = "内容解压到哪个文件夹，不存在时会建出来。",
        ["file.unzip.overwrite.label"] = "覆盖",
        ["file.unzip.overwrite.hint"] = "目标已存在同名文件时是否替换。",

        ["file.deleteFolder.name"] = "删除文件夹",
        ["file.deleteFolder.desc"] = "删除文件夹，需要时连里面的东西一起删。",
        ["file.deleteFolder.path.label"] = "文件夹",
        ["file.deleteFolder.path.hint"] = "要删除的文件夹。只写名字时会相对宏文件夹解析。",
        ["file.deleteFolder.recurse.label"] = "连里面的内容一起删",
        ["file.deleteFolder.recurse.hint"] = "不勾选时，文件夹里还有东西就原样留着，不会误删。",

        ["file.listFiles.name"] = "列出文件",
        ["file.listFiles.desc"] = "把文件夹里的文件收集成列表。",
        ["file.listFiles.folder.label"] = "文件夹",
        ["file.listFiles.folder.hint"] = "要在其中查找的文件夹。只写名称时会相对宏文件夹解析。",
        ["file.listFiles.pattern.label"] = "匹配模式",
        ["file.listFiles.pattern.hint"] = "要收集哪些文件，例如 *.txt。",
        ["file.listFiles.recurse.label"] = "包含子文件夹",
        ["file.listFiles.resultVariable.label"] = "结果变量",
        ["file.listFiles.resultVariable.hint"] = "接收完整路径列表的变量。",

        ["file.readJson.name"] = "读取 JSON",
        ["file.readJson.desc"] = "从 JSON 文件中读取一个值。",
        ["file.readJson.path.label"] = "文件",
        ["file.readJson.path.hint"] = "要读取的 JSON 文件。只写文件名时会相对宏文件夹解析。",
        ["file.readJson.query.label"] = "位置",
        ["file.readJson.query.hint"] = "值的路径，例如 server.name 或 items[0].id。留空表示整个文件。",
        ["file.readJson.resultVariable.label"] = "结果变量",
        ["file.readJson.resultVariable.hint"] = "接收该值的变量。",

        ["file.writeJson.name"] = "写入 JSON",
        ["file.writeJson.desc"] = "设置 JSON 文件中的一个值，保留其余内容。",
        ["file.writeJson.path.label"] = "文件",
        ["file.writeJson.path.hint"] = "要更新的 JSON 文件。只写文件名时会相对宏文件夹解析。",
        ["file.writeJson.query.label"] = "位置",
        ["file.writeJson.query.hint"] = "值的路径。途经的缺失对象会自动创建。",
        ["file.writeJson.value.label"] = "值",
        ["file.writeJson.value.hint"] = "要存入的值。",

        ["file.readCsv.name"] = "读取 CSV",
        ["file.readCsv.desc"] = "把 CSV 文件读取成行列表。",
        ["file.readCsv.path.label"] = "文件",
        ["file.readCsv.path.hint"] = "要读取的 CSV 文件。只写文件名时会相对宏文件夹解析。",
        ["file.readCsv.separator.label"] = "分隔符",
        ["file.readCsv.separator.hint"] = "两个单元格之间的字符。",
        ["file.readCsv.separator.option.comma"] = "逗号 ,",
        ["file.readCsv.separator.option.semicolon"] = "分号 ;",
        ["file.readCsv.separator.option.tab"] = "制表符",
        ["file.readCsv.separator.option.pipe"] = "竖线 |",
        ["file.readCsv.hasHeader.label"] = "首行是表头",
        ["file.readCsv.hasHeader.hint"] = "结果中不包含第一行。",
        ["file.readCsv.resultVariable.label"] = "结果变量",
        ["file.readCsv.resultVariable.hint"] = "接收行列表的变量，每行是一个单元格列表。",
        ["file.readCsv.encoding.label"] = "编码",
        ["file.readCsv.encoding.hint"] = EncodingHintText,
        ["file.readCsv.encoding.option.utf8"] = EncodingUtf8,
        ["file.readCsv.encoding.option.utf8bom"] = EncodingUtf8Bom,
        ["file.readCsv.encoding.option.gbk"] = EncodingGbk,
        ["file.readCsv.encoding.option.utf16"] = EncodingUtf16,

        ["file.writeCsv.name"] = "写入 CSV",
        ["file.writeCsv.desc"] = "把行列表写入 CSV 文件。",
        ["file.writeCsv.path.label"] = "文件",
        ["file.writeCsv.path.hint"] = "要写入的 CSV 文件。只写文件名时会相对宏文件夹解析。",
        ["file.writeCsv.rows.label"] = "行",
        ["file.writeCsv.rows.hint"] = "行列表。每一行本身也可以是一个单元格列表。",
        ["file.writeCsv.separator.label"] = "分隔符",
        ["file.writeCsv.separator.hint"] = "两个单元格之间的字符。",
        ["file.writeCsv.separator.option.comma"] = "逗号 ,",
        ["file.writeCsv.separator.option.semicolon"] = "分号 ;",
        ["file.writeCsv.separator.option.tab"] = "制表符",
        ["file.writeCsv.separator.option.pipe"] = "竖线 |",
        ["file.writeCsv.encoding.label"] = "编码",
        ["file.writeCsv.encoding.hint"] = EncodingHintText,
        ["file.writeCsv.encoding.option.utf8"] = EncodingUtf8,
        ["file.writeCsv.encoding.option.utf8bom"] = EncodingUtf8Bom,
        ["file.writeCsv.encoding.option.gbk"] = EncodingGbk,
        ["file.writeCsv.encoding.option.utf16"] = EncodingUtf16,

        ["file.saveVariables.name"] = "保存变量",
        ["file.saveVariables.desc"] = "把变量写入 JSON 文件，方便下次运行读取。",
        ["file.saveVariables.path.label"] = "文件",
        ["file.saveVariables.path.hint"] = "要写入的文件。只写文件名时会相对宏文件夹解析。",
        ["file.saveVariables.names.label"] = "哪些变量",
        ["file.saveVariables.names.hint"] = "要保存的名称，用逗号分隔。留空表示所有局部变量和共享变量。",

        ["file.loadVariables.name"] = "读取变量",
        ["file.loadVariables.desc"] = "读取由“保存变量”写出的文件，恢复变量。",
        ["file.loadVariables.path.label"] = "文件",
        ["file.loadVariables.path.hint"] = "要读取的文件。只写文件名时会相对宏文件夹解析。",

        // ---------------------------------------------------------------- clipboard
        ["clipboard.writeText.name"] = "复制到剪贴板",
        ["clipboard.writeText.desc"] = "把文本放进剪贴板，相当于复制。",
        ["clipboard.writeText.text.label"] = "文本",
        ["clipboard.writeText.text.hint"] = "要放进剪贴板的文本。",

        ["clipboard.readText.name"] = "读取剪贴板",
        ["clipboard.readText.desc"] = "把剪贴板上的文本读入变量。",
        ["clipboard.readText.resultVariable.label"] = "结果变量",
        ["clipboard.readText.resultVariable.hint"] = "接收剪贴板文本的变量。",

        ["clipboard.readImage.name"] = "读取剪贴板图片",
        ["clipboard.readImage.desc"] = "把剪贴板上的图片读进图像变量。",
        ["clipboard.readImage.resultVariable.label"] = "结果变量",
        ["clipboard.readImage.resultVariable.hint"] = "接收图片的变量，可以交给找图步骤在屏幕上找。$变量名.width、.height 是它的尺寸；剪贴板上的图片没有屏幕位置，所以没有 .x。",

        ["clipboard.writeImage.name"] = "复制图片到剪贴板",
        ["clipboard.writeImage.desc"] = "把一张图片放到剪贴板上，等同于复制它。",
        ["clipboard.writeImage.image.label"] = "图片",
        ["clipboard.writeImage.image.hint"] = "可以是图片文件，也可以是前面步骤填好的图像变量。",

        ["clipboard.readFiles.name"] = "读取剪贴板文件",
        ["clipboard.readFiles.desc"] = "把剪贴板上的文件路径读成列表。",
        ["clipboard.readFiles.resultVariable.label"] = "结果变量",
        ["clipboard.readFiles.resultVariable.hint"] = "接收完整路径列表的变量；剪贴板上没有文件时是空列表。",

        ["clipboard.writeFiles.name"] = "复制文件到剪贴板",
        ["clipboard.writeFiles.desc"] = "把文件放到剪贴板上，粘贴出来的是文件本身。",
        ["clipboard.writeFiles.files.label"] = "文件",
        ["clipboard.writeFiles.files.hint"] = "路径列表，也可以只写一个路径。相对路径按宏文件夹解析；每个文件都要真的存在，否则粘贴时会在对方程序里悄悄失败。",

        ["clipboard.clear.name"] = "清空剪贴板",
        ["clipboard.clear.desc"] = "清空剪贴板内容。",

        ["clipboard.waitChange.name"] = "等待剪贴板",
        ["clipboard.waitChange.desc"] = "等待剪贴板上有新的内容被复制。",
        ["clipboard.waitChange.timeoutMs.label"] = "超时毫秒",
        ["clipboard.waitChange.timeoutMs.hint"] = "最多等待多久，超时即失败。",
        ["clipboard.waitChange.resultVariable.label"] = "结果变量",
        ["clipboard.waitChange.resultVariable.hint"] = "接收新文本的变量，留空表示只等待不保存。",

        ["clipboard.copy.name"] = "复制",
        ["clipboard.copy.desc"] = "发送复制快捷键，并保留复制到的内容。",
        ["clipboard.copy.keys.label"] = "快捷键",
        ["clipboard.copy.keys.hint"] = "用 + 连接，用于复制所选内容。",
        ["clipboard.copy.timeoutMs.label"] = "超时毫秒",
        ["clipboard.copy.timeoutMs.hint"] = "等待剪贴板变化的时长。",
        ["clipboard.copy.resultVariable.label"] = "结果变量",
        ["clipboard.copy.resultVariable.hint"] = "接收复制内容的变量。",

        ["clipboard.paste.name"] = "粘贴",
        ["clipboard.paste.desc"] = "把文本放进剪贴板，并发送粘贴快捷键。",
        ["clipboard.paste.text.label"] = "文本",
        ["clipboard.paste.text.hint"] = "要粘贴的文本。留空表示直接粘贴剪贴板里已有的内容。",
        ["clipboard.paste.keys.label"] = "快捷键",
        ["clipboard.paste.keys.hint"] = "用 + 连接，用于粘贴。",

        // ------------------------------------------------------------------ process
        ["process.start.name"] = "启动程序",
        ["process.start.desc"] = "启动另一个程序，可以选择不显示窗口。",
        ["process.start.file.label"] = "程序",
        ["process.start.file.hint"] = "要启动的程序，例如 notepad.exe。",
        ["process.start.arguments.label"] = "参数",
        ["process.start.arguments.hint"] = "传给程序的参数。",
        ["process.start.workingDirectory.label"] = "工作目录",
        ["process.start.workingDirectory.hint"] = "程序在哪个目录下启动。",
        ["process.start.hidden.label"] = "隐藏窗口",
        ["process.start.hidden.hint"] = "启动时不显示程序窗口。",
        ["process.start.runAsAdmin.label"] = "以管理员身份运行",
        ["process.start.runAsAdmin.hint"] = "请 Windows 用管理员权限启动这个程序。系统会弹出自己的确认框，拒绝就让这一步失败。以管理员身份启动的程序无法隐藏窗口。",
        ["process.start.environment.label"] = "环境变量",
        ["process.start.environment.hint"] = "这个程序启动时使用的环境变量，一行一个 NAME=value。留空表示沿用维克多自己的环境变量。以 # 开头的行会被忽略。自己带环境变量启动时，这里要写程序本身，不能写文档或快捷方式。",
        ["process.start.resultVariable.label"] = "结果变量",
        ["process.start.resultVariable.hint"] = "接收进程 id 的变量。",

        ["process.waitFor.name"] = "等待程序",
        ["process.waitFor.desc"] = "等待某个程序开始运行。",
        ["process.waitFor.name.label"] = "程序",
        ["process.waitFor.name.hint"] = "要等待的程序名。",
        ["process.waitFor.timeoutMs.label"] = "超时毫秒",
        ["process.waitFor.timeoutMs.hint"] = "最多等待多久，超时即失败。",
        ["process.waitFor.resultVariable.label"] = "结果变量",
        ["process.waitFor.resultVariable.hint"] = "接收进程 id 的变量。",

        ["process.waitExit.name"] = "等待程序结束",
        ["process.waitExit.desc"] = "等待本宏启动的某个程序结束。",
        ["process.waitExit.id.label"] = "进程 id",
        ["process.waitExit.id.hint"] = "要等待的进程，通常是“启动程序”返回的 id。",
        ["process.waitExit.timeoutMs.label"] = "超时毫秒",
        ["process.waitExit.timeoutMs.hint"] = "最多等待多久，超时即失败。",
        ["process.waitExit.resultVariable.label"] = "结果变量",
        ["process.waitExit.resultVariable.hint"] = "接收退出码的变量。",

        ["process.exists.name"] = "程序是否在运行",
        ["process.exists.desc"] = "检查某个程序是否正在运行。",
        ["process.exists.name.label"] = "程序",
        ["process.exists.name.hint"] = "要查找的程序名。",
        ["process.exists.resultVariable.label"] = "结果变量",
        ["process.exists.resultVariable.hint"] = "接收 true 或 false 的变量。",

        ["process.list.name"] = "列出程序",
        ["process.list.desc"] = "把正在运行的程序名收集成列表。",
        ["process.list.resultVariable.label"] = "结果变量",
        ["process.list.resultVariable.hint"] = "接收名称列表的变量。",

        ["process.kill.name"] = "结束程序",
        ["process.kill.desc"] = "关闭一个程序，默认先请它正常退出。",
        ["process.kill.target.label"] = "程序",
        ["process.kill.target.hint"] = "程序名，或进程 id。",
        ["process.kill.force.label"] = "强制关闭",
        ["process.kill.force.hint"] = "直接结束，而不是先请它退出。",
        ["process.kill.resultVariable.label"] = "结果变量",
        ["process.kill.resultVariable.hint"] = "接收关闭了几个进程的变量。",

        ["command.run.name"] = "执行命令",
        ["command.run.desc"] = "执行一条命令并收集它的输出。",
        ["command.run.file.label"] = "命令",
        ["command.run.file.hint"] = "要运行的程序，例如 cmd.exe。",
        ["command.run.arguments.label"] = "参数",
        ["command.run.arguments.hint"] = "传给命令的参数。",
        ["command.run.workingDirectory.label"] = "工作目录",
        ["command.run.workingDirectory.hint"] = "命令在哪个目录下运行。",
        ["command.run.environment.label"] = "环境变量",
        ["command.run.environment.hint"] = "这条命令运行时使用的环境变量，一行一个 NAME=value。留空表示沿用维克多自己的环境变量。以 # 开头的行会被忽略。",
        ["command.run.standardInput.label"] = "标准输入",
        ["command.run.standardInput.hint"] = "这条命令从标准输入读到的东西。留空表示不给它任何输入。按 UTF-8 发送，里面的 $变量 会替换成那个变量的值。",
        ["command.run.timeoutMs.label"] = "超时毫秒",
        ["command.run.timeoutMs.hint"] = "命令最多可以运行多久。",
        ["command.run.streamOutput.label"] = "输出实时写入日志",
        ["command.run.streamOutput.hint"] = "命令还在跑的时候，它打印的每一行就立刻出现在运行日志里，长时间跑的构建或脚本可以这样看着进度。结果变量里仍然是完整输出。",
        ["command.run.outputEncoding.label"] = "输出编码",
        ["command.run.outputEncoding.hint"] = "命令按哪个编码打印。默认按本机自己的代码页读，Windows 自带的程序（cmd.exe、Windows PowerShell、Python）输出到管道时用的就是它；Node.js 这类无论在哪个系统都按 UTF-8 输出的程序，要在这里改成 UTF-8，否则中文会变成问号。",
        ["command.run.outputEncoding.option.system"] = "本机代码页",
        ["command.run.outputEncoding.option.utf8"] = "UTF-8",
        ["command.run.outputEncoding.option.utf16"] = "UTF-16",
        ["command.run.resultVariable.label"] = "结果变量",
        ["command.run.resultVariable.hint"] = "接收命令输出的变量。",
        ["command.run.errorVariable.label"] = "错误变量",
        ["command.run.errorVariable.hint"] = "接收错误输出的变量。",
        ["command.run.exitCodeVariable.label"] = "退出码变量",
        ["command.run.exitCodeVariable.hint"] = "接收退出码的变量。",

        // ------------------------------------------------------------------ system
        ["system.info.name"] = "系统信息",
        ["system.info.desc"] = "读取关于这台机器的一条信息，例如用户名或某个目录。",
        ["system.info.field.label"] = "字段",
        ["system.info.field.hint"] = "要读取哪一项。",
        ["system.info.field.option.userName"] = "用户名",
        ["system.info.field.option.machineName"] = "计算机名",
        ["system.info.field.option.userDomain"] = "域",
        ["system.info.field.option.osVersion"] = "Windows 版本",
        ["system.info.field.option.processorCount"] = "处理器数量",
        ["system.info.field.option.systemFolder"] = "Windows 目录",
        ["system.info.field.option.tempFolder"] = "临时目录",
        ["system.info.field.option.userFolder"] = "用户目录",
        ["system.info.field.option.desktopFolder"] = "桌面",
        ["system.info.field.option.documentsFolder"] = "文档",
        ["system.info.field.option.downloadsFolder"] = "下载",
        ["system.info.field.option.startupFolder"] = "启动目录",
        ["system.info.field.option.appDataFolder"] = "AppData",
        ["system.info.field.option.programFiles"] = "Program Files",
        ["system.info.field.option.networkConnected"] = "网络已连接",
        ["system.info.field.option.networkNames"] = "连接的网卡",
        ["system.info.field.option.localIp"] = "本机 IP",
        ["system.info.field.option.batteryPercent"] = "电池百分比",
        ["system.info.field.option.onAcPower"] = "已接电源",
        ["system.info.field.option.monitorCount"] = "显示器数量",
        ["system.info.field.option.monitorBounds"] = "显示器位置",
        ["system.info.field.option.dpi"] = "DPI",
        ["system.info.field.option.dpiPercent"] = "缩放百分比",
        ["system.info.field.option.uptimeSeconds"] = "已开机秒数",
        ["system.info.resultVariable.label"] = "结果变量",
        ["system.info.resultVariable.hint"] = "接收该值的变量。",

        ["system.environment.name"] = "环境变量",
        ["system.environment.desc"] = "读取一个环境变量。",
        ["system.environment.name.label"] = "名称",
        ["system.environment.name.hint"] = "环境变量的名称。",
        ["system.environment.resultVariable.label"] = "结果变量",
        ["system.environment.resultVariable.hint"] = "接收该值的变量。",
        ["system.power.name"] = "电源",
        ["system.power.desc"] = "锁屏、关闭显示器、睡眠、注销、重启或关闭这台电脑。",
        ["system.power.what.label"] = "执行",
        ["system.power.what.hint"] = "开始菜单电源按钮里的那些事。锁屏和关闭显示器不会有任何损失；注销、重启和关机都会关掉正在运行的程序，没保存的东西会跟着丢。",
        ["system.power.what.option.lock"] = "锁屏",
        ["system.power.what.option.monitorOff"] = "关闭显示器",
        ["system.power.what.option.signOut"] = "注销",
        ["system.power.what.option.sleep"] = "睡眠",
        ["system.power.what.option.hibernate"] = "休眠",
        ["system.power.what.option.restart"] = "重启",
        ["system.power.what.option.shutDown"] = "关机",
        ["system.power.what.option.abortShutdown"] = "取消倒计时中的关机",
        ["system.power.graceSeconds.label"] = "提示秒数",
        ["system.power.graceSeconds.hint"] = "重启或关机前给多少秒提醒：屏幕上会出现倒计时，这期间还能用\"取消倒计时中的关机\"或 shutdown /a 反悔。填 0 表示立刻执行。其他选项用不到这个值。",
        ["system.volume.name"] = "音量",
        ["system.volume.desc"] = "读取或调整 Windows 正在用的那只音箱的音量。",
        ["system.volume.what.label"] = "执行",
        ["system.volume.what.hint"] = "读取音量、设成某个数值、调大调小几点，或者静音/取消静音。这是整台机器的音量，和键盘上的音量键不是一回事——音量键调的是当前获得焦点的那个窗口。",
        ["system.volume.what.option.get"] = "读取",
        ["system.volume.what.option.set"] = "设为指定值",
        ["system.volume.what.option.up"] = "调大",
        ["system.volume.what.option.down"] = "调小",
        ["system.volume.what.option.mute"] = "静音",
        ["system.volume.what.option.unmute"] = "取消静音",
        ["system.volume.what.option.toggleMute"] = "静音/取消静音",
        ["system.volume.percent.label"] = "音量百分比",
        ["system.volume.percent.hint"] = "要设成的音量，0 到 100。被\"设为指定值\"使用。",
        ["system.volume.stepPercent.label"] = "调整幅度",
        ["system.volume.stepPercent.hint"] = "音量调大或调小多少个百分点。被\"调大\"和\"调小\"使用，两端都不会超过 0 和 100。",
        ["system.volume.resultVariable.label"] = "结果变量",
        ["system.volume.resultVariable.hint"] = "接收调整后音量的变量，0 到 100。只做静音的步骤也会把当前音量记下来。",
        ["system.ime.name"] = "输入法",
        ["system.ime.desc"] = "读取最前面那个窗口的键盘布局，或者把它切到另一种布局。",
        ["system.ime.what.label"] = "执行",
        ["system.ime.what.hint"] = "这里说的都是最前面那个窗口——人正在打字的那个。宏在中文布局下发送西文按键，拿到的是候选词而不是快捷键，所以先切到英文布局往往就是宏能不能用的关键。中文输入法自己的中英开关只能靠按键去关（Windows 把这个状态记在正在打字的那个程序里），发 Ctrl+Space 或 Shift 就是那件事。",
        ["system.ime.what.option.get"] = "当前是哪种布局",
        ["system.ime.what.option.list"] = "列出已安装的布局",
        ["system.ime.what.option.switch"] = "切换到另一种布局",
        ["system.ime.layout.label"] = "布局",
        ["system.ime.layout.hint"] = "要切换到的布局，被\"切换到另一种布局\"使用。写名字的一部分就能匹配；可选的名字用\"列出已安装的布局\"查出来。这一步会等到窗口真的换过去，所以下一步可以放心按那种语言打字。",
        ["system.ime.resultVariable.label"] = "结果变量",
        ["system.ime.resultVariable.hint"] = "接收结果的变量：当前布局名，或者可以切换过去的布局列表。",
        ["system.brightness.name"] = "屏幕亮度",
        ["system.brightness.desc"] = "读取或调整屏幕的亮度。",
        ["system.brightness.what.label"] = "执行",
        ["system.brightness.what.hint"] = "读取亮度、设成某个数值、调大或调小几点。每一台肯回应的屏幕会一起调——这是直接跟显示器通过视频线对话，和显示器上的亮度按钮是同一件事，所以笔记本内置屏或者没有带这个功能的屏幕可能完全没有回应。",
        ["system.brightness.what.option.get"] = "读取",
        ["system.brightness.what.option.set"] = "设为指定值",
        ["system.brightness.what.option.up"] = "调亮",
        ["system.brightness.what.option.down"] = "调暗",
        ["system.brightness.percent.label"] = "亮度百分比",
        ["system.brightness.percent.hint"] = "要设成的亮度，0 到 100。被\"设为指定值\"使用。",
        ["system.brightness.stepPercent.label"] = "调整幅度",
        ["system.brightness.stepPercent.hint"] = "亮度调亮或调暗多少个百分点。被\"调亮\"和\"调暗\"使用，两端都不会超过 0 和 100。",
        ["system.brightness.resultVariable.label"] = "结果变量",
        ["system.brightness.resultVariable.hint"] = "接收调整后屏幕亮度的变量，0 到 100。",

        // ------------------------------------------------------------------ window
        ["window.exists.name"] = "窗口是否存在",
        ["window.exists.desc"] = "检查某个标题的窗口是否已经打开。",
        ["window.exists.title.label"] = "窗口",
        ["window.exists.title.hint"] = WindowTitleHint,
        ["window.exists.matchBy.label"] = "匹配方式",
        ["window.exists.matchBy.hint"] = WindowMatchByHint,
        ["window.exists.matchBy.option.title"] = WindowMatchByTitle,
        ["window.exists.matchBy.option.process"] = WindowMatchByProcess,
        ["window.exists.matchBy.option.class"] = WindowMatchByClass,
        ["window.exists.resultVariable.label"] = "结果变量",
        ["window.exists.resultVariable.hint"] = "接收 true 或 false 的变量。",

        ["window.waitFor.name"] = "等待窗口",
        ["window.waitFor.desc"] = "等待某个标题的窗口出现。",
        ["window.waitFor.title.label"] = "窗口",
        ["window.waitFor.title.hint"] = WindowTitleHint,
        ["window.waitFor.matchBy.label"] = "匹配方式",
        ["window.waitFor.matchBy.hint"] = WindowMatchByHint,
        ["window.waitFor.matchBy.option.title"] = WindowMatchByTitle,
        ["window.waitFor.matchBy.option.process"] = WindowMatchByProcess,
        ["window.waitFor.matchBy.option.class"] = WindowMatchByClass,
        ["window.waitFor.timeoutMs.label"] = "超时毫秒",
        ["window.waitFor.timeoutMs.hint"] = "最多等待多久，超时即失败。",
        ["window.waitFor.resultVariable.label"] = "结果变量",
        ["window.waitFor.resultVariable.hint"] = "接收该窗口标题的变量。",

        ["window.activate.name"] = "激活窗口",
        ["window.activate.desc"] = "把窗口调到最前，若已最小化则先恢复。",
        ["window.activate.title.label"] = "窗口",
        ["window.activate.title.hint"] = WindowTitleHint,
        ["window.activate.matchBy.label"] = "匹配方式",
        ["window.activate.matchBy.hint"] = WindowMatchByHint,
        ["window.activate.matchBy.option.title"] = WindowMatchByTitle,
        ["window.activate.matchBy.option.process"] = WindowMatchByProcess,
        ["window.activate.matchBy.option.class"] = WindowMatchByClass,

        ["window.minimize.name"] = "最小化窗口",
        ["window.minimize.desc"] = "把窗口最小化到任务栏。",
        ["window.minimize.title.label"] = "窗口",
        ["window.minimize.title.hint"] = WindowTitleHint,
        ["window.minimize.matchBy.label"] = "匹配方式",
        ["window.minimize.matchBy.hint"] = WindowMatchByHint,
        ["window.minimize.matchBy.option.title"] = WindowMatchByTitle,
        ["window.minimize.matchBy.option.process"] = WindowMatchByProcess,
        ["window.minimize.matchBy.option.class"] = WindowMatchByClass,

        ["window.maximize.name"] = "最大化窗口",
        ["window.maximize.desc"] = "让窗口铺满整个屏幕。",
        ["window.maximize.title.label"] = "窗口",
        ["window.maximize.title.hint"] = WindowTitleHint,
        ["window.maximize.matchBy.label"] = "匹配方式",
        ["window.maximize.matchBy.hint"] = WindowMatchByHint,
        ["window.maximize.matchBy.option.title"] = WindowMatchByTitle,
        ["window.maximize.matchBy.option.process"] = WindowMatchByProcess,
        ["window.maximize.matchBy.option.class"] = WindowMatchByClass,

        ["window.restore.name"] = "还原窗口",
        ["window.restore.desc"] = "把最小化或最大化的窗口恢复成正常大小。",
        ["window.restore.title.label"] = "窗口",
        ["window.restore.title.hint"] = WindowTitleHint,
        ["window.restore.matchBy.label"] = "匹配方式",
        ["window.restore.matchBy.hint"] = WindowMatchByHint,
        ["window.restore.matchBy.option.title"] = WindowMatchByTitle,
        ["window.restore.matchBy.option.process"] = WindowMatchByProcess,
        ["window.restore.matchBy.option.class"] = WindowMatchByClass,

        ["window.move.name"] = "移动窗口",
        ["window.move.desc"] = "移动窗口并给它一个新的大小。",
        ["window.move.title.label"] = "窗口",
        ["window.move.title.hint"] = WindowTitleHint,
        ["window.move.matchBy.label"] = "匹配方式",
        ["window.move.matchBy.hint"] = WindowMatchByHint,
        ["window.move.matchBy.option.title"] = WindowMatchByTitle,
        ["window.move.matchBy.option.process"] = WindowMatchByProcess,
        ["window.move.matchBy.option.class"] = WindowMatchByClass,
        ["window.move.x.label"] = "X",
        ["window.move.x.hint"] = "左边缘的屏幕横坐标。",
        ["window.move.y.label"] = "Y",
        ["window.move.y.hint"] = "上边缘的屏幕纵坐标。",
        ["window.move.width.label"] = "宽度",
        ["window.move.width.hint"] = "新的宽度，单位像素。",
        ["window.move.height.label"] = "高度",
        ["window.move.height.hint"] = "新的高度，单位像素。",

        ["window.close.name"] = "关闭窗口",
        ["window.close.desc"] = "请求关闭窗口，相当于点击关闭按钮。",
        ["window.close.title.label"] = "窗口",
        ["window.close.title.hint"] = WindowTitleHint,
        ["window.close.matchBy.label"] = "匹配方式",
        ["window.close.matchBy.hint"] = WindowMatchByHint,
        ["window.close.matchBy.option.title"] = WindowMatchByTitle,
        ["window.close.matchBy.option.process"] = WindowMatchByProcess,
        ["window.close.matchBy.option.class"] = WindowMatchByClass,

        ["window.list.name"] = "列出窗口",
        ["window.list.desc"] = "把打开的窗口标题收集成列表，也可以只留符合条件的那些。",
        ["window.list.filter.label"] = "筛选文字",
        ["window.list.filter.hint"] = "只保留标题、进程名或窗口类名里含有这段文字的窗口。留空表示全部。",
        ["window.list.filterBy.label"] = "按什么筛选",
        ["window.list.filterBy.hint"] = "筛选文字和窗口的哪一部分比较。",
        ["window.list.filterBy.option.title"] = WindowMatchByTitle,
        ["window.list.filterBy.option.process"] = WindowMatchByProcess,
        ["window.list.filterBy.option.class"] = WindowMatchByClass,
        ["window.list.resultVariable.label"] = "结果变量",
        ["window.list.resultVariable.hint"] = "接收标题列表的变量。",

        ["window.info.name"] = "窗口信息",
        ["window.info.desc"] = "把窗口的位置和大小读进变量。",
        ["window.info.title.label"] = "窗口",
        ["window.info.title.hint"] = WindowTitleHint,
        ["window.info.matchBy.label"] = "匹配方式",
        ["window.info.matchBy.hint"] = WindowMatchByHint,
        ["window.info.matchBy.option.title"] = WindowMatchByTitle,
        ["window.info.matchBy.option.process"] = WindowMatchByProcess,
        ["window.info.matchBy.option.class"] = WindowMatchByClass,
        ["window.info.resultVariable.label"] = "结果变量",
        ["window.info.resultVariable.hint"] = "接收窗口矩形的变量，写法是 x,y,宽,高，可以直接当搜索区域用；.x、.y、.width、.height 是各个部分，.title 是标题栏上的字。",

        // -------------------------------------------------------------------- input
        ["input.keyPress.name"] = "按键",
        ["input.keyPress.desc"] = "按下并松开一个按键。",
        ["input.keyPress.key.label"] = "按键",
        ["input.keyPress.key.hint"] = "要按下的键，例如 F5 或 Enter。",
        ["input.keyPress.holdMs.label"] = "按住毫秒",
        ["input.keyPress.holdMs.hint"] = "按键保持按下的时长。",
        ["input.keyPress.repeat.label"] = "重复次数",
        ["input.keyPress.repeat.hint"] = "这个键连续按几下。",
        ["input.keyPress.intervalMs.label"] = "重复间隔毫秒",
        ["input.keyPress.intervalMs.hint"] = "每两下之间的等待时间；只按一下就填 0。",

        ["input.keyDown.name"] = "按下按键",
        ["input.keyDown.desc"] = "保持按下某个键，直到对应的“松开按键”步骤。",
        ["input.keyDown.key.label"] = "按键",

        ["input.keyUp.name"] = "松开按键",
        ["input.keyUp.desc"] = "松开当前处于按下状态的按键。",
        ["input.keyUp.key.label"] = "按键",

        ["input.hotkey.name"] = "组合键",
        ["input.hotkey.desc"] = "按下组合键，例如 Ctrl+Shift+S。",
        ["input.hotkey.keys.label"] = "按键组合",
        ["input.hotkey.keys.hint"] = "用 + 连接，同时按下。",
        ["input.hotkey.holdMs.label"] = "按住毫秒",
        ["input.hotkey.holdMs.hint"] = "组合键保持按下的时长。",
        ["input.hotkey.repeat.label"] = "重复次数",
        ["input.hotkey.repeat.hint"] = "这组组合键连续发几次。",
        ["input.hotkey.intervalMs.label"] = "重复间隔毫秒",
        ["input.hotkey.intervalMs.hint"] = "每两次之间的等待时间；只发一次就填 0。",

        ["input.typeText.name"] = "输入文本",
        ["input.typeText.desc"] = "输入一段文字。",
        ["input.typeText.text.label"] = "文本",
        ["input.typeText.text.hint"] = "要输入的文本。",
        ["input.typeText.intervalMs.label"] = "间隔毫秒",
        ["input.typeText.intervalMs.hint"] = "每个字符之间的间隔。",

        ["input.mouseMove.name"] = "鼠标移动到",
        ["input.mouseMove.desc"] = "把光标移动到屏幕上的指定位置。",
        ["input.mouseMove.x.label"] = "X",
        ["input.mouseMove.x.hint"] = "目标屏幕横坐标。",
        ["input.mouseMove.y.label"] = "Y",
        ["input.mouseMove.y.hint"] = "目标屏幕纵坐标。",
        ["input.mouseMove.durationMs.label"] = "用时毫秒",
        ["input.mouseMove.durationMs.hint"] = "0 表示瞬间跳到目标位置。",
        ["input.mouseMove.style.label"] = "移动方式",
        ["input.mouseMove.style.hint"] = "鼠标怎么走过去。弧线会绕开直线；模拟人手在弧线上再带一点抖动、两头慢中间快，看起来不像机器画的。走弧线需要时间，所以瞬时移动会自动借 200 毫秒。",
        ["input.mouseMove.style.option.direct"] = "直线",
        ["input.mouseMove.style.option.smooth"] = "弧线",
        ["input.mouseMove.style.option.human"] = "模拟人手",

        ["input.mouseMoveRelative.name"] = "鼠标相对移动",
        ["input.mouseMoveRelative.desc"] = "在当前光标位置的基础上偏移一段距离。",
        ["input.mouseMoveRelative.dx.label"] = "横向偏移",
        ["input.mouseMoveRelative.dx.hint"] = "水平方向移动的像素数。",
        ["input.mouseMoveRelative.dy.label"] = "纵向偏移",
        ["input.mouseMoveRelative.dy.hint"] = "垂直方向移动的像素数。",
        ["input.mouseMoveRelative.durationMs.label"] = "用时毫秒",
        ["input.mouseMoveRelative.durationMs.hint"] = "0 表示瞬间跳到目标位置。",
        ["input.mouseMoveRelative.style.label"] = "移动方式",
        ["input.mouseMoveRelative.style.hint"] = "鼠标怎么走过去。弧线会绕开直线；模拟人手在弧线上再带一点抖动、两头慢中间快，看起来不像机器画的。走弧线需要时间，所以瞬时移动会自动借 200 毫秒。",
        ["input.mouseMoveRelative.style.option.direct"] = "直线",
        ["input.mouseMoveRelative.style.option.smooth"] = "弧线",
        ["input.mouseMoveRelative.style.option.human"] = "模拟人手",

        ["input.mouseClick.name"] = "鼠标点击",
        ["input.mouseClick.desc"] = "在屏幕指定位置点击鼠标按键。",
        ["input.mouseClick.button.label"] = "按键",
        ["input.mouseClick.x.label"] = "X",
        ["input.mouseClick.x.hint"] = "点击位置的横坐标。",
        ["input.mouseClick.y.label"] = "Y",
        ["input.mouseClick.y.hint"] = "点击位置的纵坐标。",
        ["input.mouseClick.clicks.label"] = "点击次数",
        ["input.mouseClick.clicks.hint"] = "一共发送几次点击。",
        ["input.mouseClick.intervalMs.label"] = "间隔毫秒",
        ["input.mouseClick.intervalMs.hint"] = "连续点击之间的间隔。",
        ["input.mouseClick.holdMs.label"] = "按住毫秒",
        ["input.mouseClick.holdMs.hint"] = "按下后保持多久才松开。填 0 就是普通的一下快点击；需要长按才响应的按钮，把这里调大。",

        ["input.mouseDoubleClick.name"] = "鼠标双击",
        ["input.mouseDoubleClick.desc"] = "在屏幕指定位置双击鼠标按键。",
        ["input.mouseDoubleClick.button.label"] = "按键",
        ["input.mouseDoubleClick.x.label"] = "X",
        ["input.mouseDoubleClick.x.hint"] = "双击位置的横坐标。",
        ["input.mouseDoubleClick.y.label"] = "Y",
        ["input.mouseDoubleClick.y.hint"] = "双击位置的纵坐标。",

        ["input.mouseDown.name"] = "按下鼠标",
        ["input.mouseDown.desc"] = "保持按住鼠标按键，直到对应的“松开鼠标”步骤。",
        ["input.mouseDown.button.label"] = "按键",
        ["input.mouseDown.x.label"] = "X",
        ["input.mouseDown.x.hint"] = "按下位置的横坐标。",
        ["input.mouseDown.y.label"] = "Y",
        ["input.mouseDown.y.hint"] = "按下位置的纵坐标。",

        ["input.mouseUp.name"] = "松开鼠标",
        ["input.mouseUp.desc"] = "松开当前处于按住状态的鼠标按键。",
        ["input.mouseUp.button.label"] = "按键",
        ["input.mouseUp.x.label"] = "X",
        ["input.mouseUp.x.hint"] = "松开位置的横坐标。",
        ["input.mouseUp.y.label"] = "Y",
        ["input.mouseUp.y.hint"] = "松开位置的纵坐标。",

        ["input.mouseScroll.name"] = "鼠标滚轮",
        ["input.mouseScroll.desc"] = "滚动鼠标滚轮。",
        ["input.mouseScroll.direction.label"] = "方向",
        ["input.mouseScroll.unit.label"] = "滚轮单位",
        ["input.mouseScroll.unit.hint"] = "格是滚轮平时一次转动的量；像素把同样的转动量分得更细，120 像素等于一格。只看整数格的程序可能会忽略不足一格的部分。",
        ["input.mouseScroll.unit.option.notches"] = "格",
        ["input.mouseScroll.unit.option.pixels"] = "像素",
        ["input.mouseScroll.amount.label"] = "数量",
        ["input.mouseScroll.amount.hint"] = "滚多远，按上面的单位计算。",
        ["input.mouseScroll.smoothMs.label"] = "平滑毫秒",
        ["input.mouseScroll.smoothMs.hint"] = "把这次滚动摊到这么多毫秒里，分成几小段发送，滚动看起来是滑过去的；填 0 就一次滚完。",
        ["input.mouseScroll.x.label"] = "X",
        ["input.mouseScroll.x.hint"] = "滚动位置的横坐标。",
        ["input.mouseScroll.y.label"] = "Y",
        ["input.mouseScroll.y.hint"] = "滚动位置的纵坐标。",

        ["input.mouseDrag.name"] = "鼠标拖拽",
        ["input.mouseDrag.desc"] = "从一点按住拖到另一点再松开。",
        ["input.mouseDrag.startX.label"] = "起点 X",
        ["input.mouseDrag.startX.hint"] = "拖拽起点的横坐标。",
        ["input.mouseDrag.startY.label"] = "起点 Y",
        ["input.mouseDrag.startY.hint"] = "拖拽起点的纵坐标。",
        ["input.mouseDrag.endX.label"] = "终点 X",
        ["input.mouseDrag.endX.hint"] = "拖拽终点的横坐标。",
        ["input.mouseDrag.endY.label"] = "终点 Y",
        ["input.mouseDrag.endY.hint"] = "拖拽终点的纵坐标。",
        ["input.mouseDrag.button.label"] = "按键",
        ["input.mouseDrag.durationMs.label"] = "用时毫秒",
        ["input.mouseDrag.durationMs.hint"] = "整个拖拽过程的时长。",
        ["input.mouseDrag.steps.label"] = "移动步数",
        ["input.mouseDrag.steps.hint"] = "拖拽过程中发送的中间移动事件数量。",
        ["input.mouseDrag.style.label"] = "移动方式",
        ["input.mouseDrag.style.hint"] = "拖着走的时候鼠标怎么移动。弧线会绕开直线；模拟人手在弧线上再带一点抖动，看起来不像机器画的。",
        ["input.mouseDrag.style.option.direct"] = "直线",
        ["input.mouseDrag.style.option.smooth"] = "弧线",
        ["input.mouseDrag.style.option.human"] = "模拟人手",

        // 输入方式，13 个输入动作共用一组文案。
        ["input.keyPress.inputMode.label"] = "输入方式",
        ["input.keyPress.inputMode.hint"] = InputModeHint,
        ["input.keyPress.inputMode.option.foreground"] = "前台",
        ["input.keyPress.inputMode.option.background"] = "后台消息",
        ["input.keyPress.inputMode.option.driver"] = "驱动级",
        ["input.keyPress.targetWindow.label"] = "目标窗口",
        ["input.keyPress.targetWindow.hint"] = TargetWindowHint,

        ["input.keyDown.inputMode.label"] = "输入方式",
        ["input.keyDown.inputMode.hint"] = InputModeHint,
        ["input.keyDown.inputMode.option.foreground"] = "前台",
        ["input.keyDown.inputMode.option.background"] = "后台消息",
        ["input.keyDown.inputMode.option.driver"] = "驱动级",
        ["input.keyDown.targetWindow.label"] = "目标窗口",
        ["input.keyDown.targetWindow.hint"] = TargetWindowHint,

        ["input.keyUp.inputMode.label"] = "输入方式",
        ["input.keyUp.inputMode.hint"] = InputModeHint,
        ["input.keyUp.inputMode.option.foreground"] = "前台",
        ["input.keyUp.inputMode.option.background"] = "后台消息",
        ["input.keyUp.inputMode.option.driver"] = "驱动级",
        ["input.keyUp.targetWindow.label"] = "目标窗口",
        ["input.keyUp.targetWindow.hint"] = TargetWindowHint,

        ["input.hotkey.inputMode.label"] = "输入方式",
        ["input.hotkey.inputMode.hint"] = InputModeHint,
        ["input.hotkey.inputMode.option.foreground"] = "前台",
        ["input.hotkey.inputMode.option.background"] = "后台消息",
        ["input.hotkey.inputMode.option.driver"] = "驱动级",
        ["input.hotkey.targetWindow.label"] = "目标窗口",
        ["input.hotkey.targetWindow.hint"] = TargetWindowHint,

        ["input.typeText.inputMode.label"] = "输入方式",
        ["input.typeText.inputMode.hint"] = InputModeHint,
        ["input.typeText.inputMode.option.foreground"] = "前台",
        ["input.typeText.inputMode.option.background"] = "后台消息",
        ["input.typeText.inputMode.option.driver"] = "驱动级",
        ["input.typeText.targetWindow.label"] = "目标窗口",
        ["input.typeText.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseMove.inputMode.label"] = "输入方式",
        ["input.mouseMove.inputMode.hint"] = InputModeHint
            + "后台方式下屏幕上的鼠标不会移动，只是让窗口以为鼠标到了那里。",
        ["input.mouseMove.inputMode.option.foreground"] = "前台",
        ["input.mouseMove.inputMode.option.background"] = "后台消息",
        ["input.mouseMove.inputMode.option.driver"] = "驱动级",
        ["input.mouseMove.targetWindow.label"] = "目标窗口",
        ["input.mouseMove.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseMoveRelative.inputMode.label"] = "输入方式",
        ["input.mouseMoveRelative.inputMode.hint"] = InputModeHint
            + "后台方式下屏幕上的鼠标不会移动，只是让窗口以为鼠标到了那里。",
        ["input.mouseMoveRelative.inputMode.option.foreground"] = "前台",
        ["input.mouseMoveRelative.inputMode.option.background"] = "后台消息",
        ["input.mouseMoveRelative.inputMode.option.driver"] = "驱动级",
        ["input.mouseMoveRelative.targetWindow.label"] = "目标窗口",
        ["input.mouseMoveRelative.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseClick.inputMode.label"] = "输入方式",
        ["input.mouseClick.inputMode.hint"] = InputModeHint,
        ["input.mouseClick.inputMode.option.foreground"] = "前台",
        ["input.mouseClick.inputMode.option.background"] = "后台消息",
        ["input.mouseClick.inputMode.option.driver"] = "驱动级",
        ["input.mouseClick.targetWindow.label"] = "目标窗口",
        ["input.mouseClick.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseDoubleClick.inputMode.label"] = "输入方式",
        ["input.mouseDoubleClick.inputMode.hint"] = InputModeHint,
        ["input.mouseDoubleClick.inputMode.option.foreground"] = "前台",
        ["input.mouseDoubleClick.inputMode.option.background"] = "后台消息",
        ["input.mouseDoubleClick.inputMode.option.driver"] = "驱动级",
        ["input.mouseDoubleClick.targetWindow.label"] = "目标窗口",
        ["input.mouseDoubleClick.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseDown.inputMode.label"] = "输入方式",
        ["input.mouseDown.inputMode.hint"] = InputModeHint,
        ["input.mouseDown.inputMode.option.foreground"] = "前台",
        ["input.mouseDown.inputMode.option.background"] = "后台消息",
        ["input.mouseDown.inputMode.option.driver"] = "驱动级",
        ["input.mouseDown.targetWindow.label"] = "目标窗口",
        ["input.mouseDown.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseUp.inputMode.label"] = "输入方式",
        ["input.mouseUp.inputMode.hint"] = InputModeHint,
        ["input.mouseUp.inputMode.option.foreground"] = "前台",
        ["input.mouseUp.inputMode.option.background"] = "后台消息",
        ["input.mouseUp.inputMode.option.driver"] = "驱动级",
        ["input.mouseUp.targetWindow.label"] = "目标窗口",
        ["input.mouseUp.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseScroll.inputMode.label"] = "输入方式",
        ["input.mouseScroll.inputMode.hint"] = InputModeHint,
        ["input.mouseScroll.inputMode.option.foreground"] = "前台",
        ["input.mouseScroll.inputMode.option.background"] = "后台消息",
        ["input.mouseScroll.inputMode.option.driver"] = "驱动级",
        ["input.mouseScroll.targetWindow.label"] = "目标窗口",
        ["input.mouseScroll.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseDrag.inputMode.label"] = "输入方式",
        ["input.mouseDrag.inputMode.hint"] = InputModeHint,
        ["input.mouseDrag.inputMode.option.foreground"] = "前台",
        ["input.mouseDrag.inputMode.option.background"] = "后台消息",
        ["input.mouseDrag.inputMode.option.driver"] = "驱动级",
        ["input.mouseDrag.targetWindow.label"] = "目标窗口",
        ["input.mouseDrag.targetWindow.hint"] = TargetWindowHint,

        // 坐标基准：所有带坐标或矩形的动作共用一组文案。
        ["input.mouseMove.anchorMode.label"] = "坐标基准",
        ["input.mouseMove.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseMove.anchorMode.option.element"] = "界面元素左上角",
        ["input.mouseMove.anchorSelector.label"] = "锚点元素",
        ["input.mouseMove.anchorSelector.hint"] = AnchorElementHint,
        ["input.mouseMove.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseMove.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseMove.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseMove.anchorWindow.label"] = "基准窗口",
        ["input.mouseMove.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseClick.anchorMode.label"] = "坐标基准",
        ["input.mouseClick.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseClick.anchorMode.option.element"] = "界面元素左上角",
        ["input.mouseClick.anchorSelector.label"] = "锚点元素",
        ["input.mouseClick.anchorSelector.hint"] = AnchorElementHint,
        ["input.mouseClick.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseClick.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseClick.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseClick.anchorWindow.label"] = "基准窗口",
        ["input.mouseClick.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseDoubleClick.anchorMode.label"] = "坐标基准",
        ["input.mouseDoubleClick.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseDoubleClick.anchorMode.option.element"] = "界面元素左上角",
        ["input.mouseDoubleClick.anchorSelector.label"] = "锚点元素",
        ["input.mouseDoubleClick.anchorSelector.hint"] = AnchorElementHint,
        ["input.mouseDoubleClick.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseDoubleClick.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseDoubleClick.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseDoubleClick.anchorWindow.label"] = "基准窗口",
        ["input.mouseDoubleClick.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseDown.anchorMode.label"] = "坐标基准",
        ["input.mouseDown.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseDown.anchorMode.option.element"] = "界面元素左上角",
        ["input.mouseDown.anchorSelector.label"] = "锚点元素",
        ["input.mouseDown.anchorSelector.hint"] = AnchorElementHint,
        ["input.mouseDown.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseDown.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseDown.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseDown.anchorWindow.label"] = "基准窗口",
        ["input.mouseDown.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseUp.anchorMode.label"] = "坐标基准",
        ["input.mouseUp.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseUp.anchorMode.option.element"] = "界面元素左上角",
        ["input.mouseUp.anchorSelector.label"] = "锚点元素",
        ["input.mouseUp.anchorSelector.hint"] = AnchorElementHint,
        ["input.mouseUp.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseUp.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseUp.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseUp.anchorWindow.label"] = "基准窗口",
        ["input.mouseUp.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseScroll.anchorMode.label"] = "坐标基准",
        ["input.mouseScroll.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseScroll.anchorMode.option.element"] = "界面元素左上角",
        ["input.mouseScroll.anchorSelector.label"] = "锚点元素",
        ["input.mouseScroll.anchorSelector.hint"] = AnchorElementHint,
        ["input.mouseScroll.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseScroll.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseScroll.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseScroll.anchorWindow.label"] = "基准窗口",
        ["input.mouseScroll.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseDrag.anchorMode.label"] = "坐标基准",
        ["input.mouseDrag.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseDrag.anchorMode.option.element"] = "界面元素左上角",
        ["input.mouseDrag.anchorSelector.label"] = "锚点元素",
        ["input.mouseDrag.anchorSelector.hint"] = AnchorElementHint,
        ["input.mouseDrag.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseDrag.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseDrag.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseDrag.anchorWindow.label"] = "基准窗口",
        ["input.mouseDrag.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.capture.anchorMode.label"] = "坐标基准",
        ["vision.capture.anchorMode.hint"] = AnchorModeHint,
        ["vision.capture.anchorMode.option.element"] = "界面元素左上角",
        ["vision.capture.anchorSelector.label"] = "锚点元素",
        ["vision.capture.anchorSelector.hint"] = AnchorElementHint,
        ["vision.capture.anchorMode.option.screen"] = "屏幕像素",
        ["vision.capture.anchorMode.option.window"] = "窗口左上角",
        ["vision.capture.anchorMode.option.client"] = "窗口客户区",
        ["vision.capture.anchorWindow.label"] = "基准窗口",
        ["vision.capture.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.findImage.anchorMode.label"] = "坐标基准",
        ["vision.findImage.anchorMode.hint"] = AnchorModeHint,
        ["vision.findImage.anchorMode.option.screen"] = "屏幕像素",
        ["vision.findImage.anchorMode.option.window"] = "窗口左上角",
        ["vision.findImage.anchorMode.option.client"] = "窗口客户区",
        ["vision.findImage.anchorWindow.label"] = "基准窗口",
        ["vision.findImage.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.getPixel.anchorMode.label"] = "坐标基准",
        ["vision.getPixel.anchorMode.hint"] = AnchorModeHint,
        ["vision.getPixel.anchorMode.option.screen"] = "屏幕像素",
        ["vision.getPixel.anchorMode.option.window"] = "窗口左上角",
        ["vision.getPixel.anchorMode.option.client"] = "窗口客户区",
        ["vision.getPixel.anchorWindow.label"] = "基准窗口",
        ["vision.getPixel.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.waitColor.anchorMode.label"] = "坐标基准",
        ["vision.waitColor.anchorMode.hint"] = AnchorModeHint,
        ["vision.waitColor.anchorMode.option.screen"] = "屏幕像素",
        ["vision.waitColor.anchorMode.option.window"] = "窗口左上角",
        ["vision.waitColor.anchorMode.option.client"] = "窗口客户区",
        ["vision.waitColor.anchorWindow.label"] = "基准窗口",
        ["vision.waitColor.anchorWindow.hint"] = AnchorWindowHint,

        ["ocr.recognize.anchorMode.label"] = "坐标基准",
        ["ocr.recognize.anchorMode.hint"] = AnchorModeHint,
        ["ocr.recognize.anchorMode.option.screen"] = "屏幕像素",
        ["ocr.recognize.anchorMode.option.window"] = "窗口左上角",
        ["ocr.recognize.anchorMode.option.client"] = "窗口客户区",
        ["ocr.recognize.anchorWindow.label"] = "基准窗口",
        ["ocr.recognize.anchorWindow.hint"] = AnchorWindowHint,

        ["ocr.findText.anchorMode.label"] = "坐标基准",
        ["ocr.findText.anchorMode.hint"] = AnchorModeHint,
        ["ocr.findText.anchorMode.option.screen"] = "屏幕像素",
        ["ocr.findText.anchorMode.option.window"] = "窗口左上角",
        ["ocr.findText.anchorMode.option.client"] = "窗口客户区",
        ["ocr.findText.anchorWindow.label"] = "基准窗口",
        ["ocr.findText.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.imageExists.anchorMode.label"] = "坐标基准",
        ["condition.imageExists.anchorMode.hint"] = AnchorModeHint,
        ["condition.imageExists.anchorMode.option.screen"] = "屏幕像素",
        ["condition.imageExists.anchorMode.option.window"] = "窗口左上角",
        ["condition.imageExists.anchorMode.option.client"] = "窗口客户区",
        ["condition.imageExists.anchorWindow.label"] = "基准窗口",
        ["condition.imageExists.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.textExists.anchorMode.label"] = "坐标基准",
        ["condition.textExists.anchorMode.hint"] = AnchorModeHint,
        ["condition.textExists.anchorMode.option.screen"] = "屏幕像素",
        ["condition.textExists.anchorMode.option.window"] = "窗口左上角",
        ["condition.textExists.anchorMode.option.client"] = "窗口客户区",
        ["condition.textExists.anchorWindow.label"] = "基准窗口",
        ["condition.textExists.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.colorEquals.anchorMode.label"] = "坐标基准",
        ["condition.colorEquals.anchorMode.hint"] = AnchorModeHint,
        ["condition.colorEquals.anchorMode.option.screen"] = "屏幕像素",
        ["condition.colorEquals.anchorMode.option.window"] = "窗口左上角",
        ["condition.colorEquals.anchorMode.option.client"] = "窗口客户区",
        ["condition.colorEquals.anchorWindow.label"] = "基准窗口",
        ["condition.colorEquals.anchorWindow.hint"] = AnchorWindowHint,

        // ------------------------------------- 找图 / 找色做厚：多命中、多区域、多点比色
        ["vision.findImage.matchIndex.label"] = "第几个命中",
        ["vision.findImage.matchIndex.hint"] = MatchIndexHint,
        ["vision.findImage.allMatches.label"] = "记录全部命中",
        ["vision.findImage.allMatches.hint"] = AllMatchesHint,

        ["vision.waitImage.region.label"] = "搜索区域",
        ["vision.waitImage.region.hint"] = RegionHintText,
        ["vision.waitImage.matchIndex.label"] = "第几个命中",
        ["vision.waitImage.matchIndex.hint"] = MatchIndexHint,
        ["vision.waitImage.anchorMode.label"] = "坐标基准",
        ["vision.waitImage.anchorMode.hint"] = AnchorModeHint,
        ["vision.waitImage.anchorMode.option.screen"] = "屏幕像素",
        ["vision.waitImage.anchorMode.option.window"] = "窗口左上角",
        ["vision.waitImage.anchorMode.option.client"] = "窗口客户区",
        ["vision.waitImage.anchorWindow.label"] = "基准窗口",
        ["vision.waitImage.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.clickImage.region.label"] = "搜索区域",
        ["vision.clickImage.region.hint"] = RegionHintText,
        ["vision.clickImage.matchIndex.label"] = "第几个命中",
        ["vision.clickImage.matchIndex.hint"] = MatchIndexHint,
        ["vision.clickImage.anchorMode.label"] = "坐标基准",
        ["vision.clickImage.anchorMode.hint"] = AnchorModeHint,
        ["vision.clickImage.anchorMode.option.screen"] = "屏幕像素",
        ["vision.clickImage.anchorMode.option.window"] = "窗口左上角",
        ["vision.clickImage.anchorMode.option.client"] = "窗口客户区",
        ["vision.clickImage.anchorWindow.label"] = "基准窗口",
        ["vision.clickImage.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.findColor.name"] = "查找颜色",
        ["vision.findColor.desc"] = "在屏幕的一块区域里找某个颜色。",
        ["vision.findColor.color.label"] = "颜色",
        ["vision.findColor.color.hint"] = "要找的颜色。",
        ["vision.findColor.tolerance.label"] = "容差 %",
        ["vision.findColor.tolerance.hint"] = "允许的颜色偏差。",
        ["vision.findColor.matchIndex.label"] = "第几个命中",
        ["vision.findColor.matchIndex.hint"] = MatchIndexHint,
        ["vision.findColor.allMatches.label"] = "记录全部命中",
        ["vision.findColor.allMatches.hint"] = AllMatchesHint,
        ["vision.findColor.region.label"] = "搜索区域",
        ["vision.findColor.region.hint"] = RegionHintText,
        ["vision.findColor.timeoutMs.label"] = "超时毫秒",
        ["vision.findColor.timeoutMs.hint"] =
            "0 表示只找一次，找不到就把结果留空；填了数字就等它出现，一直不出现算失败。",
        ["vision.findColor.intervalMs.label"] = "间隔毫秒",
        ["vision.findColor.intervalMs.hint"] = "等待时两次查找之间的间隔。",
        ["vision.findColor.resultVariable.label"] = "结果变量",
        ["vision.findColor.resultVariable.hint"] =
            "接收找到的位置，没找到时为空；$变量名.x、.y、.score 是各个部分，"
            + "勾了“记录全部命中”后还有 .count 和 .list。",
        ["vision.findColor.anchorMode.label"] = "坐标基准",
        ["vision.findColor.anchorMode.hint"] = AnchorModeHint,
        ["vision.findColor.anchorMode.option.screen"] = "屏幕像素",
        ["vision.findColor.anchorMode.option.window"] = "窗口左上角",
        ["vision.findColor.anchorMode.option.client"] = "窗口客户区",
        ["vision.findColor.anchorWindow.label"] = "基准窗口",
        ["vision.findColor.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.colorsMatch.name"] = "多点比色",
        ["condition.colorsMatch.desc"] = "当若干个点都显示指定的颜色时为真。",
        ["condition.colorsMatch.points.label"] = "比色点",
        ["condition.colorsMatch.points.hint"] =
            "每个点写成 x,y,#RRGGBB，用分号或换行分开。",
        ["condition.colorsMatch.tolerance.label"] = "容差 %",
        ["condition.colorsMatch.tolerance.hint"] = "允许的颜色偏差。",
        ["condition.colorsMatch.mode.label"] = "满足方式",
        ["condition.colorsMatch.mode.hint"] = "每个点都要匹配，还是有一个匹配就算满足。",
        ["condition.colorsMatch.mode.option.all"] = "全部匹配",
        ["condition.colorsMatch.mode.option.any"] = "任意一个匹配",
        ["condition.colorsMatch.anchorMode.label"] = "坐标基准",
        ["condition.colorsMatch.anchorMode.hint"] = AnchorModeHint,
        ["condition.colorsMatch.anchorMode.option.screen"] = "屏幕像素",
        ["condition.colorsMatch.anchorMode.option.window"] = "窗口左上角",
        ["condition.colorsMatch.anchorMode.option.client"] = "窗口客户区",
        ["condition.colorsMatch.anchorWindow.label"] = "基准窗口",
        ["condition.colorsMatch.anchorWindow.hint"] = AnchorWindowHint,

        // ------------------------------------------------------------------- vision
        ["vision.capture.name"] = "截屏",
        ["vision.capture.desc"] = "把屏幕的一块区域截取到图像变量里。",
        ["vision.capture.x.label"] = "X",
        ["vision.capture.x.hint"] = "区域左上角横坐标。",
        ["vision.capture.y.label"] = "Y",
        ["vision.capture.y.hint"] = "区域左上角纵坐标。",
        ["vision.capture.width.label"] = "宽度",
        ["vision.capture.width.hint"] = "区域宽度（像素）。",
        ["vision.capture.height.label"] = "高度",
        ["vision.capture.height.hint"] = "区域高度（像素）。",
        ["vision.capture.saveTo.label"] = "保存到变量",
        ["vision.capture.saveTo.hint"] = "接收截图的变量。$变量名.x、.y、.width、.height 记录这次截图覆盖的矩形。",

        ["vision.captureWindow.name"] = "截取窗口",
        ["vision.captureWindow.desc"] = "把整个窗口连着标题栏一起截取到图像变量里。",
        ["vision.captureWindow.title.label"] = "窗口",
        ["vision.captureWindow.title.hint"] = WindowTitleHint,
        ["vision.captureWindow.matchBy.label"] = "匹配方式",
        ["vision.captureWindow.matchBy.hint"] = WindowMatchByHint,
        ["vision.captureWindow.matchBy.option.title"] = WindowMatchByTitle,
        ["vision.captureWindow.matchBy.option.process"] = WindowMatchByProcess,
        ["vision.captureWindow.matchBy.option.class"] = WindowMatchByClass,
        ["vision.captureWindow.saveTo.label"] = "保存到变量",
        ["vision.captureWindow.saveTo.hint"] = "接收截图的变量。$变量名.x、.y、.width、.height 记录窗口外框覆盖的矩形。",

        ["vision.findImage.name"] = "查找图片",
        ["vision.findImage.desc"] = "在屏幕上寻找一张参考图片。",
        ["vision.findImage.image.label"] = "图片文件",
        ["vision.findImage.image.hint"] = "参考图片：文件路径，或截图动作保存的变量（如 $shot）。",
        ["vision.findImage.confidence.label"] = "相似度 %",
        ["vision.findImage.confidence.hint"] = "要求的最低匹配度。",
        ["vision.findImage.region.label"] = "搜索区域",
        ["vision.findImage.region.hint"] = RegionHintText,
        ["vision.findImage.resultVariable.label"] = "结果变量",
        ["vision.findImage.resultVariable.hint"] = "接收匹配中心点，未找到时为空；$变量名.x、.y、.width、.height、.score 是各个部分。",

        ["vision.waitImage.name"] = "等待图片",
        ["vision.waitImage.desc"] = "等待参考图片在屏幕上出现。",
        ["vision.waitImage.image.label"] = "图片文件",
        ["vision.waitImage.image.hint"] = "要等待的参考图片：文件路径，或截图动作保存的变量。",
        ["vision.waitImage.confidence.label"] = "相似度 %",
        ["vision.waitImage.confidence.hint"] = "要求的最低匹配度。",
        ["vision.waitImage.timeoutMs.label"] = "超时毫秒",
        ["vision.waitImage.timeoutMs.hint"] = "超过这个时长就放弃。",
        ["vision.waitImage.intervalMs.label"] = "间隔毫秒",
        ["vision.waitImage.intervalMs.hint"] = "两次检测之间的间隔。",
        ["vision.waitImage.resultVariable.label"] = "结果变量",

        ["vision.clickImage.name"] = "点击图片",
        ["vision.clickImage.desc"] = "在屏幕上找到参考图片并点击它。",
        ["vision.clickImage.image.label"] = "图片文件",
        ["vision.clickImage.confidence.label"] = "相似度 %",
        ["vision.clickImage.confidence.hint"] = "要求的最低匹配度。",
        ["vision.clickImage.offsetX.label"] = "横向偏移",
        ["vision.clickImage.offsetX.hint"] = "在匹配中心基础上水平偏移的像素。",
        ["vision.clickImage.offsetY.label"] = "纵向偏移",
        ["vision.clickImage.timeoutMs.label"] = "超时毫秒",
        ["vision.clickImage.timeoutMs.hint"] = "等待图片出现的时长，超时即放弃。",
        ["vision.clickImage.button.label"] = "按键",

        ["vision.getPixel.name"] = "取色",
        ["vision.getPixel.desc"] = "读取某个像素的颜色。",
        ["vision.getPixel.x.label"] = "X",
        ["vision.getPixel.x.hint"] = "取样点的横坐标。",
        ["vision.getPixel.y.label"] = "Y",
        ["vision.getPixel.y.hint"] = "取样点的纵坐标。",
        ["vision.getPixel.resultVariable.label"] = "结果变量",
        ["vision.getPixel.resultVariable.hint"] = "接收颜色的变量，可沿用已有变量名或新建一个。",
        ["vision.getPixel.asHex.label"] = "存为十六进制",
        ["vision.getPixel.asHex.hint"] = "存成 #RRGGBB，而不是原始通道值。",

        ["vision.waitColor.name"] = "等待颜色",
        ["vision.waitColor.desc"] = "等待某个像素变成指定颜色。",
        ["vision.waitColor.x.label"] = "X",
        ["vision.waitColor.x.hint"] = "监视点的横坐标。",
        ["vision.waitColor.y.label"] = "Y",
        ["vision.waitColor.y.hint"] = "监视点的纵坐标。",
        ["vision.waitColor.color.label"] = "颜色",
        ["vision.waitColor.color.hint"] = "像素需要显示的颜色。",
        ["vision.waitColor.tolerance.label"] = "容差 %",
        ["vision.waitColor.tolerance.hint"] = "允许的颜色偏差。",
        ["vision.waitColor.timeoutMs.label"] = "超时毫秒",
        ["vision.waitColor.timeoutMs.hint"] = "超过这个时长就放弃。",

        // ---------------------------------------------------------------------- ocr
        ["ocr.recognize.name"] = "识别文字",
        ["ocr.recognize.desc"] = "识别屏幕某块区域里的文字。",
        ["ocr.recognize.x.label"] = "X",
        ["ocr.recognize.x.hint"] = "区域左上角横坐标。",
        ["ocr.recognize.y.label"] = "Y",
        ["ocr.recognize.y.hint"] = "区域左上角纵坐标。",
        ["ocr.recognize.width.label"] = "宽度",
        ["ocr.recognize.width.hint"] = "区域宽度（像素）。",
        ["ocr.recognize.height.label"] = "高度",
        ["ocr.recognize.height.hint"] = "区域高度（像素）。",
        ["ocr.recognize.language.label"] = "语言",
        ["ocr.recognize.resultVariable.label"] = "结果变量",
        ["ocr.recognize.resultVariable.hint"] = "接收识别结果的变量，可沿用已有变量名或新建一个。",

        ["ocr.findText.name"] = "查找文字",
        ["ocr.findText.desc"] = "在屏幕上搜索指定文字。",
        ["ocr.findText.text.label"] = "要查找的文字",
        ["ocr.findText.text.hint"] = "要搜索的文字。",
        ["ocr.findText.region.label"] = "搜索区域",
        ["ocr.findText.region.hint"] = RegionHintText,
        ["ocr.findText.matchMode.label"] = "匹配方式",
        ["ocr.findText.matchMode.hint"] = "识别结果与搜索文字的比较方式。",
        ["ocr.findText.resultVariable.label"] = "结果变量",
        ["ocr.findText.resultVariable.hint"] = "接收匹配中心点，未找到时为空；$变量名.x、.y、.text、.score 是各个部分。",
        ["ocr.findText.allMatches.label"] = "记录全部命中",
        ["ocr.findText.allMatches.hint"] = "除了挑中的那一处，还把匹配到几处、分别在哪里记下来："
            + "$变量名.count 是处数，$变量名.list 每处一个“x,y”，可以直接交给 count()、get() 和 forEach。",

        ["ocr.clickText.name"] = "点击文字",
        ["ocr.clickText.desc"] = "在屏幕上找到文字并点击它。",
        ["ocr.clickText.text.label"] = "要查找的文字",
        ["ocr.clickText.matchMode.label"] = "匹配方式",
        ["ocr.clickText.matchMode.hint"] = "识别结果与搜索文字的比较方式。",
        ["ocr.clickText.offsetX.label"] = "横向偏移",
        ["ocr.clickText.offsetX.hint"] = "在匹配中心基础上水平偏移的像素。",
        ["ocr.clickText.offsetY.label"] = "纵向偏移",
        ["ocr.clickText.timeoutMs.label"] = "超时毫秒",
        ["ocr.clickText.timeoutMs.hint"] = "等待文字出现的时长，超时即放弃。",
        ["ocr.clickText.button.label"] = "按键",

        // ---------------------------------------------------------------------- uia
        ["uia.exists.name"] = "元素是否存在",
        ["uia.exists.desc"] = "判断某个 UI Automation 元素是否存在。",
        ["uia.exists.window.label"] = "窗口",
        ["uia.exists.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.exists.selector.label"] = "选择器",
        ["uia.exists.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.exists.matchIndex.label"] = "第几个命中",
        ["uia.exists.matchIndex.hint"] = "选择器可能匹配到多个元素，这里填要的是第几个。" + MatchIndexHint,
        ["uia.exists.timeoutMs.label"] = "超时毫秒",
        ["uia.exists.timeoutMs.hint"] = "0 表示只检查一次并立即返回。",
        ["uia.exists.resultVariable.label"] = "结果变量",
        ["uia.exists.resultVariable.hint"] = "接收 true / false 的变量。",

        ["uia.find.name"] = "查找元素",
        ["uia.find.desc"] = "查找一个 UI Automation 元素，并记住它在屏幕上的位置。",
        ["uia.find.window.label"] = "窗口",
        ["uia.find.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.find.selector.label"] = "选择器",
        ["uia.find.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.find.matchIndex.label"] = "第几个命中",
        ["uia.find.matchIndex.hint"] = MatchIndexHint,
        ["uia.find.allMatches.label"] = "记录全部命中",
        ["uia.find.allMatches.hint"] = AllMatchesHint,
        ["uia.find.resultVariable.label"] = "结果变量",
        ["uia.find.resultVariable.hint"] =
            "用来接收元素中心位置的变量，没找到时置空。$变量.x、$变量.y、$变量.width、$变量.height "
            + "和 $变量.text 分别是各个部分，后面的步骤可以拿它们当参照物；"
            + "勾了“记录全部命中”时，$变量.count 和 $变量.list 是全部命中。",

        ["uia.waitElement.name"] = "等待元素",
        ["uia.waitElement.desc"] = "等待某个 UI Automation 元素出现。",
        ["uia.waitElement.window.label"] = "窗口",
        ["uia.waitElement.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.waitElement.selector.label"] = "选择器",
        ["uia.waitElement.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.waitElement.matchIndex.label"] = "第几个命中",
        ["uia.waitElement.matchIndex.hint"] =
            "选择器可能匹配到多个元素，这里填要等的是第几个。" + MatchIndexHint,
        ["uia.waitElement.timeoutMs.label"] = "超时毫秒",
        ["uia.waitElement.timeoutMs.hint"] = "超过这个时长就放弃。",
        ["uia.waitElement.pollMs.label"] = "轮询毫秒",
        ["uia.waitElement.pollMs.hint"] = "两次检查之间的间隔。",

        ["uia.click.name"] = "点击元素",
        ["uia.click.desc"] = "点击一个 UI Automation 元素。",
        ["uia.click.window.label"] = "窗口",
        ["uia.click.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.click.selector.label"] = "选择器",
        ["uia.click.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.click.matchIndex.label"] = "第几个命中",
        ["uia.click.matchIndex.hint"] = "选择器可能匹配到多个元素，这里填要点击的是第几个。" + MatchIndexHint,
        ["uia.click.timeoutMs.label"] = "超时毫秒",
        ["uia.click.timeoutMs.hint"] = "点击前等待元素出现的时长。",
        ["uia.click.button.label"] = "按键",

        ["uia.setText.name"] = "设置元素文本",
        ["uia.setText.desc"] = "向 UI Automation 元素输入文本。",
        ["uia.setText.window.label"] = "窗口",
        ["uia.setText.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.setText.selector.label"] = "选择器",
        ["uia.setText.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.setText.matchIndex.label"] = "第几个命中",
        ["uia.setText.matchIndex.hint"] = "选择器可能匹配到多个元素，这里填要写入的是第几个。" + MatchIndexHint,
        ["uia.setText.text.label"] = "文本",
        ["uia.setText.text.hint"] = "写入元素的文本。",
        ["uia.setText.clearFirst.label"] = "先清空",
        ["uia.setText.clearFirst.hint"] = "输入前先清空输入框内容。",

        ["uia.getText.name"] = "读取元素文本",
        ["uia.getText.desc"] = "读取 UI Automation 元素的文本。",
        ["uia.getText.window.label"] = "窗口",
        ["uia.getText.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.getText.selector.label"] = "选择器",
        ["uia.getText.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.getText.matchIndex.label"] = "第几个命中",
        ["uia.getText.matchIndex.hint"] = "选择器可能匹配到多个元素，这里填要读取的是第几个。" + MatchIndexHint,
        ["uia.getText.resultVariable.label"] = "结果变量",
        ["uia.getText.resultVariable.hint"] = "接收文本的变量。",

        ["uia.select.name"] = "选择列表项",
        ["uia.select.desc"] = "在下拉框、列表或选项卡里选中一项。",
        ["uia.select.window.label"] = "窗口",
        ["uia.select.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.select.selector.label"] = "选择器",
        ["uia.select.selector.hint"] = "下拉框、列表或选项卡的选择器。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.select.matchIndex.label"] = "第几个命中",
        ["uia.select.matchIndex.hint"] = "选择器可能匹配到多个控件，这里填要操作的是第几个。" + MatchIndexHint,
        ["uia.select.item.label"] = "选项文字",
        ["uia.select.item.hint"] = "要选中的那一项显示的文字，也可以由 $变量 提供（比如刚从别处读回来的值）。留空就填下面的序号。",
        ["uia.select.itemIndex.label"] = "选项序号",
        ["uia.select.itemIndex.hint"] = "要选第几项，从 1 开始数；填 0 表示用上面写的文字来选。",

        ["uia.check.name"] = "勾选框",
        ["uia.check.desc"] = "把勾选框、开关或单选框打开或关掉。",
        ["uia.check.window.label"] = "窗口",
        ["uia.check.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.check.selector.label"] = "选择器",
        ["uia.check.selector.hint"] = "勾选框、开关或单选框的选择器。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.check.matchIndex.label"] = "第几个命中",
        ["uia.check.matchIndex.hint"] = "选择器可能匹配到多个控件，这里填要操作的是第几个。" + MatchIndexHint,
        ["uia.check.state.label"] = "状态",
        ["uia.check.state.hint"] = "要把它怎么样。“反过来”是不管现在是什么状态都切成另一种，宏不知道开始时是什么状态时用这个。",
        ["uia.check.state.option.on"] = "打开",
        ["uia.check.state.option.off"] = "关闭",
        ["uia.check.state.option.toggle"] = "反过来",

        ["uia.expand.name"] = "展开/收起",
        ["uia.expand.desc"] = "展开或收起树节点、菜单、折叠面板。",
        ["uia.expand.window.label"] = "窗口",
        ["uia.expand.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.expand.selector.label"] = "选择器",
        ["uia.expand.selector.hint"] = "要展开或收起的节点选择器。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.expand.matchIndex.label"] = "第几个命中",
        ["uia.expand.matchIndex.hint"] = "选择器可能匹配到多个控件，这里填要操作的是第几个。" + MatchIndexHint,
        ["uia.expand.state.label"] = "状态",
        ["uia.expand.state.hint"] = "要展开、收起，还是不管现在是哪种都切成另一种。",
        ["uia.expand.state.option.expand"] = "展开",
        ["uia.expand.state.option.collapse"] = "收起",
        ["uia.expand.state.option.toggle"] = "反过来",

        ["uia.scrollIntoView.name"] = "滚动到可见",
        ["uia.scrollIntoView.desc"] = "把列表或面板里的某个元素滚动到看得见的位置。",
        ["uia.scrollIntoView.window.label"] = "窗口",
        ["uia.scrollIntoView.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.scrollIntoView.selector.label"] = "选择器",
        ["uia.scrollIntoView.selector.hint"] = "要滚动到可见的元素选择器。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.scrollIntoView.matchIndex.label"] = "第几个命中",
        ["uia.scrollIntoView.matchIndex.hint"] = "选择器可能匹配到多个控件，这里填要操作的是第几个。" + MatchIndexHint,

        ["uia.readTable.name"] = "读取表格",
        ["uia.readTable.desc"] = "把表格或网格读成一个按行存放的列表。",
        ["uia.readTable.window.label"] = "窗口",
        ["uia.readTable.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.readTable.selector.label"] = "选择器",
        ["uia.readTable.selector.hint"] = "表格或网格的选择器。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.readTable.matchIndex.label"] = "第几个命中",
        ["uia.readTable.matchIndex.hint"] = "选择器可能匹配到多个控件，这里填要读取的是第几个。" + MatchIndexHint,
        ["uia.readTable.maxRows.label"] = "读取行数",
        ["uia.readTable.maxRows.hint"] =
            "最多读取前多少行数据。整行都是空的会被跳过——放列标题的那一行、有些表格底部留着"
            + "用来输入新记录的空白行，都不是数据。",
        ["uia.readTable.resultVariable.label"] = "结果变量",
        ["uia.readTable.resultVariable.hint"] =
            "用来接收表格内容的变量：$变量 是一个“每行一项”的列表，每一项又是一行单元格的列表，"
            + "和读取 CSV 返回的形状一样。",

        ["uia.focusWindow.name"] = "窗口置前",
        ["uia.focusWindow.desc"] = "把某个窗口切换到最前面。",
        ["uia.focusWindow.window.label"] = "窗口",
        ["uia.focusWindow.window.hint"] = "窗口标题，或保存标题的 $变量。可以用“拾取窗口”从当前打开的窗口里选一个。",

        // ------------------------------------------------------------------ script
        ["script.run.name"] = "运行脚本",
        ["script.run.desc"] = "用选定的解释器运行一小段脚本，兜住动作目录里没有的情况。",
        ["script.run.language.label"] = "解释器",
        ["script.run.language.hint"] = "用哪个解释器运行这段脚本。PowerShell 和命令提示符每台 Windows 上都有；Node.js 和 Python 需要先自己装好；自选解释器用来写机器上装的其他程序，比如 dotnet-script。",
        ["script.run.language.option.powershell"] = "PowerShell",
        ["script.run.language.option.cmd"] = "命令提示符",
        ["script.run.language.option.node"] = "Node.js",
        ["script.run.language.option.python"] = "Python",
        ["script.run.language.option.custom"] = "自选解释器",
        ["script.run.interpreter.label"] = "解释器命令行",
        ["script.run.interpreter.hint"] = "运行这段脚本的程序，它自己的开关写在前面，配合上面的\"自选解释器\"使用。脚本的路径会接在它后面，和你手打命令行时一样。路径里有空格时用引号括起来。",
        ["script.run.extension.label"] = "脚本后缀",
        ["script.run.extension.hint"] = "那个程序认识的脚本后缀，例如 dotnet-script 用 .csx、cscript 用 .vbs。只在\"自选解释器\"时用得上。",
        ["script.run.encoding.label"] = "脚本文件编码",
        ["script.run.encoding.hint"] = "交给解释器的那份脚本按什么编码写。默认交给解释器自己决定：PowerShell 带 BOM，其余不带，各自都能正确读出中文；像 cscript 这种按系统代码页读文件的程序，要选 GBK。",
        ["script.run.encoding.option.auto"] = "按解释器习惯",
        ["script.run.encoding.option.utf8"] = "UTF-8",
        ["script.run.encoding.option.utf8bom"] = "UTF-8 带 BOM",
        ["script.run.encoding.option.gbk"] = "GBK（中文）",
        ["script.run.encoding.option.utf16"] = "UTF-16",
        ["script.run.script.label"] = "脚本",
        ["script.run.script.hint"] = "脚本本身。写 {{变量名}} 的地方会在运行前换成那个变量的值，这就是宏的值传进脚本的方式；脚本打印出来的内容会回到下面的结果变量里。",
        ["script.run.arguments.label"] = "参数",
        ["script.run.arguments.hint"] = "附加在脚本命令行后面的参数。这里也会替换 {{变量名}}。",
        ["script.run.folder.label"] = "工作目录",
        ["script.run.folder.hint"] = "脚本在哪个目录里运行。留空表示在宏所在目录；那个目录还不存在时，就在维克多自己的工作目录。",
        ["script.run.timeoutMs.label"] = "超时毫秒",
        ["script.run.timeoutMs.hint"] = "超过这个时长就结束脚本并让这一步失败。",
        ["script.run.resultVariable.label"] = "结果变量",
        ["script.run.resultVariable.hint"] = "用来接收脚本打印内容的变量，首尾的空行会去掉。",

        // ---------------------------------------------------------------- condition
        ["condition.imageExists.name"] = "图片存在",
        ["condition.imageExists.desc"] = "当参考图片出现在屏幕上时为真。",
        ["condition.imageExists.image.label"] = "图片文件",
        ["condition.imageExists.confidence.label"] = "相似度 %",
        ["condition.imageExists.confidence.hint"] = "要求的最低匹配度。",
        ["condition.imageExists.region.label"] = "搜索区域",
        ["condition.imageExists.region.hint"] = RegionHintText,

        ["condition.textExists.name"] = "文字存在",
        ["condition.textExists.desc"] = "当屏幕上出现指定文字时为真。",
        ["condition.textExists.text.label"] = "文字",
        ["condition.textExists.region.label"] = "搜索区域",
        ["condition.textExists.region.hint"] = RegionHintText,
        ["condition.textExists.matchMode.label"] = "匹配方式",
        ["condition.textExists.matchMode.hint"] = "识别结果与搜索文字的比较方式。",

        ["condition.uiaExists.name"] = "UI 元素存在",
        ["condition.uiaExists.desc"] = "当 UI Automation 元素存在时为真。",
        ["condition.uiaExists.window.label"] = "窗口",
        ["condition.uiaExists.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["condition.uiaExists.selector.label"] = "选择器",
        ["condition.uiaExists.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",

        ["condition.colorEquals.name"] = "颜色相同",
        ["condition.colorEquals.desc"] = "当某个像素的颜色匹配时为真。",
        ["condition.colorEquals.x.label"] = "X",
        ["condition.colorEquals.x.hint"] = "比较点的横坐标。",
        ["condition.colorEquals.y.label"] = "Y",
        ["condition.colorEquals.y.hint"] = "比较点的纵坐标。",
        ["condition.colorEquals.color.label"] = "颜色",
        ["condition.colorEquals.tolerance.label"] = "容差 %",
        ["condition.colorEquals.tolerance.hint"] = "允许的颜色偏差。",

        // ------------------------------------------ 否定条件与布尔表达式（条件也能自己写公式）
        ["condition.imageNotExists.name"] = "图片不存在",
        ["condition.imageNotExists.desc"] = "当参考图片不在屏幕上时为真。",
        ["condition.imageNotExists.image.label"] = "图片文件",
        ["condition.imageNotExists.confidence.label"] = "相似度 %",
        ["condition.imageNotExists.confidence.hint"] = "要求的最低匹配度。",
        ["condition.imageNotExists.region.label"] = "搜索区域",
        ["condition.imageNotExists.region.hint"] = RegionHintText,
        ["condition.imageNotExists.anchorMode.label"] = "坐标基准",
        ["condition.imageNotExists.anchorMode.hint"] = AnchorModeHint,
        ["condition.imageNotExists.anchorMode.option.screen"] = "屏幕像素",
        ["condition.imageNotExists.anchorMode.option.window"] = "窗口左上角",
        ["condition.imageNotExists.anchorMode.option.client"] = "窗口客户区",
        ["condition.imageNotExists.anchorWindow.label"] = "基准窗口",
        ["condition.imageNotExists.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.textNotExists.name"] = "文字不存在",
        ["condition.textNotExists.desc"] = "当屏幕上没有指定文字时为真。",
        ["condition.textNotExists.text.label"] = "文字",
        ["condition.textNotExists.region.label"] = "搜索区域",
        ["condition.textNotExists.region.hint"] = RegionHintText,
        ["condition.textNotExists.matchMode.label"] = "匹配方式",
        ["condition.textNotExists.matchMode.hint"] = "识别结果与搜索文字的比较方式。",
        ["condition.textNotExists.matchMode.option.contains"] = "包含",
        ["condition.textNotExists.matchMode.option.exact"] = "完全匹配",
        ["condition.textNotExists.matchMode.option.regex"] = "正则匹配",
        ["condition.textNotExists.anchorMode.label"] = "坐标基准",
        ["condition.textNotExists.anchorMode.hint"] = AnchorModeHint,
        ["condition.textNotExists.anchorMode.option.screen"] = "屏幕像素",
        ["condition.textNotExists.anchorMode.option.window"] = "窗口左上角",
        ["condition.textNotExists.anchorMode.option.client"] = "窗口客户区",
        ["condition.textNotExists.anchorWindow.label"] = "基准窗口",
        ["condition.textNotExists.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.uiaNotExists.name"] = "UI 元素不存在",
        ["condition.uiaNotExists.desc"] = "当某个 UI Automation 元素不存在时为真。",
        ["condition.uiaNotExists.window.label"] = "窗口",
        ["condition.uiaNotExists.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["condition.uiaNotExists.selector.label"] = "选择器",
        ["condition.uiaNotExists.selector.hint"] =
            "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",

        ["condition.expression.name"] = "布尔表达式",
        ["condition.expression.desc"] = "自己写一段表达式，结果为真时条件成立。",
        ["condition.expression.expression.label"] = "表达式",
        ["condition.expression.expression.hint"] =
            "用 $变量、运算符和内置函数拼出一个真 / 假结果，例如 $count > 3 and contains($name, \"ok\")。"
            + "每次判断都会重新求值，所以在等待里它跟着变量一起变。",

        ["condition.compare.name"] = "条件判断",
        ["condition.compare.desc"] = "把一个变量与另一个值或变量进行比较。",
        ["condition.compare.variable.label"] = "变量",
        ["condition.compare.variable.hint"] = "要判断的变量；候选项来自前面步骤创建过的变量。",
        ["condition.compare.operator.label"] = "判断方式",
        ["condition.compare.operator.hint"] = "变量与比较值之间的关系。",
        ["condition.compare.value.label"] = "变量或值",
        ["condition.compare.value.hint"] = "可从下拉中选择已有变量，也可以直接输入数字或文本；判断“变量存在”时可留空。",
        ["condition.compare.operator.option.equals"] = "等于",
        ["condition.compare.operator.option.notEquals"] = "不等于",
        ["condition.compare.operator.option.greaterThan"] = "大于",
        ["condition.compare.operator.option.greaterOrEqual"] = "大于等于",
        ["condition.compare.operator.option.lessThan"] = "小于",
        ["condition.compare.operator.option.lessOrEqual"] = "小于等于",
        ["condition.compare.operator.option.contains"] = "包含",
        ["condition.compare.operator.option.notContains"] = "不包含",
        ["condition.compare.operator.option.exists"] = "变量存在",
        ["condition.compare.operator.option.regexMatch"] = "正则匹配",

        ["condition.group.name"] = "条件组",
        ["condition.group.desc"] = "用“与 / 或 / 非”把多个条件组合在一起：与＝全部满足，或＝任一满足，非＝全部不满足。",
        ["condition.group.op.label"] = "逻辑",
        ["condition.group.op.hint"] = "子条件的组合方式；有两个以上条件时才会生效。",
        ["condition.group.op.option.and"] = "与（全部满足）",
        ["condition.group.op.option.or"] = "或（任一满足）",
        ["condition.group.op.option.none"] = "非（全部不满足）",
        ["condition.group.conditions.label"] = "子条件",
        ["condition.group.conditions.hint"] = "加两个以上条件后，可用上面的逻辑组合它们；条件组可以继续嵌套。",

        ["condition.randomChance.name"] = "随机概率",
        ["condition.randomChance.desc"] = "按固定概率随机为真。",
        ["condition.randomChance.percent.label"] = "概率 %",
        ["condition.randomChance.percent.hint"] = "条件为真的概率。",

        // ------------------------------------------------- 下拉选项（每个动作各一份键）
        // 鼠标按键在八个动作里出现，措辞必须一致，否则同一个下拉框换个动作就变样。
        ["input.mouseClick.button.option.left"] = "左键",
        ["input.mouseClick.button.option.right"] = "右键",
        ["input.mouseClick.button.option.middle"] = "中键",
        ["input.mouseClick.button.option.back"] = "后退键",
        ["input.mouseClick.button.option.forward"] = "前进键",
        ["input.mouseDoubleClick.button.option.left"] = "左键",
        ["input.mouseDoubleClick.button.option.right"] = "右键",
        ["input.mouseDoubleClick.button.option.middle"] = "中键",
        ["input.mouseDoubleClick.button.option.back"] = "后退键",
        ["input.mouseDoubleClick.button.option.forward"] = "前进键",
        ["input.mouseDown.button.option.left"] = "左键",
        ["input.mouseDown.button.option.right"] = "右键",
        ["input.mouseDown.button.option.middle"] = "中键",
        ["input.mouseDown.button.option.back"] = "后退键",
        ["input.mouseDown.button.option.forward"] = "前进键",
        ["input.mouseUp.button.option.left"] = "左键",
        ["input.mouseUp.button.option.right"] = "右键",
        ["input.mouseUp.button.option.middle"] = "中键",
        ["input.mouseUp.button.option.back"] = "后退键",
        ["input.mouseUp.button.option.forward"] = "前进键",
        ["input.mouseDrag.button.option.left"] = "左键",
        ["input.mouseDrag.button.option.right"] = "右键",
        ["input.mouseDrag.button.option.middle"] = "中键",
        ["input.mouseDrag.button.option.back"] = "后退键",
        ["input.mouseDrag.button.option.forward"] = "前进键",
        ["vision.clickImage.button.option.left"] = "左键",
        ["vision.clickImage.button.option.right"] = "右键",
        ["vision.clickImage.button.option.middle"] = "中键",
        ["vision.clickImage.button.option.back"] = "后退键",
        ["vision.clickImage.button.option.forward"] = "前进键",
        ["ocr.clickText.button.option.left"] = "左键",
        ["ocr.clickText.button.option.right"] = "右键",
        ["ocr.clickText.button.option.middle"] = "中键",
        ["ocr.clickText.button.option.back"] = "后退键",
        ["ocr.clickText.button.option.forward"] = "前进键",
        ["uia.click.button.option.left"] = "左键",
        ["uia.click.button.option.right"] = "右键",
        ["uia.click.button.option.middle"] = "中键",
        ["uia.click.button.option.back"] = "后退键",
        ["uia.click.button.option.forward"] = "前进键",

        ["input.mouseScroll.direction.option.up"] = "向上",
        ["input.mouseScroll.direction.option.down"] = "向下",
        ["input.mouseScroll.direction.option.left"] = "向左",
        ["input.mouseScroll.direction.option.right"] = "向右",

        ["ocr.recognize.language.option.auto"] = "自动",
        ["ocr.recognize.language.option.en"] = "英文",
        ["ocr.recognize.language.option.zh"] = "中文",

        ["ocr.findText.matchMode.option.contains"] = "包含",
        ["ocr.findText.matchMode.option.exact"] = "完全匹配",
        ["ocr.findText.matchMode.option.regex"] = "正则匹配",
        ["ocr.clickText.matchMode.option.contains"] = "包含",
        ["ocr.clickText.matchMode.option.exact"] = "完全匹配",
        ["ocr.clickText.matchMode.option.regex"] = "正则匹配",
        ["condition.textExists.matchMode.option.contains"] = "包含",
        ["condition.textExists.matchMode.option.exact"] = "完全匹配",
        ["condition.textExists.matchMode.option.regex"] = "正则匹配",

        ["control.log.level.option.info"] = "信息",
        ["control.log.level.option.warn"] = "警告",
        ["control.log.level.option.error"] = "错误",
        ["control.log.level.option.debug"] = "调试",
    };
}
