using System.Collections.Generic;

namespace Viktor.Localization;

/// <summary>
/// Chinese text for the action catalogue. Keys are
/// <c>{actionKey}.name</c>, <c>{actionKey}.desc</c> and
/// <c>{actionKey}.{parameter}.label</c> / <c>.hint</c>; anything missing falls
/// back to the English text stored in the catalogue itself.
/// </summary>
internal static class ActionStrings
{
    /// <summary>
    /// The hint the thirteen input actions share for their input-mode picker. They were written
    /// once rather than thirteen times, so a change to how input is described stays in one place.
    /// </summary>
    private const string InputModeHint =
        "这一步的输入怎么送出去。前台发给当前有焦点的窗口；后台把消息投给下面的目标窗口，"
        + "不用抢焦点，屏幕上的鼠标也不会真的移动；驱动级通过虚拟 USB 设备发送，"
        + "需要先启动 VIIPER 服务端。";

    /// <summary>The matching hint for the window background input posts its messages at.</summary>
    private const string TargetWindowHint =
        "后台输入把消息投给哪个窗口，填标题的一部分即可。其他输入方式用不到。";

    /// <summary>
    /// The hint every action that takes a position or a rectangle shares for its coordinate-origin
    /// picker, written once for the same reason the input-mode hint is.
    /// </summary>
    private const string AnchorModeHint =
        "这一步的坐标从哪里量起。屏幕＝桌面上的像素位置，也是以前所有宏的写法；"
        + "窗口左上角＝从目标窗口外框的左上角算起；窗口客户区＝从窗口边框里面算起。"
        + "后两种会让这一步跟着窗口走，窗口移动或缩放之后仍然落在窗口里的同一个位置。";

    /// <summary>The matching hint for the window those coordinates are measured from.</summary>
    private const string AnchorWindowHint =
        "坐标从哪个窗口量起，填标题的一部分即可。留空表示运行时最前面那个窗口；"
        + "选“屏幕像素”时用不到它。";

    /// <summary>The hint every search-region field shares, in the wording the English one uses.</summary>
    private const string RegionHintText =
        "可选，格式 x,y,width,height，也可写成 $变量；一次要看几块区域就用分号隔开，每块都会搜；"
        + "留空表示全屏搜索。";

    /// <summary>The hint the "which hit" fields share.</summary>
    private const string MatchIndexHint = "从左到右、从上往下数第几个命中，1 是第一个。";

    /// <summary>The hint the "record every match" switches share.</summary>
    private const string AllMatchesHint =
        "勾上以后把命中的数量和位置都记下来：$变量名.count 是数量，$变量名.list 是每次命中的 “x,y”，"
        + "可以配合 count()、get()、forEach 使用。";

    internal static readonly Dictionary<string, string> Chinese = new()
    {
        // ------------------------------------------------------------------ control
        ["control.waitUntil.name"] = "等待直到",
        ["control.waitUntil.desc"] = "反复判断一个条件，成立之后再继续往下走。",
        ["control.waitUntil.condition.label"] = "条件",
        ["control.waitUntil.condition.hint"] = "会一遍遍判断这个条件，直到它成立。颜色、图片、文字、界面元素、变量比较都可以用来等。",
        ["control.waitUntil.timeoutMs.label"] = "超时毫秒",
        ["control.waitUntil.timeoutMs.hint"] = "超过这个时长就放弃。",
        ["control.waitUntil.pollMs.label"] = "检查间隔毫秒",
        ["control.waitUntil.pollMs.hint"] = "两次判断之间等待多久。",
        ["control.waitUntil.onTimeout.label"] = "一直不成立时",
        ["control.waitUntil.onTimeout.hint"] = "时间到了以后这个宏怎么做。",
        ["control.waitUntil.onTimeout.option.stop"] = "停止整个宏",
        ["control.waitUntil.onTimeout.option.continue"] = "忽略并继续下一步",
        ["control.waitUntil.elapsedVariable.label"] = "等待时长毫秒",
        ["control.waitUntil.elapsedVariable.hint"] = "用来接收这次等待实际花了多少毫秒；等到和超时都会写入。",

        ["control.sequence.name"] = "顺序执行",
        ["control.sequence.desc"] = "按顺序依次执行子步骤。",
        ["control.sequence.name.label"] = "名称",
        ["control.sequence.name.hint"] = "可选，列表里显示的名称。",
        ["control.sequence.steps.label"] = "子步骤",
        ["control.sequence.steps.hint"] = "按顺序执行的子步骤。",

        ["control.delay.name"] = "延迟",
        ["control.delay.desc"] = "执行下一步之前等待固定时长。",
        ["control.delay.ms.label"] = "毫秒",
        ["control.delay.ms.hint"] = "等待时长，单位毫秒。",

        ["control.delayRandom.name"] = "随机延迟",
        ["control.delayRandom.desc"] = "等待一个随机时长，让宏看起来不像机械执行。",
        ["control.delayRandom.minMs.label"] = "最短毫秒",
        ["control.delayRandom.minMs.hint"] = "最短等待时长，单位毫秒。",
        ["control.delayRandom.maxMs.label"] = "最长毫秒",
        ["control.delayRandom.maxMs.hint"] = "最长等待时长，单位毫秒。",

        ["control.repeat.name"] = "重复",
        ["control.repeat.desc"] = "把子步骤重复执行固定次数。",
        ["control.repeat.times.label"] = "次数",
        ["control.repeat.times.hint"] = "重复执行的次数。",
        ["control.repeat.intervalMs.label"] = "间隔毫秒",
        ["control.repeat.intervalMs.hint"] = "每轮之间的等待时间。",
        ["control.repeat.body.label"] = "循环体步骤",
        ["control.repeat.body.hint"] = "每轮执行一次的子步骤。",

        ["control.while.name"] = "当…时循环",
        ["control.while.desc"] = "条件成立期间，反复执行子步骤。",
        ["control.while.condition.label"] = "条件",
        ["control.while.condition.hint"] = "每轮开始前判断一次。",
        ["control.while.maxIterations.label"] = "最大轮数",
        ["control.while.maxIterations.hint"] = "安全上限，避免死循环停不下来。",
        ["control.while.body.label"] = "循环体步骤",
        ["control.while.body.hint"] = "条件成立时执行的子步骤。",

        ["control.forEach.name"] = "遍历",
        ["control.forEach.desc"] = "对列表或变量中的每一项执行一次子步骤。",
        ["control.forEach.items.label"] = "列表项",
        ["control.forEach.items.hint"] = "一个列表，或保存列表的 $变量。例如 [1, 2, 3]、split($text, \",\") 或 $names。",
        ["control.forEach.itemVariable.label"] = "当前项变量",
        ["control.forEach.itemVariable.hint"] = "用于接收当前项的变量名。",
        ["control.forEach.reverse.label"] = "倒序遍历",
        ["control.forEach.reverse.hint"] = "从最后一项往前遍历。",
        ["control.forEach.body.label"] = "循环体步骤",
        ["control.forEach.body.hint"] = "每一项执行一次的子步骤。",

        ["control.if.name"] = "条件分支",
        ["control.if.desc"] = "根据条件在两个子步骤块中选择一个执行。",
        ["control.if.condition.label"] = "条件",
        ["control.if.condition.hint"] = "执行到这一步时判断一次。",
        ["control.if.then.label"] = "满足时步骤",
        ["control.if.then.hint"] = "条件成立时执行的子步骤。",
        ["control.if.else.label"] = "不满足时步骤",
        ["control.if.else.hint"] = "条件不成立时执行的子步骤。",

        ["control.try.name"] = "尝试 / 捕获 / 收尾",
        ["control.try.desc"] = "先执行尝试的步骤，失败时改走捕获的步骤，最后无论如何都执行收尾的步骤。",
        ["control.try.body.label"] = "尝试步骤",
        ["control.try.body.hint"] = "先尝试执行的子步骤。",
        ["control.try.catch.label"] = "捕获步骤",
        ["control.try.catch.hint"] = "尝试失败时执行的子步骤。",
        ["control.try.finally.label"] = "收尾步骤",
        ["control.try.finally.hint"] = "无论成功、失败还是被跳过都会执行的子步骤。",
        ["control.try.errorVariable.label"] = "失败原因变量",
        ["control.try.errorVariable.hint"] = "用来接收失败原因；没有失败时会被清空。",

        ["control.break.name"] = "跳出循环",
        ["control.break.desc"] = "立即跳出最内层循环。",

        ["control.continue.name"] = "继续下一轮",
        ["control.continue.desc"] = "跳过本轮剩余步骤，直接开始下一轮。",

        ["control.stop.name"] = "停止宏",
        ["control.stop.desc"] = "停止正在运行的宏。",
        ["control.stop.reason.label"] = "原因",
        ["control.stop.reason.hint"] = "可选，会写入日志。",

        ["control.setVariable.name"] = "设置变量",
        ["control.setVariable.desc"] = "保存一个值，供后面的步骤使用。",
        ["control.setVariable.name.label"] = "变量名",
        ["control.setVariable.name.hint"] = "局部变量在这里命名即可；全局变量必须先在变量中心创建。",
        ["control.setVariable.value.label"] = "值",
        ["control.setVariable.value.hint"] = "数字、文本、$变量，或公式，例如 $count + 1、upper($name)。",
        ["control.setVariable.scope.label"] = "作用范围",
        ["control.setVariable.scope.hint"] = "局部变量只属于本宏，全局变量由所有宏共享。",
        ["control.setVariable.scope.option.local"] = "局部变量（仅本宏）",
        ["control.setVariable.scope.option.global"] = "全局变量（所有宏共享）",

        ["control.listCreate.name"] = "创建列表",
        ["control.listCreate.desc"] = "建立一个列表变量，覆盖它原来的内容。",
        ["control.listCreate.name.label"] = "变量名",
        ["control.listCreate.name.hint"] = "局部列表只属于本宏，全局列表由所有宏共享。列表里可以放任意类型的值。",
        ["control.listCreate.scope.label"] = "作用范围",
        ["control.listCreate.scope.hint"] = "局部列表只属于本宏，全局列表由所有宏共享。",
        ["control.listCreate.scope.option.local"] = "局部列表（仅本宏）",
        ["control.listCreate.scope.option.global"] = "全局列表（所有宏共享）",
        ["control.listCreate.items.label"] = "初始项",
        ["control.listCreate.items.hint"] = "列表一开始包含的值。留空则建立空列表。",

        ["control.listAdd.name"] = "列表追加",
        ["control.listAdd.desc"] = "在一个列表的末尾加入一个或多个值。",
        ["control.listAdd.name.label"] = "列表变量",
        ["control.listAdd.name.hint"] = "宏当前可见的列表。",
        ["control.listAdd.value.label"] = "追加的值",
        ["control.listAdd.value.hint"] = "放到列表末尾的值。",

        ["control.listInsert.name"] = "列表插入",
        ["control.listInsert.desc"] = "把值插入到列表的指定位置。",
        ["control.listInsert.name.label"] = "列表变量",
        ["control.listInsert.name.hint"] = "宏当前可见的列表。",
        ["control.listInsert.index.label"] = "位置",
        ["control.listInsert.index.hint"] = "插入位置，0 表示最前面。",
        ["control.listInsert.value.label"] = "值",
        ["control.listInsert.value.hint"] = "插入到该位置的值。",

        ["control.listRemoveAt.name"] = "列表移除",
        ["control.listRemoveAt.desc"] = "把列表指定位置的项移除。",
        ["control.listRemoveAt.name.label"] = "列表变量",
        ["control.listRemoveAt.name.hint"] = "宏当前可见的列表。",
        ["control.listRemoveAt.index.label"] = "位置",
        ["control.listRemoveAt.index.hint"] = "要移除的位置；-1 表示最后一项。",

        ["control.listClear.name"] = "清空列表",
        ["control.listClear.desc"] = "清空列表内容，变量本身保留。",
        ["control.listClear.name.label"] = "列表变量",
        ["control.listClear.name.hint"] = "宏当前可见的列表。",

        ["control.log.name"] = "写日志",
        ["control.log.desc"] = "向 Viktor 日志写入一条消息。",
        ["control.log.message.label"] = "消息",
        ["control.log.message.hint"] = "写入日志的文本。",
        ["control.log.level.label"] = "级别",

        ["control.runMacro.name"] = "执行其他宏",
        ["control.runMacro.desc"] = "运行本项目里的另一个宏，就像把它的步骤写在这里一样。"
            + "被调用的宏与调用它的宏共用变量，所以它能读取调用者准备的数据，也能把结果留在变量里。",
        ["control.runMacro.macro.label"] = "宏",
        ["control.runMacro.macro.hint"] = "本项目里的另一个宏。改名或删除后这里需要跟着改。",

        // --------------------------------------------------------------------- file
        ["file.readText.name"] = "读取文本",
        ["file.readText.desc"] = "把文本文件读入变量。",
        ["file.readText.path.label"] = "文件",
        ["file.readText.path.hint"] = "要读取的文件。只写文件名时会相对宏文件夹解析。",
        ["file.readText.resultVariable.label"] = "结果变量",
        ["file.readText.resultVariable.hint"] = "接收文件内容的变量。",

        ["file.writeText.name"] = "写入文本",
        ["file.writeText.desc"] = "把文本写入文件，可以替换原内容或追加到末尾。",
        ["file.writeText.path.label"] = "文件",
        ["file.writeText.path.hint"] = "要写入的文件。只写文件名时会相对宏文件夹解析。",
        ["file.writeText.text.label"] = "文本",
        ["file.writeText.text.hint"] = "要写入的文本。",
        ["file.writeText.mode.label"] = "方式",
        ["file.writeText.mode.hint"] = "替换原文件，或追加到已有内容后面。",
        ["file.writeText.mode.option.overwrite"] = "替换原内容",
        ["file.writeText.mode.option.append"] = "追加到末尾",

        ["file.exists.name"] = "文件是否存在",
        ["file.exists.desc"] = "检查文件或文件夹是否存在。",
        ["file.exists.path.label"] = "文件",
        ["file.exists.path.hint"] = "要查找的文件或文件夹。只写名称时会相对宏文件夹解析。",
        ["file.exists.resultVariable.label"] = "结果变量",
        ["file.exists.resultVariable.hint"] = "接收 true 或 false 的变量。",

        ["file.delete.name"] = "删除文件",
        ["file.delete.desc"] = "删除一个文件。",
        ["file.delete.path.label"] = "文件",
        ["file.delete.path.hint"] = "要删除的文件。只写文件名时会相对宏文件夹解析。",

        ["file.copy.name"] = "复制文件",
        ["file.copy.desc"] = "把文件复制到另一个位置。",
        ["file.copy.from.label"] = "源文件",
        ["file.copy.from.hint"] = "要复制的文件。只写文件名时会相对宏文件夹解析。",
        ["file.copy.to.label"] = "目标",
        ["file.copy.to.hint"] = "副本要放到哪里。只写文件名时会相对宏文件夹解析。",
        ["file.copy.overwrite.label"] = "覆盖",
        ["file.copy.overwrite.hint"] = "目标已存在时是否替换。",

        ["file.listFiles.name"] = "列出文件",
        ["file.listFiles.desc"] = "把文件夹里的文件收集成列表。",
        ["file.listFiles.folder.label"] = "文件夹",
        ["file.listFiles.folder.hint"] = "要在其中查找的文件夹。只写名称时会相对宏文件夹解析。",
        ["file.listFiles.pattern.label"] = "匹配模式",
        ["file.listFiles.pattern.hint"] = "要收集哪些文件，例如 *.txt。",
        ["file.listFiles.recurse.label"] = "包含子文件夹",
        ["file.listFiles.resultVariable.label"] = "结果变量",
        ["file.listFiles.resultVariable.hint"] = "接收完整路径列表的变量。",

        ["file.readJson.name"] = "读取 JSON",
        ["file.readJson.desc"] = "从 JSON 文件中读取一个值。",
        ["file.readJson.path.label"] = "文件",
        ["file.readJson.path.hint"] = "要读取的 JSON 文件。只写文件名时会相对宏文件夹解析。",
        ["file.readJson.query.label"] = "位置",
        ["file.readJson.query.hint"] = "值的路径，例如 server.name 或 items[0].id。留空表示整个文件。",
        ["file.readJson.resultVariable.label"] = "结果变量",
        ["file.readJson.resultVariable.hint"] = "接收该值的变量。",

        ["file.writeJson.name"] = "写入 JSON",
        ["file.writeJson.desc"] = "设置 JSON 文件中的一个值，保留其余内容。",
        ["file.writeJson.path.label"] = "文件",
        ["file.writeJson.path.hint"] = "要更新的 JSON 文件。只写文件名时会相对宏文件夹解析。",
        ["file.writeJson.query.label"] = "位置",
        ["file.writeJson.query.hint"] = "值的路径。途经的缺失对象会自动创建。",
        ["file.writeJson.value.label"] = "值",
        ["file.writeJson.value.hint"] = "要存入的值。",

        ["file.readCsv.name"] = "读取 CSV",
        ["file.readCsv.desc"] = "把 CSV 文件读取成行列表。",
        ["file.readCsv.path.label"] = "文件",
        ["file.readCsv.path.hint"] = "要读取的 CSV 文件。只写文件名时会相对宏文件夹解析。",
        ["file.readCsv.separator.label"] = "分隔符",
        ["file.readCsv.separator.hint"] = "两个单元格之间的字符。",
        ["file.readCsv.separator.option.comma"] = "逗号 ,",
        ["file.readCsv.separator.option.semicolon"] = "分号 ;",
        ["file.readCsv.separator.option.tab"] = "制表符",
        ["file.readCsv.separator.option.pipe"] = "竖线 |",
        ["file.readCsv.hasHeader.label"] = "首行是表头",
        ["file.readCsv.hasHeader.hint"] = "结果中不包含第一行。",
        ["file.readCsv.resultVariable.label"] = "结果变量",
        ["file.readCsv.resultVariable.hint"] = "接收行列表的变量，每行是一个单元格列表。",

        ["file.writeCsv.name"] = "写入 CSV",
        ["file.writeCsv.desc"] = "把行列表写入 CSV 文件。",
        ["file.writeCsv.path.label"] = "文件",
        ["file.writeCsv.path.hint"] = "要写入的 CSV 文件。只写文件名时会相对宏文件夹解析。",
        ["file.writeCsv.rows.label"] = "行",
        ["file.writeCsv.rows.hint"] = "行列表。每一行本身也可以是一个单元格列表。",
        ["file.writeCsv.separator.label"] = "分隔符",
        ["file.writeCsv.separator.hint"] = "两个单元格之间的字符。",
        ["file.writeCsv.separator.option.comma"] = "逗号 ,",
        ["file.writeCsv.separator.option.semicolon"] = "分号 ;",
        ["file.writeCsv.separator.option.tab"] = "制表符",
        ["file.writeCsv.separator.option.pipe"] = "竖线 |",

        ["file.saveVariables.name"] = "保存变量",
        ["file.saveVariables.desc"] = "把变量写入 JSON 文件，方便下次运行读取。",
        ["file.saveVariables.path.label"] = "文件",
        ["file.saveVariables.path.hint"] = "要写入的文件。只写文件名时会相对宏文件夹解析。",
        ["file.saveVariables.names.label"] = "哪些变量",
        ["file.saveVariables.names.hint"] = "要保存的名称，用逗号分隔。留空表示所有局部变量和共享变量。",

        ["file.loadVariables.name"] = "读取变量",
        ["file.loadVariables.desc"] = "读取由“保存变量”写出的文件，恢复变量。",
        ["file.loadVariables.path.label"] = "文件",
        ["file.loadVariables.path.hint"] = "要读取的文件。只写文件名时会相对宏文件夹解析。",

        // ---------------------------------------------------------------- clipboard
        ["clipboard.writeText.name"] = "复制到剪贴板",
        ["clipboard.writeText.desc"] = "把文本放进剪贴板，相当于复制。",
        ["clipboard.writeText.text.label"] = "文本",
        ["clipboard.writeText.text.hint"] = "要放进剪贴板的文本。",

        ["clipboard.readText.name"] = "读取剪贴板",
        ["clipboard.readText.desc"] = "把剪贴板上的文本读入变量。",
        ["clipboard.readText.resultVariable.label"] = "结果变量",
        ["clipboard.readText.resultVariable.hint"] = "接收剪贴板文本的变量。",

        ["clipboard.clear.name"] = "清空剪贴板",
        ["clipboard.clear.desc"] = "清空剪贴板内容。",

        ["clipboard.waitChange.name"] = "等待剪贴板",
        ["clipboard.waitChange.desc"] = "等待剪贴板上有新的内容被复制。",
        ["clipboard.waitChange.timeoutMs.label"] = "超时毫秒",
        ["clipboard.waitChange.timeoutMs.hint"] = "最多等待多久，超时即失败。",
        ["clipboard.waitChange.resultVariable.label"] = "结果变量",
        ["clipboard.waitChange.resultVariable.hint"] = "接收新文本的变量，留空表示只等待不保存。",

        ["clipboard.copy.name"] = "复制",
        ["clipboard.copy.desc"] = "发送复制快捷键，并保留复制到的内容。",
        ["clipboard.copy.keys.label"] = "快捷键",
        ["clipboard.copy.keys.hint"] = "用 + 连接，用于复制所选内容。",
        ["clipboard.copy.timeoutMs.label"] = "超时毫秒",
        ["clipboard.copy.timeoutMs.hint"] = "等待剪贴板变化的时长。",
        ["clipboard.copy.resultVariable.label"] = "结果变量",
        ["clipboard.copy.resultVariable.hint"] = "接收复制内容的变量。",

        ["clipboard.paste.name"] = "粘贴",
        ["clipboard.paste.desc"] = "把文本放进剪贴板，并发送粘贴快捷键。",
        ["clipboard.paste.text.label"] = "文本",
        ["clipboard.paste.text.hint"] = "要粘贴的文本。留空表示直接粘贴剪贴板里已有的内容。",
        ["clipboard.paste.keys.label"] = "快捷键",
        ["clipboard.paste.keys.hint"] = "用 + 连接，用于粘贴。",

        // ------------------------------------------------------------------ process
        ["process.start.name"] = "启动程序",
        ["process.start.desc"] = "启动另一个程序，可以选择不显示窗口。",
        ["process.start.file.label"] = "程序",
        ["process.start.file.hint"] = "要启动的程序，例如 notepad.exe。",
        ["process.start.arguments.label"] = "参数",
        ["process.start.arguments.hint"] = "传给程序的参数。",
        ["process.start.workingDirectory.label"] = "工作目录",
        ["process.start.workingDirectory.hint"] = "程序在哪个目录下启动。",
        ["process.start.hidden.label"] = "隐藏窗口",
        ["process.start.hidden.hint"] = "启动时不显示程序窗口。",
        ["process.start.resultVariable.label"] = "结果变量",
        ["process.start.resultVariable.hint"] = "接收进程 id 的变量。",

        ["process.waitFor.name"] = "等待程序",
        ["process.waitFor.desc"] = "等待某个程序开始运行。",
        ["process.waitFor.name.label"] = "程序",
        ["process.waitFor.name.hint"] = "要等待的程序名。",
        ["process.waitFor.timeoutMs.label"] = "超时毫秒",
        ["process.waitFor.timeoutMs.hint"] = "最多等待多久，超时即失败。",
        ["process.waitFor.resultVariable.label"] = "结果变量",
        ["process.waitFor.resultVariable.hint"] = "接收进程 id 的变量。",

        ["process.waitExit.name"] = "等待程序结束",
        ["process.waitExit.desc"] = "等待本宏启动的某个程序结束。",
        ["process.waitExit.id.label"] = "进程 id",
        ["process.waitExit.id.hint"] = "要等待的进程，通常是“启动程序”返回的 id。",
        ["process.waitExit.timeoutMs.label"] = "超时毫秒",
        ["process.waitExit.timeoutMs.hint"] = "最多等待多久，超时即失败。",
        ["process.waitExit.resultVariable.label"] = "结果变量",
        ["process.waitExit.resultVariable.hint"] = "接收退出码的变量。",

        ["process.exists.name"] = "程序是否在运行",
        ["process.exists.desc"] = "检查某个程序是否正在运行。",
        ["process.exists.name.label"] = "程序",
        ["process.exists.name.hint"] = "要查找的程序名。",
        ["process.exists.resultVariable.label"] = "结果变量",
        ["process.exists.resultVariable.hint"] = "接收 true 或 false 的变量。",

        ["process.list.name"] = "列出程序",
        ["process.list.desc"] = "把正在运行的程序名收集成列表。",
        ["process.list.resultVariable.label"] = "结果变量",
        ["process.list.resultVariable.hint"] = "接收名称列表的变量。",

        ["process.kill.name"] = "结束程序",
        ["process.kill.desc"] = "关闭一个程序，默认先请它正常退出。",
        ["process.kill.target.label"] = "程序",
        ["process.kill.target.hint"] = "程序名，或进程 id。",
        ["process.kill.force.label"] = "强制关闭",
        ["process.kill.force.hint"] = "直接结束，而不是先请它退出。",
        ["process.kill.resultVariable.label"] = "结果变量",
        ["process.kill.resultVariable.hint"] = "接收关闭了几个进程的变量。",

        ["command.run.name"] = "执行命令",
        ["command.run.desc"] = "执行一条命令并收集它的输出。",
        ["command.run.file.label"] = "命令",
        ["command.run.file.hint"] = "要运行的程序，例如 cmd.exe。",
        ["command.run.arguments.label"] = "参数",
        ["command.run.arguments.hint"] = "传给命令的参数。",
        ["command.run.workingDirectory.label"] = "工作目录",
        ["command.run.workingDirectory.hint"] = "命令在哪个目录下运行。",
        ["command.run.timeoutMs.label"] = "超时毫秒",
        ["command.run.timeoutMs.hint"] = "命令最多可以运行多久。",
        ["command.run.resultVariable.label"] = "结果变量",
        ["command.run.resultVariable.hint"] = "接收命令输出的变量。",
        ["command.run.errorVariable.label"] = "错误变量",
        ["command.run.errorVariable.hint"] = "接收错误输出的变量。",
        ["command.run.exitCodeVariable.label"] = "退出码变量",
        ["command.run.exitCodeVariable.hint"] = "接收退出码的变量。",

        // ------------------------------------------------------------------ system
        ["system.info.name"] = "系统信息",
        ["system.info.desc"] = "读取关于这台机器的一条信息，例如用户名或某个目录。",
        ["system.info.field.label"] = "字段",
        ["system.info.field.hint"] = "要读取哪一项。",
        ["system.info.field.option.userName"] = "用户名",
        ["system.info.field.option.machineName"] = "计算机名",
        ["system.info.field.option.userDomain"] = "域",
        ["system.info.field.option.osVersion"] = "Windows 版本",
        ["system.info.field.option.processorCount"] = "处理器数量",
        ["system.info.field.option.systemFolder"] = "Windows 目录",
        ["system.info.field.option.tempFolder"] = "临时目录",
        ["system.info.field.option.userFolder"] = "用户目录",
        ["system.info.field.option.desktopFolder"] = "桌面",
        ["system.info.field.option.documentsFolder"] = "文档",
        ["system.info.field.option.downloadsFolder"] = "下载",
        ["system.info.field.option.startupFolder"] = "启动目录",
        ["system.info.field.option.appDataFolder"] = "AppData",
        ["system.info.field.option.programFiles"] = "Program Files",
        ["system.info.resultVariable.label"] = "结果变量",
        ["system.info.resultVariable.hint"] = "接收该值的变量。",

        ["system.environment.name"] = "环境变量",
        ["system.environment.desc"] = "读取一个环境变量。",
        ["system.environment.name.label"] = "名称",
        ["system.environment.name.hint"] = "环境变量的名称。",
        ["system.environment.resultVariable.label"] = "结果变量",
        ["system.environment.resultVariable.hint"] = "接收该值的变量。",

        // ------------------------------------------------------------------ window
        ["window.exists.name"] = "窗口是否存在",
        ["window.exists.desc"] = "检查某个标题的窗口是否已经打开。",
        ["window.exists.title.label"] = "窗口",
        ["window.exists.title.hint"] = "窗口标题的一部分，不区分大小写。留空表示最前面的窗口。",
        ["window.exists.resultVariable.label"] = "结果变量",
        ["window.exists.resultVariable.hint"] = "接收 true 或 false 的变量。",

        ["window.waitFor.name"] = "等待窗口",
        ["window.waitFor.desc"] = "等待某个标题的窗口出现。",
        ["window.waitFor.title.label"] = "窗口",
        ["window.waitFor.title.hint"] = "窗口标题的一部分，不区分大小写。留空表示最前面的窗口。",
        ["window.waitFor.timeoutMs.label"] = "超时毫秒",
        ["window.waitFor.timeoutMs.hint"] = "最多等待多久，超时即失败。",
        ["window.waitFor.resultVariable.label"] = "结果变量",
        ["window.waitFor.resultVariable.hint"] = "接收该窗口标题的变量。",

        ["window.activate.name"] = "激活窗口",
        ["window.activate.desc"] = "把窗口调到最前，若已最小化则先恢复。",
        ["window.activate.title.label"] = "窗口",
        ["window.activate.title.hint"] = "窗口标题的一部分，不区分大小写。留空表示最前面的窗口。",

        ["window.minimize.name"] = "最小化窗口",
        ["window.minimize.desc"] = "把窗口最小化到任务栏。",
        ["window.minimize.title.label"] = "窗口",
        ["window.minimize.title.hint"] = "窗口标题的一部分，不区分大小写。留空表示最前面的窗口。",

        ["window.maximize.name"] = "最大化窗口",
        ["window.maximize.desc"] = "让窗口铺满整个屏幕。",
        ["window.maximize.title.label"] = "窗口",
        ["window.maximize.title.hint"] = "窗口标题的一部分，不区分大小写。留空表示最前面的窗口。",

        ["window.restore.name"] = "还原窗口",
        ["window.restore.desc"] = "把最小化或最大化的窗口恢复成正常大小。",
        ["window.restore.title.label"] = "窗口",
        ["window.restore.title.hint"] = "窗口标题的一部分，不区分大小写。留空表示最前面的窗口。",

        ["window.move.name"] = "移动窗口",
        ["window.move.desc"] = "移动窗口并给它一个新的大小。",
        ["window.move.title.label"] = "窗口",
        ["window.move.title.hint"] = "窗口标题的一部分，不区分大小写。留空表示最前面的窗口。",
        ["window.move.x.label"] = "X",
        ["window.move.x.hint"] = "左边缘的屏幕横坐标。",
        ["window.move.y.label"] = "Y",
        ["window.move.y.hint"] = "上边缘的屏幕纵坐标。",
        ["window.move.width.label"] = "宽度",
        ["window.move.width.hint"] = "新的宽度，单位像素。",
        ["window.move.height.label"] = "高度",
        ["window.move.height.hint"] = "新的高度，单位像素。",

        ["window.close.name"] = "关闭窗口",
        ["window.close.desc"] = "请求关闭窗口，相当于点击关闭按钮。",
        ["window.close.title.label"] = "窗口",
        ["window.close.title.hint"] = "窗口标题的一部分，不区分大小写。留空表示最前面的窗口。",

        ["window.list.name"] = "列出窗口",
        ["window.list.desc"] = "把打开的窗口标题收集成列表。",
        ["window.list.resultVariable.label"] = "结果变量",
        ["window.list.resultVariable.hint"] = "接收标题列表的变量。",

        // -------------------------------------------------------------------- input
        ["input.keyPress.name"] = "按键",
        ["input.keyPress.desc"] = "按下并松开一个按键。",
        ["input.keyPress.key.label"] = "按键",
        ["input.keyPress.key.hint"] = "要按下的键，例如 F5 或 Enter。",
        ["input.keyPress.holdMs.label"] = "按住毫秒",
        ["input.keyPress.holdMs.hint"] = "按键保持按下的时长。",

        ["input.keyDown.name"] = "按下按键",
        ["input.keyDown.desc"] = "保持按下某个键，直到对应的“松开按键”步骤。",
        ["input.keyDown.key.label"] = "按键",

        ["input.keyUp.name"] = "松开按键",
        ["input.keyUp.desc"] = "松开当前处于按下状态的按键。",
        ["input.keyUp.key.label"] = "按键",

        ["input.hotkey.name"] = "组合键",
        ["input.hotkey.desc"] = "按下组合键，例如 Ctrl+Shift+S。",
        ["input.hotkey.keys.label"] = "按键组合",
        ["input.hotkey.keys.hint"] = "用 + 连接，同时按下。",
        ["input.hotkey.holdMs.label"] = "按住毫秒",
        ["input.hotkey.holdMs.hint"] = "组合键保持按下的时长。",

        ["input.typeText.name"] = "输入文本",
        ["input.typeText.desc"] = "输入一段文字。",
        ["input.typeText.text.label"] = "文本",
        ["input.typeText.text.hint"] = "要输入的文本。",
        ["input.typeText.intervalMs.label"] = "间隔毫秒",
        ["input.typeText.intervalMs.hint"] = "每个字符之间的间隔。",

        ["input.mouseMove.name"] = "鼠标移动到",
        ["input.mouseMove.desc"] = "把光标移动到屏幕上的指定位置。",
        ["input.mouseMove.x.label"] = "X",
        ["input.mouseMove.x.hint"] = "目标屏幕横坐标。",
        ["input.mouseMove.y.label"] = "Y",
        ["input.mouseMove.y.hint"] = "目标屏幕纵坐标。",
        ["input.mouseMove.durationMs.label"] = "用时毫秒",
        ["input.mouseMove.durationMs.hint"] = "0 表示瞬间跳到目标位置。",
        ["input.mouseMove.style.label"] = "移动方式",
        ["input.mouseMove.style.hint"] = "鼠标怎么走过去。弧线会绕开直线；模拟人手在弧线上再带一点抖动、两头慢中间快，看起来不像机器画的。走弧线需要时间，所以瞬时移动会自动借 200 毫秒。",
        ["input.mouseMove.style.option.direct"] = "直线",
        ["input.mouseMove.style.option.smooth"] = "弧线",
        ["input.mouseMove.style.option.human"] = "模拟人手",

        ["input.mouseMoveRelative.name"] = "鼠标相对移动",
        ["input.mouseMoveRelative.desc"] = "在当前光标位置的基础上偏移一段距离。",
        ["input.mouseMoveRelative.dx.label"] = "横向偏移",
        ["input.mouseMoveRelative.dx.hint"] = "水平方向移动的像素数。",
        ["input.mouseMoveRelative.dy.label"] = "纵向偏移",
        ["input.mouseMoveRelative.dy.hint"] = "垂直方向移动的像素数。",
        ["input.mouseMoveRelative.durationMs.label"] = "用时毫秒",
        ["input.mouseMoveRelative.durationMs.hint"] = "0 表示瞬间跳到目标位置。",
        ["input.mouseMoveRelative.style.label"] = "移动方式",
        ["input.mouseMoveRelative.style.hint"] = "鼠标怎么走过去。弧线会绕开直线；模拟人手在弧线上再带一点抖动、两头慢中间快，看起来不像机器画的。走弧线需要时间，所以瞬时移动会自动借 200 毫秒。",
        ["input.mouseMoveRelative.style.option.direct"] = "直线",
        ["input.mouseMoveRelative.style.option.smooth"] = "弧线",
        ["input.mouseMoveRelative.style.option.human"] = "模拟人手",

        ["input.mouseClick.name"] = "鼠标点击",
        ["input.mouseClick.desc"] = "在屏幕指定位置点击鼠标按键。",
        ["input.mouseClick.button.label"] = "按键",
        ["input.mouseClick.x.label"] = "X",
        ["input.mouseClick.x.hint"] = "点击位置的横坐标。",
        ["input.mouseClick.y.label"] = "Y",
        ["input.mouseClick.y.hint"] = "点击位置的纵坐标。",
        ["input.mouseClick.clicks.label"] = "点击次数",
        ["input.mouseClick.clicks.hint"] = "一共发送几次点击。",
        ["input.mouseClick.intervalMs.label"] = "间隔毫秒",
        ["input.mouseClick.intervalMs.hint"] = "连续点击之间的间隔。",

        ["input.mouseDoubleClick.name"] = "鼠标双击",
        ["input.mouseDoubleClick.desc"] = "在屏幕指定位置双击鼠标按键。",
        ["input.mouseDoubleClick.button.label"] = "按键",
        ["input.mouseDoubleClick.x.label"] = "X",
        ["input.mouseDoubleClick.x.hint"] = "双击位置的横坐标。",
        ["input.mouseDoubleClick.y.label"] = "Y",
        ["input.mouseDoubleClick.y.hint"] = "双击位置的纵坐标。",

        ["input.mouseDown.name"] = "按下鼠标",
        ["input.mouseDown.desc"] = "保持按住鼠标按键，直到对应的“松开鼠标”步骤。",
        ["input.mouseDown.button.label"] = "按键",
        ["input.mouseDown.x.label"] = "X",
        ["input.mouseDown.x.hint"] = "按下位置的横坐标。",
        ["input.mouseDown.y.label"] = "Y",
        ["input.mouseDown.y.hint"] = "按下位置的纵坐标。",

        ["input.mouseUp.name"] = "松开鼠标",
        ["input.mouseUp.desc"] = "松开当前处于按住状态的鼠标按键。",
        ["input.mouseUp.button.label"] = "按键",
        ["input.mouseUp.x.label"] = "X",
        ["input.mouseUp.x.hint"] = "松开位置的横坐标。",
        ["input.mouseUp.y.label"] = "Y",
        ["input.mouseUp.y.hint"] = "松开位置的纵坐标。",

        ["input.mouseScroll.name"] = "鼠标滚轮",
        ["input.mouseScroll.desc"] = "滚动鼠标滚轮。",
        ["input.mouseScroll.direction.label"] = "方向",
        ["input.mouseScroll.amount.label"] = "格数",
        ["input.mouseScroll.amount.hint"] = "滚动的格数。",
        ["input.mouseScroll.x.label"] = "X",
        ["input.mouseScroll.x.hint"] = "滚动位置的横坐标。",
        ["input.mouseScroll.y.label"] = "Y",
        ["input.mouseScroll.y.hint"] = "滚动位置的纵坐标。",

        ["input.mouseDrag.name"] = "鼠标拖拽",
        ["input.mouseDrag.desc"] = "从一点按住拖到另一点再松开。",
        ["input.mouseDrag.startX.label"] = "起点 X",
        ["input.mouseDrag.startX.hint"] = "拖拽起点的横坐标。",
        ["input.mouseDrag.startY.label"] = "起点 Y",
        ["input.mouseDrag.startY.hint"] = "拖拽起点的纵坐标。",
        ["input.mouseDrag.endX.label"] = "终点 X",
        ["input.mouseDrag.endX.hint"] = "拖拽终点的横坐标。",
        ["input.mouseDrag.endY.label"] = "终点 Y",
        ["input.mouseDrag.endY.hint"] = "拖拽终点的纵坐标。",
        ["input.mouseDrag.button.label"] = "按键",
        ["input.mouseDrag.durationMs.label"] = "用时毫秒",
        ["input.mouseDrag.durationMs.hint"] = "整个拖拽过程的时长。",
        ["input.mouseDrag.steps.label"] = "移动步数",
        ["input.mouseDrag.steps.hint"] = "拖拽过程中发送的中间移动事件数量。",
        ["input.mouseDrag.style.label"] = "移动方式",
        ["input.mouseDrag.style.hint"] = "拖着走的时候鼠标怎么移动。弧线会绕开直线；模拟人手在弧线上再带一点抖动，看起来不像机器画的。",
        ["input.mouseDrag.style.option.direct"] = "直线",
        ["input.mouseDrag.style.option.smooth"] = "弧线",
        ["input.mouseDrag.style.option.human"] = "模拟人手",

        // 输入方式，13 个输入动作共用一组文案。
        ["input.keyPress.inputMode.label"] = "输入方式",
        ["input.keyPress.inputMode.hint"] = InputModeHint,
        ["input.keyPress.inputMode.option.foreground"] = "前台",
        ["input.keyPress.inputMode.option.background"] = "后台消息",
        ["input.keyPress.inputMode.option.driver"] = "驱动级",
        ["input.keyPress.targetWindow.label"] = "目标窗口",
        ["input.keyPress.targetWindow.hint"] = TargetWindowHint,

        ["input.keyDown.inputMode.label"] = "输入方式",
        ["input.keyDown.inputMode.hint"] = InputModeHint,
        ["input.keyDown.inputMode.option.foreground"] = "前台",
        ["input.keyDown.inputMode.option.background"] = "后台消息",
        ["input.keyDown.inputMode.option.driver"] = "驱动级",
        ["input.keyDown.targetWindow.label"] = "目标窗口",
        ["input.keyDown.targetWindow.hint"] = TargetWindowHint,

        ["input.keyUp.inputMode.label"] = "输入方式",
        ["input.keyUp.inputMode.hint"] = InputModeHint,
        ["input.keyUp.inputMode.option.foreground"] = "前台",
        ["input.keyUp.inputMode.option.background"] = "后台消息",
        ["input.keyUp.inputMode.option.driver"] = "驱动级",
        ["input.keyUp.targetWindow.label"] = "目标窗口",
        ["input.keyUp.targetWindow.hint"] = TargetWindowHint,

        ["input.hotkey.inputMode.label"] = "输入方式",
        ["input.hotkey.inputMode.hint"] = InputModeHint,
        ["input.hotkey.inputMode.option.foreground"] = "前台",
        ["input.hotkey.inputMode.option.background"] = "后台消息",
        ["input.hotkey.inputMode.option.driver"] = "驱动级",
        ["input.hotkey.targetWindow.label"] = "目标窗口",
        ["input.hotkey.targetWindow.hint"] = TargetWindowHint,

        ["input.typeText.inputMode.label"] = "输入方式",
        ["input.typeText.inputMode.hint"] = InputModeHint,
        ["input.typeText.inputMode.option.foreground"] = "前台",
        ["input.typeText.inputMode.option.background"] = "后台消息",
        ["input.typeText.inputMode.option.driver"] = "驱动级",
        ["input.typeText.targetWindow.label"] = "目标窗口",
        ["input.typeText.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseMove.inputMode.label"] = "输入方式",
        ["input.mouseMove.inputMode.hint"] = InputModeHint
            + "后台方式下屏幕上的鼠标不会移动，只是让窗口以为鼠标到了那里。",
        ["input.mouseMove.inputMode.option.foreground"] = "前台",
        ["input.mouseMove.inputMode.option.background"] = "后台消息",
        ["input.mouseMove.inputMode.option.driver"] = "驱动级",
        ["input.mouseMove.targetWindow.label"] = "目标窗口",
        ["input.mouseMove.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseMoveRelative.inputMode.label"] = "输入方式",
        ["input.mouseMoveRelative.inputMode.hint"] = InputModeHint
            + "后台方式下屏幕上的鼠标不会移动，只是让窗口以为鼠标到了那里。",
        ["input.mouseMoveRelative.inputMode.option.foreground"] = "前台",
        ["input.mouseMoveRelative.inputMode.option.background"] = "后台消息",
        ["input.mouseMoveRelative.inputMode.option.driver"] = "驱动级",
        ["input.mouseMoveRelative.targetWindow.label"] = "目标窗口",
        ["input.mouseMoveRelative.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseClick.inputMode.label"] = "输入方式",
        ["input.mouseClick.inputMode.hint"] = InputModeHint,
        ["input.mouseClick.inputMode.option.foreground"] = "前台",
        ["input.mouseClick.inputMode.option.background"] = "后台消息",
        ["input.mouseClick.inputMode.option.driver"] = "驱动级",
        ["input.mouseClick.targetWindow.label"] = "目标窗口",
        ["input.mouseClick.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseDoubleClick.inputMode.label"] = "输入方式",
        ["input.mouseDoubleClick.inputMode.hint"] = InputModeHint,
        ["input.mouseDoubleClick.inputMode.option.foreground"] = "前台",
        ["input.mouseDoubleClick.inputMode.option.background"] = "后台消息",
        ["input.mouseDoubleClick.inputMode.option.driver"] = "驱动级",
        ["input.mouseDoubleClick.targetWindow.label"] = "目标窗口",
        ["input.mouseDoubleClick.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseDown.inputMode.label"] = "输入方式",
        ["input.mouseDown.inputMode.hint"] = InputModeHint,
        ["input.mouseDown.inputMode.option.foreground"] = "前台",
        ["input.mouseDown.inputMode.option.background"] = "后台消息",
        ["input.mouseDown.inputMode.option.driver"] = "驱动级",
        ["input.mouseDown.targetWindow.label"] = "目标窗口",
        ["input.mouseDown.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseUp.inputMode.label"] = "输入方式",
        ["input.mouseUp.inputMode.hint"] = InputModeHint,
        ["input.mouseUp.inputMode.option.foreground"] = "前台",
        ["input.mouseUp.inputMode.option.background"] = "后台消息",
        ["input.mouseUp.inputMode.option.driver"] = "驱动级",
        ["input.mouseUp.targetWindow.label"] = "目标窗口",
        ["input.mouseUp.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseScroll.inputMode.label"] = "输入方式",
        ["input.mouseScroll.inputMode.hint"] = InputModeHint,
        ["input.mouseScroll.inputMode.option.foreground"] = "前台",
        ["input.mouseScroll.inputMode.option.background"] = "后台消息",
        ["input.mouseScroll.inputMode.option.driver"] = "驱动级",
        ["input.mouseScroll.targetWindow.label"] = "目标窗口",
        ["input.mouseScroll.targetWindow.hint"] = TargetWindowHint,

        ["input.mouseDrag.inputMode.label"] = "输入方式",
        ["input.mouseDrag.inputMode.hint"] = InputModeHint,
        ["input.mouseDrag.inputMode.option.foreground"] = "前台",
        ["input.mouseDrag.inputMode.option.background"] = "后台消息",
        ["input.mouseDrag.inputMode.option.driver"] = "驱动级",
        ["input.mouseDrag.targetWindow.label"] = "目标窗口",
        ["input.mouseDrag.targetWindow.hint"] = TargetWindowHint,

        // 坐标基准：所有带坐标或矩形的动作共用一组文案。
        ["input.mouseMove.anchorMode.label"] = "坐标基准",
        ["input.mouseMove.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseMove.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseMove.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseMove.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseMove.anchorWindow.label"] = "基准窗口",
        ["input.mouseMove.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseClick.anchorMode.label"] = "坐标基准",
        ["input.mouseClick.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseClick.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseClick.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseClick.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseClick.anchorWindow.label"] = "基准窗口",
        ["input.mouseClick.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseDoubleClick.anchorMode.label"] = "坐标基准",
        ["input.mouseDoubleClick.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseDoubleClick.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseDoubleClick.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseDoubleClick.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseDoubleClick.anchorWindow.label"] = "基准窗口",
        ["input.mouseDoubleClick.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseDown.anchorMode.label"] = "坐标基准",
        ["input.mouseDown.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseDown.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseDown.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseDown.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseDown.anchorWindow.label"] = "基准窗口",
        ["input.mouseDown.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseUp.anchorMode.label"] = "坐标基准",
        ["input.mouseUp.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseUp.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseUp.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseUp.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseUp.anchorWindow.label"] = "基准窗口",
        ["input.mouseUp.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseScroll.anchorMode.label"] = "坐标基准",
        ["input.mouseScroll.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseScroll.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseScroll.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseScroll.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseScroll.anchorWindow.label"] = "基准窗口",
        ["input.mouseScroll.anchorWindow.hint"] = AnchorWindowHint,

        ["input.mouseDrag.anchorMode.label"] = "坐标基准",
        ["input.mouseDrag.anchorMode.hint"] = AnchorModeHint,
        ["input.mouseDrag.anchorMode.option.screen"] = "屏幕像素",
        ["input.mouseDrag.anchorMode.option.window"] = "窗口左上角",
        ["input.mouseDrag.anchorMode.option.client"] = "窗口客户区",
        ["input.mouseDrag.anchorWindow.label"] = "基准窗口",
        ["input.mouseDrag.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.capture.anchorMode.label"] = "坐标基准",
        ["vision.capture.anchorMode.hint"] = AnchorModeHint,
        ["vision.capture.anchorMode.option.screen"] = "屏幕像素",
        ["vision.capture.anchorMode.option.window"] = "窗口左上角",
        ["vision.capture.anchorMode.option.client"] = "窗口客户区",
        ["vision.capture.anchorWindow.label"] = "基准窗口",
        ["vision.capture.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.findImage.anchorMode.label"] = "坐标基准",
        ["vision.findImage.anchorMode.hint"] = AnchorModeHint,
        ["vision.findImage.anchorMode.option.screen"] = "屏幕像素",
        ["vision.findImage.anchorMode.option.window"] = "窗口左上角",
        ["vision.findImage.anchorMode.option.client"] = "窗口客户区",
        ["vision.findImage.anchorWindow.label"] = "基准窗口",
        ["vision.findImage.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.getPixel.anchorMode.label"] = "坐标基准",
        ["vision.getPixel.anchorMode.hint"] = AnchorModeHint,
        ["vision.getPixel.anchorMode.option.screen"] = "屏幕像素",
        ["vision.getPixel.anchorMode.option.window"] = "窗口左上角",
        ["vision.getPixel.anchorMode.option.client"] = "窗口客户区",
        ["vision.getPixel.anchorWindow.label"] = "基准窗口",
        ["vision.getPixel.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.waitColor.anchorMode.label"] = "坐标基准",
        ["vision.waitColor.anchorMode.hint"] = AnchorModeHint,
        ["vision.waitColor.anchorMode.option.screen"] = "屏幕像素",
        ["vision.waitColor.anchorMode.option.window"] = "窗口左上角",
        ["vision.waitColor.anchorMode.option.client"] = "窗口客户区",
        ["vision.waitColor.anchorWindow.label"] = "基准窗口",
        ["vision.waitColor.anchorWindow.hint"] = AnchorWindowHint,

        ["ocr.recognize.anchorMode.label"] = "坐标基准",
        ["ocr.recognize.anchorMode.hint"] = AnchorModeHint,
        ["ocr.recognize.anchorMode.option.screen"] = "屏幕像素",
        ["ocr.recognize.anchorMode.option.window"] = "窗口左上角",
        ["ocr.recognize.anchorMode.option.client"] = "窗口客户区",
        ["ocr.recognize.anchorWindow.label"] = "基准窗口",
        ["ocr.recognize.anchorWindow.hint"] = AnchorWindowHint,

        ["ocr.findText.anchorMode.label"] = "坐标基准",
        ["ocr.findText.anchorMode.hint"] = AnchorModeHint,
        ["ocr.findText.anchorMode.option.screen"] = "屏幕像素",
        ["ocr.findText.anchorMode.option.window"] = "窗口左上角",
        ["ocr.findText.anchorMode.option.client"] = "窗口客户区",
        ["ocr.findText.anchorWindow.label"] = "基准窗口",
        ["ocr.findText.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.imageExists.anchorMode.label"] = "坐标基准",
        ["condition.imageExists.anchorMode.hint"] = AnchorModeHint,
        ["condition.imageExists.anchorMode.option.screen"] = "屏幕像素",
        ["condition.imageExists.anchorMode.option.window"] = "窗口左上角",
        ["condition.imageExists.anchorMode.option.client"] = "窗口客户区",
        ["condition.imageExists.anchorWindow.label"] = "基准窗口",
        ["condition.imageExists.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.textExists.anchorMode.label"] = "坐标基准",
        ["condition.textExists.anchorMode.hint"] = AnchorModeHint,
        ["condition.textExists.anchorMode.option.screen"] = "屏幕像素",
        ["condition.textExists.anchorMode.option.window"] = "窗口左上角",
        ["condition.textExists.anchorMode.option.client"] = "窗口客户区",
        ["condition.textExists.anchorWindow.label"] = "基准窗口",
        ["condition.textExists.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.colorEquals.anchorMode.label"] = "坐标基准",
        ["condition.colorEquals.anchorMode.hint"] = AnchorModeHint,
        ["condition.colorEquals.anchorMode.option.screen"] = "屏幕像素",
        ["condition.colorEquals.anchorMode.option.window"] = "窗口左上角",
        ["condition.colorEquals.anchorMode.option.client"] = "窗口客户区",
        ["condition.colorEquals.anchorWindow.label"] = "基准窗口",
        ["condition.colorEquals.anchorWindow.hint"] = AnchorWindowHint,

        // ------------------------------------- 找图 / 找色做厚：多命中、多区域、多点比色
        ["vision.findImage.matchIndex.label"] = "第几个命中",
        ["vision.findImage.matchIndex.hint"] = MatchIndexHint,
        ["vision.findImage.allMatches.label"] = "记录全部命中",
        ["vision.findImage.allMatches.hint"] = AllMatchesHint,

        ["vision.waitImage.region.label"] = "搜索区域",
        ["vision.waitImage.region.hint"] = RegionHintText,
        ["vision.waitImage.matchIndex.label"] = "第几个命中",
        ["vision.waitImage.matchIndex.hint"] = MatchIndexHint,
        ["vision.waitImage.anchorMode.label"] = "坐标基准",
        ["vision.waitImage.anchorMode.hint"] = AnchorModeHint,
        ["vision.waitImage.anchorMode.option.screen"] = "屏幕像素",
        ["vision.waitImage.anchorMode.option.window"] = "窗口左上角",
        ["vision.waitImage.anchorMode.option.client"] = "窗口客户区",
        ["vision.waitImage.anchorWindow.label"] = "基准窗口",
        ["vision.waitImage.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.clickImage.region.label"] = "搜索区域",
        ["vision.clickImage.region.hint"] = RegionHintText,
        ["vision.clickImage.matchIndex.label"] = "第几个命中",
        ["vision.clickImage.matchIndex.hint"] = MatchIndexHint,
        ["vision.clickImage.anchorMode.label"] = "坐标基准",
        ["vision.clickImage.anchorMode.hint"] = AnchorModeHint,
        ["vision.clickImage.anchorMode.option.screen"] = "屏幕像素",
        ["vision.clickImage.anchorMode.option.window"] = "窗口左上角",
        ["vision.clickImage.anchorMode.option.client"] = "窗口客户区",
        ["vision.clickImage.anchorWindow.label"] = "基准窗口",
        ["vision.clickImage.anchorWindow.hint"] = AnchorWindowHint,

        ["vision.findColor.name"] = "查找颜色",
        ["vision.findColor.desc"] = "在屏幕的一块区域里找某个颜色。",
        ["vision.findColor.color.label"] = "颜色",
        ["vision.findColor.color.hint"] = "要找的颜色。",
        ["vision.findColor.tolerance.label"] = "容差 %",
        ["vision.findColor.tolerance.hint"] = "允许的颜色偏差。",
        ["vision.findColor.matchIndex.label"] = "第几个命中",
        ["vision.findColor.matchIndex.hint"] = MatchIndexHint,
        ["vision.findColor.allMatches.label"] = "记录全部命中",
        ["vision.findColor.allMatches.hint"] = AllMatchesHint,
        ["vision.findColor.region.label"] = "搜索区域",
        ["vision.findColor.region.hint"] = RegionHintText,
        ["vision.findColor.timeoutMs.label"] = "超时毫秒",
        ["vision.findColor.timeoutMs.hint"] =
            "0 表示只找一次，找不到就把结果留空；填了数字就等它出现，一直不出现算失败。",
        ["vision.findColor.intervalMs.label"] = "间隔毫秒",
        ["vision.findColor.intervalMs.hint"] = "等待时两次查找之间的间隔。",
        ["vision.findColor.resultVariable.label"] = "结果变量",
        ["vision.findColor.resultVariable.hint"] =
            "接收找到的位置，没找到时为空；$变量名.x、.y、.score 是各个部分，"
            + "勾了“记录全部命中”后还有 .count 和 .list。",
        ["vision.findColor.anchorMode.label"] = "坐标基准",
        ["vision.findColor.anchorMode.hint"] = AnchorModeHint,
        ["vision.findColor.anchorMode.option.screen"] = "屏幕像素",
        ["vision.findColor.anchorMode.option.window"] = "窗口左上角",
        ["vision.findColor.anchorMode.option.client"] = "窗口客户区",
        ["vision.findColor.anchorWindow.label"] = "基准窗口",
        ["vision.findColor.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.colorsMatch.name"] = "多点比色",
        ["condition.colorsMatch.desc"] = "当若干个点都显示指定的颜色时为真。",
        ["condition.colorsMatch.points.label"] = "比色点",
        ["condition.colorsMatch.points.hint"] =
            "每个点写成 x,y,#RRGGBB，用分号或换行分开。",
        ["condition.colorsMatch.tolerance.label"] = "容差 %",
        ["condition.colorsMatch.tolerance.hint"] = "允许的颜色偏差。",
        ["condition.colorsMatch.mode.label"] = "满足方式",
        ["condition.colorsMatch.mode.hint"] = "每个点都要匹配，还是有一个匹配就算满足。",
        ["condition.colorsMatch.mode.option.all"] = "全部匹配",
        ["condition.colorsMatch.mode.option.any"] = "任意一个匹配",
        ["condition.colorsMatch.anchorMode.label"] = "坐标基准",
        ["condition.colorsMatch.anchorMode.hint"] = AnchorModeHint,
        ["condition.colorsMatch.anchorMode.option.screen"] = "屏幕像素",
        ["condition.colorsMatch.anchorMode.option.window"] = "窗口左上角",
        ["condition.colorsMatch.anchorMode.option.client"] = "窗口客户区",
        ["condition.colorsMatch.anchorWindow.label"] = "基准窗口",
        ["condition.colorsMatch.anchorWindow.hint"] = AnchorWindowHint,

        // ------------------------------------------------------------------- vision
        ["vision.capture.name"] = "截屏",
        ["vision.capture.desc"] = "把屏幕的一块区域截取到图像变量里。",
        ["vision.capture.x.label"] = "X",
        ["vision.capture.x.hint"] = "区域左上角横坐标。",
        ["vision.capture.y.label"] = "Y",
        ["vision.capture.y.hint"] = "区域左上角纵坐标。",
        ["vision.capture.width.label"] = "宽度",
        ["vision.capture.width.hint"] = "区域宽度（像素）。",
        ["vision.capture.height.label"] = "高度",
        ["vision.capture.height.hint"] = "区域高度（像素）。",
        ["vision.capture.saveTo.label"] = "保存到变量",
        ["vision.capture.saveTo.hint"] = "接收截图的变量。$变量名.x、.y、.width、.height 记录这次截图覆盖的矩形。",

        ["vision.findImage.name"] = "查找图片",
        ["vision.findImage.desc"] = "在屏幕上寻找一张参考图片。",
        ["vision.findImage.image.label"] = "图片文件",
        ["vision.findImage.image.hint"] = "参考图片：文件路径，或截图动作保存的变量（如 $shot）。",
        ["vision.findImage.confidence.label"] = "相似度 %",
        ["vision.findImage.confidence.hint"] = "要求的最低匹配度。",
        ["vision.findImage.region.label"] = "搜索区域",
        ["vision.findImage.region.hint"] = RegionHintText,
        ["vision.findImage.resultVariable.label"] = "结果变量",
        ["vision.findImage.resultVariable.hint"] = "接收匹配中心点，未找到时为空；$变量名.x、.y、.width、.height、.score 是各个部分。",

        ["vision.waitImage.name"] = "等待图片",
        ["vision.waitImage.desc"] = "等待参考图片在屏幕上出现。",
        ["vision.waitImage.image.label"] = "图片文件",
        ["vision.waitImage.image.hint"] = "要等待的参考图片：文件路径，或截图动作保存的变量。",
        ["vision.waitImage.confidence.label"] = "相似度 %",
        ["vision.waitImage.confidence.hint"] = "要求的最低匹配度。",
        ["vision.waitImage.timeoutMs.label"] = "超时毫秒",
        ["vision.waitImage.timeoutMs.hint"] = "超过这个时长就放弃。",
        ["vision.waitImage.intervalMs.label"] = "间隔毫秒",
        ["vision.waitImage.intervalMs.hint"] = "两次检测之间的间隔。",
        ["vision.waitImage.resultVariable.label"] = "结果变量",

        ["vision.clickImage.name"] = "点击图片",
        ["vision.clickImage.desc"] = "在屏幕上找到参考图片并点击它。",
        ["vision.clickImage.image.label"] = "图片文件",
        ["vision.clickImage.confidence.label"] = "相似度 %",
        ["vision.clickImage.confidence.hint"] = "要求的最低匹配度。",
        ["vision.clickImage.offsetX.label"] = "横向偏移",
        ["vision.clickImage.offsetX.hint"] = "在匹配中心基础上水平偏移的像素。",
        ["vision.clickImage.offsetY.label"] = "纵向偏移",
        ["vision.clickImage.timeoutMs.label"] = "超时毫秒",
        ["vision.clickImage.timeoutMs.hint"] = "等待图片出现的时长，超时即放弃。",
        ["vision.clickImage.button.label"] = "按键",

        ["vision.getPixel.name"] = "取色",
        ["vision.getPixel.desc"] = "读取某个像素的颜色。",
        ["vision.getPixel.x.label"] = "X",
        ["vision.getPixel.x.hint"] = "取样点的横坐标。",
        ["vision.getPixel.y.label"] = "Y",
        ["vision.getPixel.y.hint"] = "取样点的纵坐标。",
        ["vision.getPixel.resultVariable.label"] = "结果变量",
        ["vision.getPixel.resultVariable.hint"] = "接收颜色的变量，可沿用已有变量名或新建一个。",
        ["vision.getPixel.asHex.label"] = "存为十六进制",
        ["vision.getPixel.asHex.hint"] = "存成 #RRGGBB，而不是原始通道值。",

        ["vision.waitColor.name"] = "等待颜色",
        ["vision.waitColor.desc"] = "等待某个像素变成指定颜色。",
        ["vision.waitColor.x.label"] = "X",
        ["vision.waitColor.x.hint"] = "监视点的横坐标。",
        ["vision.waitColor.y.label"] = "Y",
        ["vision.waitColor.y.hint"] = "监视点的纵坐标。",
        ["vision.waitColor.color.label"] = "颜色",
        ["vision.waitColor.color.hint"] = "像素需要显示的颜色。",
        ["vision.waitColor.tolerance.label"] = "容差 %",
        ["vision.waitColor.tolerance.hint"] = "允许的颜色偏差。",
        ["vision.waitColor.timeoutMs.label"] = "超时毫秒",
        ["vision.waitColor.timeoutMs.hint"] = "超过这个时长就放弃。",

        // ---------------------------------------------------------------------- ocr
        ["ocr.recognize.name"] = "识别文字",
        ["ocr.recognize.desc"] = "识别屏幕某块区域里的文字。",
        ["ocr.recognize.x.label"] = "X",
        ["ocr.recognize.x.hint"] = "区域左上角横坐标。",
        ["ocr.recognize.y.label"] = "Y",
        ["ocr.recognize.y.hint"] = "区域左上角纵坐标。",
        ["ocr.recognize.width.label"] = "宽度",
        ["ocr.recognize.width.hint"] = "区域宽度（像素）。",
        ["ocr.recognize.height.label"] = "高度",
        ["ocr.recognize.height.hint"] = "区域高度（像素）。",
        ["ocr.recognize.language.label"] = "语言",
        ["ocr.recognize.resultVariable.label"] = "结果变量",
        ["ocr.recognize.resultVariable.hint"] = "接收识别结果的变量，可沿用已有变量名或新建一个。",

        ["ocr.findText.name"] = "查找文字",
        ["ocr.findText.desc"] = "在屏幕上搜索指定文字。",
        ["ocr.findText.text.label"] = "要查找的文字",
        ["ocr.findText.text.hint"] = "要搜索的文字。",
        ["ocr.findText.region.label"] = "搜索区域",
        ["ocr.findText.region.hint"] = RegionHintText,
        ["ocr.findText.matchMode.label"] = "匹配方式",
        ["ocr.findText.matchMode.hint"] = "识别结果与搜索文字的比较方式。",
        ["ocr.findText.resultVariable.label"] = "结果变量",
        ["ocr.findText.resultVariable.hint"] = "接收匹配中心点，未找到时为空；$变量名.x、.y、.text、.score 是各个部分。",

        ["ocr.clickText.name"] = "点击文字",
        ["ocr.clickText.desc"] = "在屏幕上找到文字并点击它。",
        ["ocr.clickText.text.label"] = "要查找的文字",
        ["ocr.clickText.matchMode.label"] = "匹配方式",
        ["ocr.clickText.matchMode.hint"] = "识别结果与搜索文字的比较方式。",
        ["ocr.clickText.offsetX.label"] = "横向偏移",
        ["ocr.clickText.offsetX.hint"] = "在匹配中心基础上水平偏移的像素。",
        ["ocr.clickText.offsetY.label"] = "纵向偏移",
        ["ocr.clickText.timeoutMs.label"] = "超时毫秒",
        ["ocr.clickText.timeoutMs.hint"] = "等待文字出现的时长，超时即放弃。",
        ["ocr.clickText.button.label"] = "按键",

        // ---------------------------------------------------------------------- uia
        ["uia.exists.name"] = "元素是否存在",
        ["uia.exists.desc"] = "判断某个 UI Automation 元素是否存在。",
        ["uia.exists.window.label"] = "窗口",
        ["uia.exists.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.exists.selector.label"] = "选择器",
        ["uia.exists.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.exists.timeoutMs.label"] = "超时毫秒",
        ["uia.exists.timeoutMs.hint"] = "0 表示只检查一次并立即返回。",
        ["uia.exists.resultVariable.label"] = "结果变量",
        ["uia.exists.resultVariable.hint"] = "接收 true / false 的变量。",

        ["uia.waitElement.name"] = "等待元素",
        ["uia.waitElement.desc"] = "等待某个 UI Automation 元素出现。",
        ["uia.waitElement.window.label"] = "窗口",
        ["uia.waitElement.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.waitElement.selector.label"] = "选择器",
        ["uia.waitElement.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.waitElement.timeoutMs.label"] = "超时毫秒",
        ["uia.waitElement.timeoutMs.hint"] = "超过这个时长就放弃。",
        ["uia.waitElement.pollMs.label"] = "轮询毫秒",
        ["uia.waitElement.pollMs.hint"] = "两次检查之间的间隔。",

        ["uia.click.name"] = "点击元素",
        ["uia.click.desc"] = "点击一个 UI Automation 元素。",
        ["uia.click.window.label"] = "窗口",
        ["uia.click.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.click.selector.label"] = "选择器",
        ["uia.click.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.click.timeoutMs.label"] = "超时毫秒",
        ["uia.click.timeoutMs.hint"] = "点击前等待元素出现的时长。",
        ["uia.click.button.label"] = "按键",

        ["uia.setText.name"] = "设置元素文本",
        ["uia.setText.desc"] = "向 UI Automation 元素输入文本。",
        ["uia.setText.window.label"] = "窗口",
        ["uia.setText.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.setText.selector.label"] = "选择器",
        ["uia.setText.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.setText.text.label"] = "文本",
        ["uia.setText.text.hint"] = "写入元素的文本。",
        ["uia.setText.clearFirst.label"] = "先清空",
        ["uia.setText.clearFirst.hint"] = "输入前先清空输入框内容。",

        ["uia.getText.name"] = "读取元素文本",
        ["uia.getText.desc"] = "读取 UI Automation 元素的文本。",
        ["uia.getText.window.label"] = "窗口",
        ["uia.getText.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["uia.getText.selector.label"] = "选择器",
        ["uia.getText.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",
        ["uia.getText.resultVariable.label"] = "结果变量",
        ["uia.getText.resultVariable.hint"] = "接收文本的变量。",

        ["uia.focusWindow.name"] = "窗口置前",
        ["uia.focusWindow.desc"] = "把某个窗口切换到最前面。",
        ["uia.focusWindow.window.label"] = "窗口",
        ["uia.focusWindow.window.hint"] = "窗口标题，或保存标题的 $变量。可以用“拾取窗口”从当前打开的窗口里选一个。",

        // ---------------------------------------------------------------- condition
        ["condition.imageExists.name"] = "图片存在",
        ["condition.imageExists.desc"] = "当参考图片出现在屏幕上时为真。",
        ["condition.imageExists.image.label"] = "图片文件",
        ["condition.imageExists.confidence.label"] = "相似度 %",
        ["condition.imageExists.confidence.hint"] = "要求的最低匹配度。",
        ["condition.imageExists.region.label"] = "搜索区域",
        ["condition.imageExists.region.hint"] = RegionHintText,

        ["condition.textExists.name"] = "文字存在",
        ["condition.textExists.desc"] = "当屏幕上出现指定文字时为真。",
        ["condition.textExists.text.label"] = "文字",
        ["condition.textExists.region.label"] = "搜索区域",
        ["condition.textExists.region.hint"] = RegionHintText,
        ["condition.textExists.matchMode.label"] = "匹配方式",
        ["condition.textExists.matchMode.hint"] = "识别结果与搜索文字的比较方式。",

        ["condition.uiaExists.name"] = "UI 元素存在",
        ["condition.uiaExists.desc"] = "当 UI Automation 元素存在时为真。",
        ["condition.uiaExists.window.label"] = "窗口",
        ["condition.uiaExists.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["condition.uiaExists.selector.label"] = "选择器",
        ["condition.uiaExists.selector.hint"] = "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",

        ["condition.colorEquals.name"] = "颜色相同",
        ["condition.colorEquals.desc"] = "当某个像素的颜色匹配时为真。",
        ["condition.colorEquals.x.label"] = "X",
        ["condition.colorEquals.x.hint"] = "比较点的横坐标。",
        ["condition.colorEquals.y.label"] = "Y",
        ["condition.colorEquals.y.hint"] = "比较点的纵坐标。",
        ["condition.colorEquals.color.label"] = "颜色",
        ["condition.colorEquals.tolerance.label"] = "容差 %",
        ["condition.colorEquals.tolerance.hint"] = "允许的颜色偏差。",

        // ------------------------------------------ 否定条件与布尔表达式（条件也能自己写公式）
        ["condition.imageNotExists.name"] = "图片不存在",
        ["condition.imageNotExists.desc"] = "当参考图片不在屏幕上时为真。",
        ["condition.imageNotExists.image.label"] = "图片文件",
        ["condition.imageNotExists.confidence.label"] = "相似度 %",
        ["condition.imageNotExists.confidence.hint"] = "要求的最低匹配度。",
        ["condition.imageNotExists.region.label"] = "搜索区域",
        ["condition.imageNotExists.region.hint"] = RegionHintText,
        ["condition.imageNotExists.anchorMode.label"] = "坐标基准",
        ["condition.imageNotExists.anchorMode.hint"] = AnchorModeHint,
        ["condition.imageNotExists.anchorMode.option.screen"] = "屏幕像素",
        ["condition.imageNotExists.anchorMode.option.window"] = "窗口左上角",
        ["condition.imageNotExists.anchorMode.option.client"] = "窗口客户区",
        ["condition.imageNotExists.anchorWindow.label"] = "基准窗口",
        ["condition.imageNotExists.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.textNotExists.name"] = "文字不存在",
        ["condition.textNotExists.desc"] = "当屏幕上没有指定文字时为真。",
        ["condition.textNotExists.text.label"] = "文字",
        ["condition.textNotExists.region.label"] = "搜索区域",
        ["condition.textNotExists.region.hint"] = RegionHintText,
        ["condition.textNotExists.matchMode.label"] = "匹配方式",
        ["condition.textNotExists.matchMode.hint"] = "识别结果与搜索文字的比较方式。",
        ["condition.textNotExists.matchMode.option.contains"] = "包含",
        ["condition.textNotExists.matchMode.option.exact"] = "完全匹配",
        ["condition.textNotExists.matchMode.option.regex"] = "正则匹配",
        ["condition.textNotExists.anchorMode.label"] = "坐标基准",
        ["condition.textNotExists.anchorMode.hint"] = AnchorModeHint,
        ["condition.textNotExists.anchorMode.option.screen"] = "屏幕像素",
        ["condition.textNotExists.anchorMode.option.window"] = "窗口左上角",
        ["condition.textNotExists.anchorMode.option.client"] = "窗口客户区",
        ["condition.textNotExists.anchorWindow.label"] = "基准窗口",
        ["condition.textNotExists.anchorWindow.hint"] = AnchorWindowHint,

        ["condition.uiaNotExists.name"] = "UI 元素不存在",
        ["condition.uiaNotExists.desc"] = "当某个 UI Automation 元素不存在时为真。",
        ["condition.uiaNotExists.window.label"] = "窗口",
        ["condition.uiaNotExists.window.hint"] = "可选的窗口标题过滤；留空表示在所有窗口中查找。",
        ["condition.uiaNotExists.selector.label"] = "选择器",
        ["condition.uiaNotExists.selector.hint"] =
            "元素选择器，例如 Button[name='Save']。也可以点“拾取元素”，直接瞄准屏幕上的控件抓取。",

        ["condition.expression.name"] = "布尔表达式",
        ["condition.expression.desc"] = "自己写一段表达式，结果为真时条件成立。",
        ["condition.expression.expression.label"] = "表达式",
        ["condition.expression.expression.hint"] =
            "用 $变量、运算符和内置函数拼出一个真 / 假结果，例如 $count > 3 and contains($name, \"ok\")。"
            + "每次判断都会重新求值，所以在等待里它跟着变量一起变。",

        ["condition.compare.name"] = "条件判断",
        ["condition.compare.desc"] = "把一个变量与另一个值或变量进行比较。",
        ["condition.compare.variable.label"] = "变量",
        ["condition.compare.variable.hint"] = "要判断的变量；候选项来自前面步骤创建过的变量。",
        ["condition.compare.operator.label"] = "判断方式",
        ["condition.compare.operator.hint"] = "变量与比较值之间的关系。",
        ["condition.compare.value.label"] = "变量或值",
        ["condition.compare.value.hint"] = "可从下拉中选择已有变量，也可以直接输入数字或文本；判断“变量存在”时可留空。",
        ["condition.compare.operator.option.equals"] = "等于",
        ["condition.compare.operator.option.notEquals"] = "不等于",
        ["condition.compare.operator.option.greaterThan"] = "大于",
        ["condition.compare.operator.option.greaterOrEqual"] = "大于等于",
        ["condition.compare.operator.option.lessThan"] = "小于",
        ["condition.compare.operator.option.lessOrEqual"] = "小于等于",
        ["condition.compare.operator.option.contains"] = "包含",
        ["condition.compare.operator.option.notContains"] = "不包含",
        ["condition.compare.operator.option.exists"] = "变量存在",
        ["condition.compare.operator.option.regexMatch"] = "正则匹配",

        ["condition.group.name"] = "条件组",
        ["condition.group.desc"] = "用“与 / 或 / 非”把多个条件组合在一起：与＝全部满足，或＝任一满足，非＝全部不满足。",
        ["condition.group.op.label"] = "逻辑",
        ["condition.group.op.hint"] = "子条件的组合方式；有两个以上条件时才会生效。",
        ["condition.group.op.option.and"] = "与（全部满足）",
        ["condition.group.op.option.or"] = "或（任一满足）",
        ["condition.group.op.option.none"] = "非（全部不满足）",
        ["condition.group.conditions.label"] = "子条件",
        ["condition.group.conditions.hint"] = "加两个以上条件后，可用上面的逻辑组合它们；条件组可以继续嵌套。",

        ["condition.randomChance.name"] = "随机概率",
        ["condition.randomChance.desc"] = "按固定概率随机为真。",
        ["condition.randomChance.percent.label"] = "概率 %",
        ["condition.randomChance.percent.hint"] = "条件为真的概率。",

        // ------------------------------------------------- 下拉选项（每个动作各一份键）
        // 鼠标按键在八个动作里出现，措辞必须一致，否则同一个下拉框换个动作就变样。
        ["input.mouseClick.button.option.left"] = "左键",
        ["input.mouseClick.button.option.right"] = "右键",
        ["input.mouseClick.button.option.middle"] = "中键",
        ["input.mouseClick.button.option.back"] = "后退键",
        ["input.mouseClick.button.option.forward"] = "前进键",
        ["input.mouseDoubleClick.button.option.left"] = "左键",
        ["input.mouseDoubleClick.button.option.right"] = "右键",
        ["input.mouseDoubleClick.button.option.middle"] = "中键",
        ["input.mouseDoubleClick.button.option.back"] = "后退键",
        ["input.mouseDoubleClick.button.option.forward"] = "前进键",
        ["input.mouseDown.button.option.left"] = "左键",
        ["input.mouseDown.button.option.right"] = "右键",
        ["input.mouseDown.button.option.middle"] = "中键",
        ["input.mouseDown.button.option.back"] = "后退键",
        ["input.mouseDown.button.option.forward"] = "前进键",
        ["input.mouseUp.button.option.left"] = "左键",
        ["input.mouseUp.button.option.right"] = "右键",
        ["input.mouseUp.button.option.middle"] = "中键",
        ["input.mouseUp.button.option.back"] = "后退键",
        ["input.mouseUp.button.option.forward"] = "前进键",
        ["input.mouseDrag.button.option.left"] = "左键",
        ["input.mouseDrag.button.option.right"] = "右键",
        ["input.mouseDrag.button.option.middle"] = "中键",
        ["input.mouseDrag.button.option.back"] = "后退键",
        ["input.mouseDrag.button.option.forward"] = "前进键",
        ["vision.clickImage.button.option.left"] = "左键",
        ["vision.clickImage.button.option.right"] = "右键",
        ["vision.clickImage.button.option.middle"] = "中键",
        ["vision.clickImage.button.option.back"] = "后退键",
        ["vision.clickImage.button.option.forward"] = "前进键",
        ["ocr.clickText.button.option.left"] = "左键",
        ["ocr.clickText.button.option.right"] = "右键",
        ["ocr.clickText.button.option.middle"] = "中键",
        ["ocr.clickText.button.option.back"] = "后退键",
        ["ocr.clickText.button.option.forward"] = "前进键",
        ["uia.click.button.option.left"] = "左键",
        ["uia.click.button.option.right"] = "右键",
        ["uia.click.button.option.middle"] = "中键",
        ["uia.click.button.option.back"] = "后退键",
        ["uia.click.button.option.forward"] = "前进键",

        ["input.mouseScroll.direction.option.up"] = "向上",
        ["input.mouseScroll.direction.option.down"] = "向下",
        ["input.mouseScroll.direction.option.left"] = "向左",
        ["input.mouseScroll.direction.option.right"] = "向右",

        ["ocr.recognize.language.option.auto"] = "自动",
        ["ocr.recognize.language.option.en"] = "英文",
        ["ocr.recognize.language.option.zh"] = "中文",

        ["ocr.findText.matchMode.option.contains"] = "包含",
        ["ocr.findText.matchMode.option.exact"] = "完全匹配",
        ["ocr.findText.matchMode.option.regex"] = "正则匹配",
        ["ocr.clickText.matchMode.option.contains"] = "包含",
        ["ocr.clickText.matchMode.option.exact"] = "完全匹配",
        ["ocr.clickText.matchMode.option.regex"] = "正则匹配",
        ["condition.textExists.matchMode.option.contains"] = "包含",
        ["condition.textExists.matchMode.option.exact"] = "完全匹配",
        ["condition.textExists.matchMode.option.regex"] = "正则匹配",

        ["control.log.level.option.info"] = "信息",
        ["control.log.level.option.warn"] = "警告",
        ["control.log.level.option.error"] = "错误",
        ["control.log.level.option.debug"] = "调试",
    };
}
