using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace Viktor.Localization;

/// <summary>
/// Every user-facing string, keyed by area. XAML binds to the indexer
/// (<c>{Binding [Main.Save], Source={x:Static loc:Strings.Current}}</c>) so switching
/// the language refreshes whatever is already on screen.
/// </summary>
public sealed class Strings : INotifyPropertyChanged
{
    private static readonly Strings Instance = new();

    private Language _language = LocalSettings.Load();

    public static Strings Current => Instance;

    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>Raised after the language changes, for text set from code.</summary>
    public event Action? LanguageChanged;

    public Language Language
    {
        get => _language;
        set
        {
            if (_language == value)
            {
                return;
            }

            _language = value;
            LocalSettings.Store(value);

            // An empty name means "everything on this source changed", which refreshes
            // every indexer binding in one go.
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            LanguageChanged?.Invoke();
        }
    }

    /// <summary>Text for a key in the current language.</summary>
    public string this[string key] => Get(key);

    /// <summary>
    /// Text for a key. Falls back to <paramref name="fallback"/> when the key is not
    /// translated, which is how the action catalogue keeps its English text inline.
    /// </summary>
    public static string Get(string key, string? fallback = null)
    {
        // Chrome text lives in this file, action text in ActionStrings; both are Chinese only.
        if (Instance._language == Language.Chinese
            && (Chinese.TryGetValue(key, out var chinese)
                || ActionStrings.Chinese.TryGetValue(key, out chinese)))
        {
            return chinese;
        }

        if (English.TryGetValue(key, out var english))
        {
            return english;
        }

        return fallback ?? key;
    }

    /// <summary>Text for a key, with placeholders filled in by <see cref="string.Format"/>.</summary>
    public static string Format(string key, params object[] arguments)
        => string.Format(Get(key), arguments);

    internal static readonly Dictionary<string, string> English = new()
    {
        // ------------------------------------------------------------- main window
        ["Main.Title"] = "Viktor",
        ["Main.AdminBadge"] = " (Admin)",
        ["Main.File"] = "_File",
        ["Main.Help"] = "_Help",
        ["Main.OpenProject"] = "Open Macro Project",
        ["Main.SaveProject"] = "Save Macro Project",
        ["Main.SaveProjectAs"] = "Save Macro Project As",
        ["Main.ImportProject"] = "Import Macro Project",
        ["Main.OpenCurrentLocation"] = "Open Current Macro Location",
        ["Main.ReloadCurrent"] = "Reload Current Macro",
        ["Main.OpenDirectory"] = "Open Macro Directory",
        ["Main.CloseAll"] = "Close All",
        ["Main.Settings"] = "Settings",
        ["Main.WhatsNew"] = "What's New",
        ["Main.Updates"] = "Updates",
        ["Main.Feedback"] = "Feedback",
        ["Main.GetStarted"] = "Get Started",
        ["Main.About"] = "About",
        ["Main.SearchPlaceholder"] = "Type to search..",
        ["Main.EmptyTitle"] = "No macros yet.",
        ["Main.EmptyHint"] = "Use Add New Macro below to build your first macro.",
        ["Main.EditTip"] = "Edit",
        ["Main.DeleteTip"] = "Delete",
        ["Main.AddMacro"] = "Add New Macro",
        ["Main.SystemEnabled"] = "Enabled",
        ["Main.SystemDisabled"] = "Disabled",
        ["Main.SystemEnableHint"] = "Press Home to enable",
        ["Main.SystemDisableHint"] = "Press Home to disable",
        ["Main.MacroRunning"] = "Running",
        ["Main.AlwaysOnTop"] = "Always on Top",
        ["Main.AlwaysOnTopCancel"] = "Stop Staying on Top",

        // ----------------------------------------------------------- macro editor
        ["Editor.Title"] = "Macro Editor",
        ["Editor.NamePlaceholder"] = "Enter a name for your macro..",
        ["Editor.TriggerSettings"] = "Trigger Settings",
        ["Editor.TriggerBy"] = "Trigger by :",
        ["Editor.Loop"] = "Loop :",
        ["Editor.BindKey"] = "Trigger / Bind Key :",
        ["Editor.NoKey"] = "No Key Selected",
        ["Editor.SetKey"] = "Set Key",
        ["Editor.PressKey"] = "Press a key…",
        ["Editor.When"] = "When :",
        ["Editor.ColorPosition"] = "Color Position on Screen :",
        ["Editor.X"] = "X :",
        ["Editor.Y"] = "Y :",
        ["Editor.UseCursorPosition"] = "Use cursor position",
        ["Editor.TriggerOnce"] = "Trigger Once",
        ["Editor.HexColor"] = "Input Hex Color :",
        ["Editor.ColorTolerance"] = "Color Tolerance :",
        ["Editor.AltXHint"] = "Press Alt + X to capture current cursor position",
        ["Editor.AltCHint"] = "Press Alt + C to capture screen color at cursor position",
        ["Editor.PickColor"] = "Pick a color from the screen",
        ["Editor.Schedule"] = "Schedule :",
        ["Editor.Interval"] = "Every :",
        ["Editor.ScheduleTime"] = "Time :",
        ["Editor.ScheduleTimeHint"] = "HH:mm, or HH:mm:ss",
        ["Editor.ScheduleNote"] = "A timed macro runs one pass each time its schedule comes "
            + "round. Counting starts when the system is switched on.",
        ["Editor.WatchPath"] = "File or Folder :",
        ["Editor.WatchPathHint"] = "notes.txt, or a folder",
        ["Editor.WatchChange"] = "Change :",
        ["Editor.WatchFilter"] = "Names in the folder :",
        ["Editor.WatchSubfolders"] = "Include the folders inside it",
        ["Editor.WatchNote"] = "The macro runs once for each change. The events of one save "
            + "arrive together and count as one.",
        ["Editor.ProcessName"] = "Program :",
        ["Editor.ProcessNameHint"] = "notepad, or chrome — the .exe is not needed",
        ["Editor.ProcessWhen"] = "When :",
        ["Editor.ProcessNote"] = "The macro runs once each time the program starts or stops. "
            + "A program that is already open when the system is switched on is not a start.",
        ["Editor.WindowLookup"] = "Match by :",
        ["Editor.WindowValue"] = "Window :",
        ["Editor.WindowValueHint"] = "part of the title",
        ["Editor.WindowWhen"] = "When :",
        ["Editor.WindowNote"] = "The open windows are looked at twice a second, so a window is "
            + "noticed about half a second after it arrives. A window open when the system is "
            + "switched on has not just appeared.",
        ["Editor.IdleSeconds"] = "Left alone for :",
        ["Editor.IdleNote"] = "The macro runs once when the machine has gone this long without a "
            + "key press, a mouse move or a click, and again after the next quiet spell. What a "
            + "macro does itself counts as using the machine.",

        // ----------------------------------------------------------- colour picker
        ["Picker.Title"] = "Color Picker",
        ["Picker.MoveHint"] = "Move the pointer onto the target.",
        ["Picker.ConfirmHint"] = "Click, or press Enter, to take the color. Arrow keys move the "
                                 + "pointer a pixel (hold Shift for ten). Esc cancels.",
        ["Picker.Position"] = "{0}, {1}",
        ["Region.Title"] = "Pick a region",
        ["Region.Hint"] = "Drag the rectangle, then press Enter or click inside it. Esc cancels.",
        ["Region.Drag"] = "Drag a rectangle over what the macro should look at",
        ["Region.Size"] = "x {0}  y {1}   {2} × {3}",
        ["Add.PickRegion"] = "Pick region",
        ["Add.PickRegionHint"] = "Drag a rectangle on the screen to fill these fields.",

        // ------------------------------------------------------- pictures and windows
        ["Add.BrowseImage"] = "Browse…",
        ["Add.BrowseImageHint"] = "Use a picture file that is already on disk.",
        ["Add.BrowseImageTitle"] = "Choose a picture",
        ["Add.ImageFilter"] = "Pictures",
        ["Add.CaptureImage"] = "Capture…",
        ["Add.CaptureImageHint"] = "Drag a rectangle on the screen and keep it as a picture in "
                                   + "the macro project.",
        ["Add.ImageFailed"] = "That part of the screen could not be saved as a picture.",
        ["Add.ClearImage"] = "Clear",
        ["Add.ClearImageHint"] = "Forget the picture this step points at.",
        ["Add.PickWindow"] = "Pick window…",
        ["Add.PickWindowHint"] = "Choose one of the windows that are open now.",
        ["WindowPicker.Title"] = "Pick a window",
        ["WindowPicker.Filter"] = "Filter by title or program",
        ["WindowPicker.Refresh"] = "Refresh",
        ["WindowPicker.RefreshHint"] = "Look at the open windows again.",
        ["WindowPicker.Empty"] = "No open windows were found.",
        ["WindowPicker.None"] = "No window matches what you typed.",
        ["WindowPicker.Minimized"] = "minimized",
        ["WindowPicker.Maximized"] = "maximized",
        ["WindowPicker.Normal"] = "normal",
        ["WindowPicker.Size"] = "{0} × {1}",
        ["WindowPicker.Choose"] = "Use this window",
        ["WindowPicker.Hint"] = "Only part of the title is stored, so the macro still finds the "
                                + "window when the document name changes.",
        ["Add.PickElement"] = "Pick element…",
        ["Add.PickElementHint"] = "Point at a control on screen and click it to write its selector.",
        ["Element.Title"] = "Pick an element",
        ["Element.Empty"] = "No control to pick up here.",
        ["Element.Unknown"] = "Control",
        ["Element.Named"] = "name \"{0}\"",
        ["Element.Id"] = "id {0}",
        ["Element.InWindow"] = "in {0}",
        ["Editor.PickedPosition"] = "Cursor position captured: {0}, {1}",
        ["Editor.PickedColor"] = "Color captured: {0}",
        ["Editor.PickFailed"] = "That point could not be read from the screen.",
        ["Editor.RecordActions"] = "Record Actions",
        ["Editor.PositionCapture"] = "Mouse Position Capture :",
        ["Editor.MouseMovement"] = "Mouse Movement",
        ["Editor.MouseButtons"] = "Mouse Buttons",
        ["Editor.KeyboardKeys"] = "Keyboard Keys",
        ["Editor.Delays"] = "Wait Time/Delays",
        ["Editor.IgnoreInjected"] = "Ignore Other Programs' Input",
        ["Editor.Tip.IgnoreInjected"] = "Leave out input the system marks as injected, so a macro "
                                        + "never records its own playback. Turn this off to record "
                                        + "through a remote session or a virtual machine.",
        ["Editor.IgnoreDelays"] = "Ignore delays less than:",
        ["Editor.Milliseconds"] = "Milliseconds",
        ["Editor.Record"] = "Record",
        ["Editor.StopRecording"] = "Stop Recording",
        ["Editor.RecordIdle"] = "Press Ctrl + F10 or click Record to start",
        ["Editor.RecordActive"] = "Recording — {0} captured, Escape is recorded like any other "
                                  + "key. Press Ctrl + F10 to stop",
        ["Editor.RecordFailed"] = "Recording could not start. Another program may be holding the "
                                  + "keyboard or mouse hook.",
        ["Editor.RecordEmpty"] = "The recording caught nothing, which usually means nothing was done "
                                 + "while it ran. Note that the system marks input sent by another "
                                 + "program — a remote session, a virtual machine, an automation tool "
                                 + "— as injected, and that input is left out on purpose so a macro "
                                 + "never records its own playback. If you are working through a "
                                 + "remote connection, turn off \"Ignore Other Programs' Input\" in the "
                                 + "Record Actions panel and try again.",
        ["Editor.Save"] = "Save",
        ["Editor.ActionEditor"] = "Action Editor",
        ["Editor.JsonTree"] = "JSON Tree",
        ["Editor.NoSteps"] = "No steps yet.",
        ["Editor.StepDisabled"] = "skipped",
        // The two ends of a block. They are what makes "inside the loop" and "after the loop"
        // two different places on the list.
        ["Editor.BlockEnd"] = "end of {0}",
        ["Editor.Fold"] = "Fold the steps inside",
        ["Editor.Unfold"] = "Show the steps inside",
        ["Editor.AddInside"] = "Add a sub-step at the end of this list",
        ["Editor.NoStepsHint"] = "Use Add new action above to pick an action and fill in its parameters.",
        ["Editor.UnsavedTitle"] = "Unsaved changes",
        ["Editor.ClearTitle"] = "Clear all steps",
        ["Editor.ClearMessage"] = "Remove all {0} steps? This cannot be undone.",
        ["Editor.Clear"] = "Clear",
        ["Editor.Tip.SetKey"] = "Choose the key that starts this macro",
        ["Editor.Tip.Save"] = "Save this macro and close the editor",
        ["Editor.Tip.Record"] = "Start or stop recording what you do on screen (Ctrl + F10)",
        ["Editor.UnsavedMessage"] = "This macro has changes that are not saved yet.",
        ["Editor.Discard"] = "Discard",
        ["Editor.DeleteTitle"] = "Delete macro",
        ["Editor.DeleteMessage"] = "Delete '{0}'? This cannot be undone.",
        ["Editor.Delete"] = "Delete",

        // Shown under a step that carries settings worth seeing without opening its dialog.
        ["Editor.Meta.Retry"] = "retry ×{0}",
        ["Editor.Meta.RetryDoubling"] = "retry ×{0}, backing off",
        ["Editor.Meta.RetryJitter"] = "retry ×{0}, at random intervals",
        ["Editor.Meta.Timeout"] = "times out after {0}",
        ["Editor.Meta.Pauses"] = "pauses {0} before, {1} after",
        ["Editor.JitterDetail"] = "±{0}%",
        ["Editor.Meta.OnErrorContinue"] = "carries on when it fails",
        ["Editor.Meta.OnErrorNextIteration"] = "starts the next round when it fails",
        ["Editor.Meta.OnErrorAsk"] = "asks when it fails",

        // What the editor can tell is wrong before the macro runs. Only what the steps
        // themselves decide is called out here; anything that needs a run stays unsaid.
        ["Editor.ProblemSummary"] = "{0} step(s) the editor is not happy with.",
        ["Editor.ProblemMark"] = "The editor has something to say about this step",
        ["Editor.Problem.BreakOutsideLoop"] = "This break is not inside a loop, so there is nothing to leave.",
        ["Editor.Problem.ContinueOutsideLoop"] = "This continue is not inside a loop, so there is no next round to start.",
        ["Editor.Problem.NoMacro"] = "This step does not say which macro to run.",
        ["Editor.Problem.MacroNotFound"] = "There is no macro called \"{0}\" in this project.",
        ["Editor.Problem.UndefinedVariable"] = "Nothing defines \"${0}\", so it reads as nothing.",

        ["Trigger.Keys"] = "Keystrokes / Button Inputs",
        ["Trigger.Color"] = "Color / Pixel Changes",
        ["Trigger.Timer"] = "Timer / Schedule",
        ["Trigger.File"] = "File / Folder Changes",
        ["Trigger.Process"] = "Program Started / Stopped",
        ["Trigger.Window"] = "Window Appears / Goes Away",
        ["Trigger.Idle"] = "Machine Idle",
        ["Idle.Summary"] = "After {0} s of no input",
        ["Schedule.Interval"] = "At an Interval",
        ["Schedule.Daily"] = "Every Day at a Time",
        ["Schedule.Unit.Seconds"] = "seconds",
        ["Schedule.Unit.Minutes"] = "minutes",
        ["Schedule.Unit.Hours"] = "hours",
        ["Schedule.IntervalSummary"] = "Every {0} {1}",
        ["Schedule.DailySummary"] = "Every day at {0}",
        ["Schedule.DailyUnset"] = "Every day (no time set)",
        ["FileChange.Any"] = "Any change",
        ["FileChange.Created"] = "Created",
        ["FileChange.Changed"] = "Changed",
        ["FileChange.Deleted"] = "Deleted or renamed",
        ["ProcessChange.Started"] = "Started",
        ["ProcessChange.Stopped"] = "Stopped",
        ["ProcessChange.Any"] = "Started or stopped",
        ["WindowChange.Appeared"] = "Appears",
        ["WindowChange.Disappeared"] = "Goes away",
        ["WindowChange.Any"] = "Either",
        ["WindowLookup.Title"] = "Title",
        ["WindowLookup.Process"] = "Program",
        ["WindowLookup.ClassName"] = "Window class",
        ["Loop.Toggle"] = "Until Key Pressed Again (Toggle)",
        ["Loop.Hold"] = "While Holding Key (Hold)",
        ["Loop.Press"] = "Once, When Key Pressed (Press)",
        ["Loop.Release"] = "Once, When Key Released (Release)",
        ["Position.Current"] = "Save Current Position",
        ["Position.Differences"] = "Save Position Differences",
        ["ColorMatch.Matches"] = "Color Matches",
        ["ColorMatch.NotMatches"] = "Color Not Matches",

        ["Palette.Add"] = "Add new action (Insert)",
        ["Palette.Undo"] = "Undo the last change (Ctrl + Z)",
        ["Palette.Redo"] = "Redo the change that was undone (Ctrl + Y)",
        ["Palette.Edit"] = "Edit the selected step (F2 or double-click)",
        ["Palette.ToggleEnabled"] = "Turn the selected steps on or off (Ctrl + E)",
        ["Palette.Copy"] = "Copy the selected steps (Ctrl + C)",
        ["Palette.Cut"] = "Cut the selected steps (Ctrl + X)",
        ["Palette.Paste"] = "Paste below the selected step (Ctrl + V)",
        ["Palette.Delete"] = "Delete the selected steps (Del)",
        ["Palette.Group"] = "Group the selected steps into one step that runs them in order (Ctrl + G)",
        ["Palette.Run"] = "Run and debug this macro (F5)",
        ["Palette.MoveUp"] = "Move the selected steps up (Ctrl + Up)",
        ["Palette.MoveDown"] = "Move the selected steps down (Ctrl + Down)",
        ["Palette.Clear"] = "Clear all steps",
        ["Palette.AdjustDelays"] = "Playback speed — scale waits, holds and typing",
        ["Palette.RunMacro"] = "Run another macro — add a call to another macro in this project",
        ["Speed.Title"] = "Playback speed",
        ["Speed.Explanation"] = "Scales this macro's waits and pacing by a factor. It applies only while "
            + "the macro runs, so the steps keep the numbers you wrote — ×1 is exactly as written.",
        ["Speed.Summary"] = "{0} waits: about {1} → {2}",
        ["Speed.Detail"] = "Also scales {0} loop intervals and {1} key or mouse timings.",
        ["Speed.NoWaits"] = "This macro has no waits yet, so the factor only affects pacing while it runs.",

        ["Speed.Seconds"] = "{0} s",
        ["Speed.Milliseconds"] = "{0} ms",

        // ---------------------------------------------------------- add action
        ["Add.Title"] = "Add Action",
        ["Add.EditTitle"] = "Edit Action",
        ["Add.SelectAction"] = "Select Action",
        ["Add.SharedPositionHint"] = "Press Alt + X to take the pointer's position for both fields.",
        ["Add.NoSelection"] = "No action selected",
        ["Add.SelectHint"] = "Pick an action from the list to see the parameters it needs.",
        ["Add.Parameters"] = "Parameters",
        ["Add.JsonNode"] = "JSON Node",
        ["Add.JsonPlaceholder"] = "// Select an action to preview its JSON node",
        ["Add.NoParameters"] = "This action takes no parameters.",
        ["Add.Cancel"] = "Cancel",
        ["Add.Commit"] = "Add Step",
        ["Add.CommitEdit"] = "Save Step",
        ["Add.SelectFirst"] = "Select an action first.",
        ["Add.StillNeeded"] = "Still needed: {0}",
        ["Add.NestedCondition"] = "Choose condition",
        ["Add.NestedAddCondition"] = "Add condition",
        ["Add.Case"] = "Add case",
        ["Add.NestedEdit"] = "Edit",
        ["Add.StepsInList"] = "The steps inside a block are put in order in the editor's list: {0}",
        ["Add.AddStepToBlock"] = "Add a sub-step",
        ["Add.AddStepToBlockHint"] = "Appends a step to the end of this block. Their order and "
            + "deleting them are done in the editor's list, where the shape of the macro shows.",
        ["Add.ExpressionValid"] = "Expression is valid",
        ["Add.ExpressionResult"] = "= {0}",
        ["Add.FormulaUse"] = "Write this as an expression, for example $match.x",
        ["Add.FormulaBack"] = "Go back to a plain number",
        ["Add.FormulaLocked"] = "The expression reads a variable, so it cannot become a plain number",
        ["Add.FormulaMilliseconds"] = "An expression is counted in milliseconds.",
        ["Add.Unit.ms"] = "ms",
        ["Add.Unit.s"] = "s",
        ["Add.Unit.min"] = "min",
        ["Add.Unit.h"] = "h",
        ["Add.AdvancedShow"] = "Advanced options ({0})",
        ["Add.AdvancedHide"] = "Hide advanced options",
        ["Add.ActionGroup"] = "{0} ({1})",
        ["Add.RecentlyUsed"] = "Recently used",
        ["Add.Blocks"] = "Blocks",
        ["Add.BlocksNote"] = "These are the shapes a task is built from: what the run does when it "
            + "reaches them. The trigger's \"repeat while held\" is a separate setting: it starts "
            + "the whole macro over again.",
        ["Add.SearchAction"] = "Search: keys, names, or what an action does",
        ["Add.ChangeAction"] = "Change",
        ["Add.NoActionFound"] = "Nothing in the catalogue matches that.",
        ["Add.Category.Control"] = "Control flow",
        ["Add.Category.File"] = "Files",
        ["Add.Category.Clipboard"] = "Clipboard",
        ["Add.Category.Process"] = "Programs and commands",
        ["Add.Category.System"] = "System",
        ["Add.Category.Window"] = "Windows",
        ["Add.Category.Input"] = "Keyboard and mouse",
        ["Add.Category.Vision"] = "Screen and pictures",
        ["Add.Category.Ocr"] = "Text on screen",
        ["Add.Category.Uia"] = "Interface elements",
        ["Add.Category.Script"] = "Scripts",
        ["Add.Category.Condition"] = "Conditions",
        ["Add.JitterSign"] = "±",
        ["Add.JitterUnit"] = "%",
        ["Add.JitterHint"] = "How far the time may move each run, as a percentage of it.",
        ["Add.JitterRange"] = "Each run: {0} to {1}",
        ["Add.FormulaPlaceholder"] = "$match.x or $count + 1",
        ["Add.StepSettings"] = "Step settings",
        ["Add.BlockSettings"] = "These settings belong to the whole block: a failure inside it that "
            + "no step handled counts as this block failing.",
        ["Add.StepComment"] = "Comment",
        ["Add.StepCommentHint"] = "A note shown under the step in the list",
        ["Add.StepTimeout"] = "Timeout",
        ["Add.StepTimeoutHint"] = "Only the step's own running time is counted: the pauses before "
            + "and after it and the waits between retries are not. 0 means no limit. A block's "
            + "timeout covers the whole block, so the waiting its sub-steps do is included.",
        ["Add.StepRetry"] = "Retries",
        ["Add.StepRetryDelay"] = "Retry delay",
        ["Add.StepOnError"] = "When it fails",

        ["Add.StepBackoff"] = "Pause between retries",
        ["Add.StepBackoffHint"] = "A doubling pause backs off further with every attempt, which is "
            + "what a slow program needs; a random one varies each wait between 0.5x and 1.5x so "
            + "the retries cannot march in step. Neither grows past 46 hours.",
        ["Add.Backoff.Fixed"] = "The same every time",
        ["Add.Backoff.Doubling"] = "Double each attempt",
        ["Add.Backoff.Jitter"] = "Half to one and a half times, at random",
        ["Add.StepRetryPlanNone"] = "Not retried: the first failure goes straight to "
            + "the rule beside it.",
        ["Add.StepRetryPlanFixed"] = "Tried {0} more time(s), waiting {1} each time.",
        ["Add.StepRetryPlanGrowing"] = "Tried {0} more time(s), waiting {1}.",
        ["Add.StepRetryPlanRandom"] = "Tried {0} more time(s), each wait somewhere between {1} and {2}.",
        ["Add.StepDelayBefore"] = "Delay before",
        ["Add.StepDelayAfter"] = "Delay after",
        ["Add.StepEnabled"] = "Run this step",
        ["Add.OnError.Stop"] = "Stop the macro",
        ["Add.OnError.Continue"] = "Carry on with the next step",
        ["Add.OnError.NextIteration"] = "Skip to the next loop round",
        ["Add.OnError.AskUser"] = "Ask me: retry, skip or stop",
        ["Expr.Error.Syntax"] = "Expression syntax error: {0}",
        ["Expr.Error.UnknownVariable"] = "The expression uses a variable that is not defined: {0}",
        ["Expr.Error.UnknownFunction"] = "The expression uses a function that does not exist: {0}",
        ["Expr.Error.ArgumentCount"] = "Wrong number of arguments: {0}",
        ["Expr.Error.TypeMismatch"] = "Value has the wrong kind: {0}",
        ["Expr.Error.DivideByZero"] = "Cannot divide by zero",
        ["Expr.Error.IndexOutOfRange"] = "List index is outside the list: {0}",

        // ----------------------------------------------------- expression builder
        ["Add.ExpressionBuilder"] = "Operators…",
        ["Add.ExpressionBuilderHint"] = "Open the expression builder: every operator is a button "
            + "and the variables in scope are a list, so nothing has to be typed from memory.",
        ["ExprBuilder.Title"] = "Expression builder",
        ["ExprBuilder.Help"] = "Click an operator or a variable to add it at the cursor, or edit "
            + "the expression directly. The line under the box shows what it comes to.",
        ["ExprBuilder.Operators"] = "Operators",
        ["ExprBuilder.Expression"] = "Expression",
        ["ExprBuilder.Variables"] = "Insert variable",
        ["ExprBuilder.Insert"] = "Insert",
        ["ExprBuilder.Placeholder"] = "$count + 1",
        ["Expr.Op.Add"] = "Add numbers, or join two pieces of text",
        ["Expr.Op.Subtract"] = "Subtract the right side from the left",
        ["Expr.Op.Multiply"] = "Multiply the two sides",
        ["Expr.Op.Divide"] = "Divide the left side by the right",
        ["Expr.Op.Remainder"] = "What is left over after dividing",
        ["Expr.Op.Equals"] = "The two sides are the same",
        ["Expr.Op.NotEquals"] = "The two sides are different",
        ["Expr.Op.Greater"] = "The left side is greater",
        ["Expr.Op.GreaterOrEqual"] = "The left side is greater or equal",
        ["Expr.Op.Less"] = "The left side is smaller",
        ["Expr.Op.LessOrEqual"] = "The left side is smaller or equal",
        ["Expr.Op.And"] = "Both sides must be true",
        ["Expr.Op.Or"] = "Either side may be true",
        ["Expr.Op.Not"] = "Turn true into false and false into true",
        ["Expr.Op.Group"] = "Put part of the expression in brackets",
        ["Expr.Op.List"] = "Write a list of values",
        ["Expr.Op.Text"] = "Write text between the quotation marks",

        // ------------------------------------------------------------ settings
        ["Settings.Title"] = "Settings",
        ["Settings.Language"] = "Language",
        ["Settings.LanguageHint"] = "Applies immediately to every window.",
        ["Settings.FailureScreenshot"] = "Save a picture of the screen when a run fails",
        ["Settings.FailureScreenshotHint"] =
            "Kept in the logs folder beside the program. Nothing is written while a macro runs well.",
        ["Settings.Note"] = "Action names and parameter text use the selected language when a window is opened.",
        ["Settings.Close"] = "Close",

        ["Confirm.Cancel"] = "Cancel",
        ["Common.Ok"] = "OK",
        ["Common.Minimize"] = "Minimize",
        ["Common.Close"] = "Close",
        ["Common.OptionalSuffix"] = "{0} (optional)",
        ["Common.StepCount"] = "{0} step(s)",

        // ------------------------------------------------------------ macro package
        ["Main.OpenProjectTitle"] = "Open Macro Project",
        ["Main.ImportProjectTitle"] = "Import Macro Project",
        ["Main.SaveProjectTitle"] = "Save Macro Project",
        ["Main.CloseAllTitle"] = "Close all macros",
        ["Main.CloseAllMessage"] = "Remove every macro from the list? The saved package is not changed.",
        ["Package.Filter"] = "Viktor Macro Package",
        ["Package.OpenFailed"] = "This file could not be opened",
        ["Package.SaveFailed"] = "This file could not be saved",

        // -------------------------------------------------------- variable center
        ["Variable.Title"] = "Variable Center",
        ["Variable.Note"] = "A macro can read system and global variables, and change a global one. "
            + "Only this window creates globals. A local variable belongs to the macro that created it "
            + "and cannot be read by the other macros in the list.",
        ["Variable.System"] = "System Variables",
        ["Variable.SystemHint"] = "Provided by Viktor and read live here. A macro can read them but never change them.",
        ["Variable.Globals"] = "Global Variables",
        ["Variable.GlobalsHint"] = "Shared by every macro. Create and edit them here; a macro may only change their values. "
            + "The default value is what a macro sees before it changes anything.",
        ["Variable.Locals"] = "Macro Variables",
        ["Variable.LocalsHint"] = "Only the macros in the macro list are shown. A macro sees its own local variables "
            + "only — the other macros cannot read them. They hold a value while their macro runs.",
        ["Variable.Tab.Current"] = "Variables in use",
        ["Variable.Tab.Local"] = "Local variables",
        ["Variable.Tab.Global"] = "Global variables",
        ["Variable.Tab.System"] = "System variables",
        ["Variable.CurrentHint"] = "The variables the macros in the list actually use, with the scope and the "
            + "macros using them marked. System variables stay hidden unless you ask for them.",
        ["Variable.ShowSystem"] = "Show system variables",
        ["Variable.NoneUsed"] = "No macro uses a variable yet.",
        ["Variable.UnknownHint"] = "A macro names this variable, but no step defines it.",
        ["Variable.Scope"] = "Scope",
        ["Variable.Owner"] = "Macro",
        ["Variable.UsedBy"] = "Used by",
        ["Variable.NoGlobals"] = "No global variables yet. Add one below.",
        ["Variable.NoLocals"] = "No macro has created a local variable yet.",
        ["Variable.Name"] = "Name",
        ["Variable.Type"] = "Type",
        ["Variable.Value"] = "Current value",
        ["Variable.Refresh"] = "Refresh",
        ["Variable.NotSet"] = "not set",
        ["Variable.Default"] = "Default",
        ["Variable.Description"] = "Description",
        ["Variable.Add"] = "Add",
        ["Variable.Close"] = "Close",
        ["Variable.LocalDescription"] = "Created by this macro.",
        ["Variable.NameIsSystem"] = "A system variable is already called \"{0}\".",
        ["Variable.NameTaken"] = "A global variable called \"{0}\" already exists.",
        ["Variable.Scope.System"] = "System",
        ["Variable.Scope.Global"] = "Global",
        ["Variable.Scope.Local"] = "Local",
        ["Variable.Scope.Unknown"] = "not defined",
        ["Variable.Type.text"] = "Text",
        ["Variable.Type.number"] = "Number",
        ["Variable.Type.bool"] = "Boolean",
        ["Variable.Type.color"] = "Colour",
        ["Variable.Type.date"] = "Date",
        ["Variable.Type.list"] = "List",
        ["Variable.ListPreview"] = "{0} item(s): {1}",
        ["Variable.EmptyList"] = "Empty list",
        ["Variable.InvalidDefault"] = "The starting value cannot be read as a list",

        // ------------------------------------------------------------ run and debug
        ["Run.Title"] = "Run and Debug",
        ["Run.Run"] = "Run",
        ["Run.Step"] = "Step",
        ["Run.Continue"] = "Continue",
        ["Run.Stop"] = "Stop",
        ["Run.Close"] = "Close",
        ["Run.Steps"] = "Steps",
        ["Run.Log"] = "Log",
        ["Run.Variables"] = "Variables",
        ["Run.Empty"] = "This macro has no steps yet.",
        ["Run.Ready"] = "Ready",
        ["Run.Running"] = "Running\u2026",
        ["Run.Paused"] = "Paused before the next step",
        ["Run.Start"] = "Run started with {0} step(s).",
        ["Run.Finished"] = "Finished. {0} step(s) ran.",
        ["Run.Stopped"] = "Stopped. {0} step(s) ran.",
        ["Run.Aborted"] = "Aborted. {0} step(s) ran.",
        ["Run.FailurePicture"] = "Saved a picture of the screen to {0}",
        ["Run.FailurePictureFailed"] = "Could not save a picture of the screen: {0}",
        ["Run.Skipped"] = "Skipped: the step is turned off",
        ["Run.Retry"] = "Retry {0}",
        ["Run.StopRequested"] = "The macro asked to stop. {0}",
        ["Run.Set"] = "{0} = {1}",
        ["Run.Message"] = "{0}",
        ["Run.Unsupported"] = "The engine does not support this action yet: {0}",
        ["Run.ConditionUnavailable"] = "This condition needs the device layer, which is not ready: {0}",
        ["Run.BadExpression"] = "The value is not a valid expression: {0}",
        ["Run.BadList"] = "The value is not a list: {0}",
        ["Run.NotAList"] = "{0} is not a list",
        ["Run.IndexOutOfRange"] = "That position is outside the list: {0}",
        ["Run.GlobalMustExist"] = "Only the Variable Center creates shared variables, and {0} does not exist",
        ["Run.MissingVariable"] = "No variable name was given",
        ["Run.DivideByZero"] = "Cannot divide by zero.",
        ["Run.Failed"] = "The step failed.",
        ["Run.Timeout"] = "The step took longer than the {0} ms it was allowed.",
        ["Run.Ask"] = "Step \"{0}\" failed. Choose what to do next.",
        ["Run.AskRetry"] = "Retry",
        ["Run.AskSkip"] = "Skip it",
        ["Run.AskStop"] = "Stop",
        ["Run.AskTitle"] = "A step failed",
        ["Run.AskComment"] = "Your note on this step: {0}",
        ["Run.NoVariables"] = "This macro does not use any variables yet.",
        ["Run.NoDevice"] = "This machine cannot do that: {0} is not connected.",
        ["Run.UnknownKey"] = "Viktor does not recognise this key name: {0}",
        ["Run.EmptyChord"] = "The hotkey has no keys in it.",
        ["Run.PixelOutsideScreen"] = "That pixel is not on the screen: {0}",
        ["Run.EmptyRegion"] = "That is not a usable screen region: {0}",
        ["Run.CaptureFailed"] = "The screen region could not be copied: {0}",
        ["Run.BadRegion"] = "A search region reads as x,y,width,height: {0}",
        ["Run.BadPoints"] = "Every point of a colour comparison reads as x,y,#RRGGBB: {0}",
        ["Run.BadPattern"] = "That is not a usable match pattern: {0}",
        ["Run.Capture"] = "Captured into {0}: {1}",
        ["Run.SawColor"] = "The pixel shows {0}.",
        ["Run.WaitColorTimeout"] = "The pixel never showed {0}.",
        ["Run.ImageFound"] = "Found, saved to {0}: {1}",
        ["Run.ImageMissing"] = "Not on screen, so {0} was emptied.",
        ["Run.ImageNotFound"] = "Never found the reference image: {0}",
        ["Run.ClickedImage"] = "Clicked the match at {0},{1}",
        ["Run.MissingImage"] = "The reference image could not be read: {0}",
        ["Run.UnknownCondition"] = "Viktor does not know this condition: {0}",
        ["Run.TextFound"] = "Found the text, saved to {0}: {1}",
        ["Run.TextMissing"] = "The text is not on screen, so {0} was emptied.",
        ["Run.TextNotFound"] = "Never found the text: {0}",
        ["Run.ClickedText"] = "Clicked \"{0}\" at {1}",
        ["Run.ElementFound"] = "The element is there: {0}",
        ["Run.ElementNotFound"] = "The element never appeared: {0}",
        ["Run.ElementNotClickable"] = "The element could not be clicked: {0}",
        ["Run.ElementNotWritable"] = "The element could not be filled in: {0}",
        ["Run.ElementFilled"] = "Filled in {0} with \"{1}\"",
        ["Run.ClickedElement"] = "Clicked the element: {0}",
        ["Run.ElementWhere"] = "Found the element, saved to {0}: {1}",
        ["Run.ElementMissing"] = "The element is not there, so {0} was emptied.",
        ["Run.SelectedItem"] = "Picked \"{1}\" in {0}",
        ["Run.ItemNotFound"] = "There is no such entry to pick: {0}",
        ["Run.MissingItem"] = "This step does not say which entry to pick.",
        ["Run.ElementNotSelectable"] = "Nothing in this element can be picked: {0}",
        ["Run.ElementChecked"] = "Changed the checked state of {0}",
        ["Run.ElementNotCheckable"] = "This element is not a check box: {0}",
        ["Run.ElementExpanded"] = "Changed the expanded state of {0}",
        ["Run.ElementNotExpandable"] = "This element cannot be opened or closed: {0}",
        ["Run.ScrolledElement"] = "Scrolled into view: {0}",
        ["Run.ElementNotScrollable"] = "This element cannot be scrolled into view: {0}",
        ["Run.ReadTable"] = "Read {1} rows into {0}.",
        ["Run.ElementNotATable"] = "This element is not a table: {0}",
        ["Run.RanScript"] = "Ran the {0} script; {1} characters came back.",
        ["Run.ScriptFailed"] = "The script stopped with exit code {0}",
        ["Run.ScriptNotTidied"] = "The script file was already gone: {0}",
        ["Run.MissingScript"] = "This step has no script to run.",
        ["Run.UnknownInterpreter"] = "Viktor does not know this interpreter: {0}",
        ["Run.MissingInterpreter"] = "This step does not say which program runs the script.",
        ["Run.MissingScriptExtension"] = "This step does not say which file ending the script needs.",
        ["Run.WaitedFor"] = "The wait held after {0} ms: {1}.",
        ["Run.WaitGaveUp"] = "Gave up after {0} ms, so the macro carried on: {1} never held.",
        ["Run.WaitTimeout"] = "The wait ran out: {0} never held.",
        ["Run.MissingCondition"] = "This wait has no condition to wait for.",
        ["Run.WindowNotFound"] = "No window matches that title: {0}",
        ["Run.FocusedWindow"] = "Brought the window to the front: {0}",
        ["Run.EmptySelector"] = "No element selector was given.",
        ["Run.MissingWindow"] = "No window title was given: {0}",
        ["Run.MissingTargetWindow"] = "Background input needs a window to post its messages at; fill in the target window title.",
        ["Run.ReadFile"] = "Read {0}, {1} characters long.",
        ["Run.WroteFile"] = "Wrote {0}, {1} characters long.",
        ["Run.AppendedFile"] = "Added to {0}, which is now {1} characters long.",
        ["Run.DeletedFile"] = "Removed {0}.",
        ["Run.CopiedFile"] = "Copied {0} to {1}.",
        ["Run.MovedFile"] = "Moved {0} to {1}.",
        ["Run.MadeFolder"] = "Made the folder {0}.",
        ["Run.RemovedFolder"] = "Removed the folder {0}.",
        ["Run.Unzipped"] = "Unpacked {0} into {1}.",
        ["Run.ListedFiles"] = "Found {1} files in {0}.",
        ["Run.SavedVariables"] = "Saved {1} variables to {0}.",
        ["Run.LoadedVariables"] = "Read {1} variables back from {0}.",
        ["Run.BadJson"] = "The file is not readable as JSON: {0}",
        ["Run.BadJsonPath"] = "Viktor cannot read this path into the JSON: {0}",
        ["Run.MissingJsonPath"] = "There is nothing at that position in the JSON.",
        ["Run.FileNotFound"] = "There is no such file: {0}",
        ["Run.FolderNotFound"] = "There is no such folder: {0}",
        ["Run.FileExists"] = "That file is already there, and Viktor was told not to replace it: {0}",
        ["Run.MissingPath"] = "No file path was given.",
        ["Run.FileFailed"] = "The file could not be read or written: {0}",
        ["Run.BadZip"] = "That file is not a zip archive, or it is incomplete: {0}",
        ["Run.CopiedToClipboard"] = "Copied {0} characters to the clipboard.",
        ["Run.ReadClipboard"] = "Read the clipboard into {0}, {1} characters long.",
        ["Run.ClearedClipboard"] = "Emptied the clipboard.",
        ["Run.ReadClipboardImage"] = "Took the picture on the clipboard into {0} ({1}).",
        ["Run.NoClipboardImage"] = "There is no picture on the clipboard, so {0} was emptied.",
        ["Run.CopiedImageToClipboard"] = "Copied a {0} picture to the clipboard.",
        ["Run.ReadClipboardFiles"] = "Took {1} file(s) off the clipboard into {0}.",
        ["Run.CopiedFilesToClipboard"] = "Put {0} file(s) on the clipboard.",
        ["Run.ClipboardChanged"] = "The clipboard changed; {0} now holds {1} characters.",
        ["Run.CopiedFromWindow"] = "Copied the selection into {0}, {1} characters long.",
        ["Run.PastedText"] = "Put the text on the clipboard and pasted it.",
        ["Run.Pasted"] = "Pressed the paste shortcut.",
        ["Run.ClipboardTimeout"] = "The clipboard did not change in time.",
        ["Run.ClipboardBusy"] = "Another program is holding the clipboard.",
        ["Run.ClipboardWriteFailed"] = "The clipboard would not take the text.",
        ["Run.StartedProgram"] = "Started {0}, process id {1}.",
        ["Run.ProgramFound"] = "{0} is running, process id {1}.",
        ["Run.ProgramNotFound"] = "{0} never started.",
        ["Run.ProcessExited"] = "Process {0} finished with code {1}.",
        ["Run.ProcessTimeout"] = "Process {0} did not finish in time.",
        ["Run.BadProcessId"] = "That is not a process id: {0}",
        ["Run.ListedPrograms"] = "Found {0} running programs.",
        ["Run.StoppedProgram"] = "Stopped {0}; {1} processes closed.",
        ["Run.CommandFinished"] = "{0} finished with code {1}.",
        ["Run.CommandStarted"] = "Running {0} and putting what it prints in the log.",
        ["Run.CommandOutput"] = "> {0}",
        ["Run.CommandError"] = "! {0}",
        ["Run.UnknownSystemField"] = "Viktor does not know this system field: {0}",
        ["Run.Power"] = "Asked the machine to {0}; warning {1} seconds.",
        ["Run.PowerRefused"] = "Windows would not do that to this machine.",
        ["Run.LockRefused"] = "Windows would not lock the screen.",
        ["Run.AbortRefused"] = "There was no shutdown counting down to call off.",
        ["Run.UnknownPowerAction"] = "Viktor does not know this power action: {0}",
        ["Run.Volume"] = "The volume is now {0}%.",
        ["Run.SoundOff"] = "The sound is switched off.",
        ["Run.SoundOn"] = "The sound is back on.",
        ["Run.AudioRefused"] = "Windows would not change the sound: {0}",
        ["Run.UnknownVolumeAction"] = "Viktor does not know this volume action: {0}",
        ["Run.NoForegroundWindow"] = "There is no window in front to do that to.",
        ["Run.NoImeContext"] = "The window in front has no input method to switch on or off; its "
            + "keyboard layout types keys as they are.",
        ["Run.ImeRefused"] = "Windows would not switch the input method {0}.",
        ["Run.LayoutNotFound"] = "No keyboard layout installed on this machine matches: {0}",
        ["Run.LayoutNotSwitched"] = "Windows asked the window in front to switch to {0} and it "
            + "never did.",
        ["Run.Brightness"] = "The screens are now at {0}% brightness.",
        ["Run.BrightnessRefused"] = "No screen would take that brightness setting.",
        ["Run.UnknownBrightnessAction"] = "Viktor does not know this brightness action: {0}",
        ["Run.UnknownInputMethodAction"] = "Viktor does not know this input method action: {0}",
        ["Run.MissingName"] = "No name was given.",
        ["Run.MissingProgram"] = "No program was named.",
        ["Run.ProgramFailed"] = "The program would not start or run: {0}",
        ["Run.ElevationRefused"] = "Windows was asked to start {0} as administrator and refused.",
        ["Run.ElevationNoEnvironment"] = "{0} cannot be started as administrator and with its own "
            + "environment variables at the same time.",
        ["Run.BadEnvironment"] = "This is not a NAME=value line: {0}",
        ["Run.CommandTimeout"] = "The command did not finish in time: {0}",
        ["Run.ActivatedWindow"] = "Brought \"{0}\" to the front.",
        ["Run.MinimizedWindow"] = "Minimized \"{0}\".",
        ["Run.MaximizedWindow"] = "Maximized \"{0}\".",
        ["Run.RestoredWindow"] = "Put \"{0}\" back to its normal size.",
        ["Run.MovedWindow"] = "Moved and resized \"{0}\".",
        ["Run.ClosedWindow"] = "Asked \"{0}\" to close.",
        ["Run.WindowAppeared"] = "The window appeared: {0}",
        ["Run.WindowTimeout"] = "No window with that title appeared: {0}",
        ["Run.WindowFailed"] = "The window would not do that: {0}",
        ["Run.ListedWindows"] = "Found {0} open windows.",
        ["Run.WindowBox"] = "{0} sits at {1}",
        ["Run.Speed"] = "Running at ×{0} the speed written in the steps.",
        ["Run.SpeedTip"] = "This macro is running at a speed other than the one written in its steps.",
        ["Run.CalledMacro"] = "Running \"{0}\": {1} steps.",
        ["Run.MacroNotFound"] = "There is no macro called \"{0}\" in this project.",
        ["Run.MacroTooDeep"] = "The macros call each other too many times over: {0}",
        ["Run.BadMacroArgument"] = "This is not a NAME=value line to pass to the macro: {0}",
        ["Run.BreakOutsideLoop"] = "A break ran with no loop to leave: this step is not inside one.",
        ["Run.ContinueOutsideLoop"] = "A continue ran with no loop to skip ahead in: this step is not inside one.",
        ["Run.DeviceFailed"] = "A component outside Viktor failed: {0}",
        ["Run.Caught"] = "The attempt failed, so the catch steps are running.",
        ["Run.Finally"] = "Running the clean-up steps.",
        ["Add.SystemReadOnly"] = "\"{0}\" is a system variable, which a macro can only read.",
        ["Add.GlobalMustExist"] = "Global variable \"{0}\" does not exist. Create it in the Variable Center first.",
    };

    internal static readonly Dictionary<string, string> Chinese = new()
    {
        // ------------------------------------------------------------- main window
        ["Main.Title"] = "Viktor",
        ["Main.AdminBadge"] = "（管理员）",
        ["Main.File"] = "_文件",
        ["Main.Help"] = "_帮助",
        ["Main.OpenProject"] = "打开宏项目",
        ["Main.SaveProject"] = "保存宏项目",
        ["Main.SaveProjectAs"] = "宏项目另存为",
        ["Main.ImportProject"] = "导入宏项目",
        ["Main.OpenCurrentLocation"] = "打开当前宏所在位置",
        ["Main.ReloadCurrent"] = "重新加载当前宏",
        ["Main.OpenDirectory"] = "打开宏目录",
        ["Main.CloseAll"] = "全部关闭",
        ["Main.Settings"] = "设置",
        ["Main.WhatsNew"] = "更新内容",
        ["Main.Updates"] = "检查更新",
        ["Main.Feedback"] = "反馈",
        ["Main.GetStarted"] = "快速上手",
        ["Main.About"] = "关于",
        ["Main.SearchPlaceholder"] = "输入以搜索..",
        ["Main.EmptyTitle"] = "还没有宏。",
        ["Main.EmptyHint"] = "点击下方的“新建宏”创建第一个宏。",
        ["Main.EditTip"] = "编辑",
        ["Main.DeleteTip"] = "删除",
        ["Main.AddMacro"] = "新建宏",
        ["Main.SystemEnabled"] = "已启用",
        ["Main.SystemDisabled"] = "已停用",
        ["Main.SystemEnableHint"] = "按 Home 键启用",
        ["Main.SystemDisableHint"] = "按 Home 键停用",
        ["Main.MacroRunning"] = "运行中",
        ["Main.AlwaysOnTop"] = "窗口置顶",
        ["Main.AlwaysOnTopCancel"] = "取消置顶",

        // ----------------------------------------------------------- macro editor
        ["Editor.Title"] = "宏编辑器",
        ["Editor.NamePlaceholder"] = "给这个宏起个名字..",
        ["Editor.TriggerSettings"] = "触发设置",
        ["Editor.TriggerBy"] = "触发方式：",
        ["Editor.Loop"] = "循环：",
        ["Editor.BindKey"] = "触发 / 绑定按键：",
        ["Editor.NoKey"] = "未选择按键",
        ["Editor.SetKey"] = "设置按键",
        ["Editor.PressKey"] = "请按一个键…",
        ["Editor.When"] = "条件：",
        ["Editor.ColorPosition"] = "屏幕取色位置：",
        ["Editor.X"] = "X：",
        ["Editor.Y"] = "Y：",
        ["Editor.UseCursorPosition"] = "使用光标当前所在位置",
        ["Editor.TriggerOnce"] = "仅触发一次",
        ["Editor.HexColor"] = "输入十六进制颜色：",
        ["Editor.ColorTolerance"] = "颜色容差：",
        ["Editor.AltXHint"] = "按 Alt + X 记录光标当前位置",
        ["Editor.AltCHint"] = "按 Alt + C 记录光标处的屏幕颜色",
        ["Editor.PickColor"] = "从屏幕上拾取颜色",
        ["Editor.Schedule"] = "计划：",
        ["Editor.Interval"] = "每隔：",
        ["Editor.ScheduleTime"] = "时间：",
        ["Editor.ScheduleTimeHint"] = "HH:mm 或 HH:mm:ss",
        ["Editor.ScheduleNote"] = "定时触发的宏每次到点执行一遍，计时从启用系统时开始。",
        ["Editor.WatchPath"] = "文件或文件夹：",
        ["Editor.WatchPathHint"] = "notes.txt，或一个文件夹",
        ["Editor.WatchChange"] = "变化：",
        ["Editor.WatchFilter"] = "文件夹里匹配的名字：",
        ["Editor.WatchSubfolders"] = "包含里面的子文件夹",
        ["Editor.WatchNote"] = "每次变化执行一遍；同一次保存产生的多个事件会合并成一次。",
        ["Editor.ProcessName"] = "程序：",
        ["Editor.ProcessNameHint"] = "notepad、chrome，不用写 .exe",
        ["Editor.ProcessWhen"] = "时机：",
        ["Editor.ProcessNote"] = "程序每次启动或退出时执行一遍；启用系统时已在运行的程序不算启动。",
        ["Editor.WindowLookup"] = "匹配方式：",
        ["Editor.WindowValue"] = "窗口：",
        ["Editor.WindowValueHint"] = "标题的一部分",
        ["Editor.WindowWhen"] = "时机：",
        ["Editor.WindowNote"] = "每秒检查两次窗口列表，窗口出现后约半秒内会被检测到；"
            + "启用系统时已存在的窗口不算刚出现。",
        ["Editor.IdleSeconds"] = "空闲时间：",
        ["Editor.IdleNote"] = "机器持续这么久没有按键、移动鼠标或点击时执行一遍，之后每段安静的"
            + "时间各执行一遍；宏自身的动作也算使用机器。",

        // ----------------------------------------------------------- colour picker
        ["Picker.Title"] = "屏幕取色",
        ["Picker.MoveHint"] = "把鼠标移到要取色的位置。",
        ["Picker.ConfirmHint"] = "单击或按 Enter 取色；方向键可逐像素微调（按住 Shift 每次 10 像素），Esc 取消。",
        ["Picker.Position"] = "{0}, {1}",
        ["Region.Title"] = "框选区域",
        ["Region.Hint"] = "拖出矩形后按 Enter，或在矩形内单击确认；Esc 取消。",
        ["Region.Drag"] = "在屏幕上拖出宏需要看的区域",
        ["Region.Size"] = "x {0}  y {1}   宽 {2} × 高 {3}",
        ["Add.PickRegion"] = "框选区域",
        ["Add.PickRegionHint"] = "在屏幕上拖出一个矩形，自动填入这些字段。",

        // ------------------------------------------------------- pictures and windows
        ["Add.BrowseImage"] = "浏览…",
        ["Add.BrowseImageHint"] = "使用磁盘上已有的图片文件。",
        ["Add.BrowseImageTitle"] = "选择图片",
        ["Add.ImageFilter"] = "图片",
        ["Add.CaptureImage"] = "截屏…",
        ["Add.CaptureImageHint"] = "在屏幕上拖出一个矩形，把它作为图片保存到宏项目里。",
        ["Add.ImageFailed"] = "这块屏幕区域没能保存成图片。",
        ["Add.ClearImage"] = "清除",
        ["Add.ClearImageHint"] = "不再使用这个步骤指向的图片。",
        ["Add.PickWindow"] = "拾取窗口…",
        ["Add.PickWindowHint"] = "从当前打开的窗口里选一个。",
        ["WindowPicker.Title"] = "拾取窗口",
        ["WindowPicker.Filter"] = "按标题或程序筛选",
        ["WindowPicker.Refresh"] = "刷新",
        ["WindowPicker.RefreshHint"] = "重新读取当前打开的窗口。",
        ["WindowPicker.Empty"] = "没有找到打开的窗口。",
        ["WindowPicker.None"] = "没有匹配的窗口。",
        ["WindowPicker.Minimized"] = "已最小化",
        ["WindowPicker.Maximized"] = "已最大化",
        ["WindowPicker.Normal"] = "正常大小",
        ["WindowPicker.Size"] = "{0} × {1}",
        ["WindowPicker.Choose"] = "使用这个窗口",
        ["WindowPicker.Hint"] = "只保存标题的一部分，所以文档名变了以后宏仍然能找到这个窗口。",
        ["Add.PickElement"] = "拾取元素…",
        ["Add.PickElementHint"] = "把鼠标移到屏幕上的控件并点击，即可写入它的选择器。",
        ["Element.Title"] = "拾取元素",
        ["Element.Empty"] = "这里没有可拾取的控件，请换一个位置重试。",
        ["Element.Unknown"] = "控件",
        ["Element.Named"] = "名称“{0}”",
        ["Element.Id"] = "id {0}",
        ["Element.InWindow"] = "位于 {0}",
        ["Editor.PickedPosition"] = "已记录光标位置：{0}, {1}",
        ["Editor.PickedColor"] = "已取色：{0}",
        ["Editor.PickFailed"] = "无法读取该位置的屏幕颜色。",
        ["Editor.RecordActions"] = "录制动作",
        ["Editor.PositionCapture"] = "鼠标位置记录方式：",
        ["Editor.MouseMovement"] = "鼠标移动",
        ["Editor.MouseButtons"] = "鼠标按键",
        ["Editor.KeyboardKeys"] = "键盘按键",
        ["Editor.Delays"] = "等待时间 / 延迟",
        ["Editor.IgnoreInjected"] = "忽略其他程序的输入",
        ["Editor.Tip.IgnoreInjected"] = "忽略被系统标记为程序注入的输入，避免把正在运行的宏回放"
                                        + "录进宏里。若需在远程桌面或虚拟机中录制，请关闭此项。",
        ["Editor.IgnoreDelays"] = "忽略小于以下值的延迟：",
        ["Editor.Milliseconds"] = "毫秒",
        ["Editor.Record"] = "开始录制",
        ["Editor.StopRecording"] = "停止录制",
        ["Editor.RecordIdle"] = "按 Ctrl + F10 或点“开始录制”",
        ["Editor.RecordActive"] = "录制中 —— 已捕获 {0} 个事件（Esc 会被正常录下来），"
                                  + "按 Ctrl + F10 停止",
        ["Editor.RecordFailed"] = "无法开始录制。可能有其他程序占用了键盘或鼠标钩子。",
        ["Editor.RecordEmpty"] = "这次录制没有捕获到任何操作，通常是录制期间没有产生任何输入。"
                                 + "此外，远程桌面、虚拟机或自动化工具发送的输入会被系统标记为"
                                 + "程序注入，这类输入会被有意忽略（以免宏把自身的回放再次录入）。"
                                 + "若正在远程桌面或虚拟机中操作，请在“录制动作”面板中关闭"
                                 + "“忽略其他程序的输入”后重试。",
        ["Editor.Save"] = "保存",
        ["Editor.ActionEditor"] = "动作编辑器",
        ["Editor.JsonTree"] = "JSON 树",
        ["Editor.NoSteps"] = "还没有步骤。",
        ["Editor.StepDisabled"] = "已停用",
        // 块的两端。有了它们，“在循环里”和“在循环后面”才是列表上两个不同的位置。
        ["Editor.BlockEnd"] = "{0} 结束",
        ["Editor.Fold"] = "收起里面的步骤",
        ["Editor.Unfold"] = "展开里面的步骤",
        ["Editor.AddInside"] = "在这一块的末尾添加子步骤",
        ["Editor.NoStepsHint"] = "点击上方的“添加新动作”，选择动作并填写参数。",
        ["Editor.UnsavedTitle"] = "有未保存的修改",
        ["Editor.ClearTitle"] = "清空全部步骤",
        ["Editor.ClearMessage"] = "确定要清空全部 {0} 个步骤吗？此操作无法撤销。",
        ["Editor.Clear"] = "清空",
        ["Editor.Tip.SetKey"] = "选择启动这个宏的按键",
        ["Editor.Tip.Save"] = "保存这个宏并关闭编辑器",
        ["Editor.Tip.Record"] = "开始或停止录制屏幕上的操作（Ctrl + F10）",
        ["Editor.UnsavedMessage"] = "这个宏有尚未保存的修改。",
        ["Editor.Discard"] = "放弃修改",
        ["Editor.DeleteTitle"] = "删除宏",
        ["Editor.DeleteMessage"] = "确定删除“{0}”？此操作无法撤销。",
        ["Editor.Delete"] = "删除",

        // 显示在带有设置的步骤下面，不打开对话框也能看到。
        ["Editor.Meta.Retry"] = "重试 {0} 次",
        ["Editor.Meta.RetryDoubling"] = "重试 {0} 次（等待递增）",
        ["Editor.Meta.RetryJitter"] = "重试 {0} 次（等待随机）",
        ["Editor.Meta.Timeout"] = "超过 {0} 算失败",
        ["Editor.Meta.Pauses"] = "前置 {0} / 后置 {1}",
        ["Editor.JitterDetail"] = "±{0}%",
        ["Editor.Meta.OnErrorContinue"] = "失败后继续",
        ["Editor.Meta.OnErrorNextIteration"] = "失败后进入下一轮循环",
        ["Editor.Meta.OnErrorAsk"] = "失败后询问",

        // 编辑器在宏跑起来之前就能看出来的问题。只有步骤本身能定下来的才写在这里，
        // 需要跑一次才知道的事情不写。
        ["Editor.ProblemSummary"] = "有 {0} 个步骤被编辑器标了出来。",
        ["Editor.ProblemMark"] = "编辑器对这个步骤有话说",
        ["Editor.Problem.BreakOutsideLoop"] = "这个 break 不在任何循环里，没有可以跳出的循环。",
        ["Editor.Problem.ContinueOutsideLoop"] = "这个 continue 不在任何循环里，没有可以进入的下一轮。",
        ["Editor.Problem.NoMacro"] = "这一步没有选要执行的宏。",
        ["Editor.Problem.MacroNotFound"] = "本项目里没有名为“{0}”的宏。",
        ["Editor.Problem.UndefinedVariable"] = "没有定义“${0}”，读到的会是空的。",

        ["Trigger.Keys"] = "键盘 / 鼠标输入",
        ["Trigger.Color"] = "颜色 / 像素变化",
        ["Trigger.Timer"] = "定时",
        ["Trigger.File"] = "文件 / 文件夹变化",
        ["Trigger.Process"] = "程序启动 / 退出",
        ["Trigger.Window"] = "窗口出现 / 消失",
        ["Trigger.Idle"] = "机器空闲",
        ["Idle.Summary"] = "空闲 {0} 秒后",
        ["Schedule.Interval"] = "按间隔重复",
        ["Schedule.Daily"] = "每天固定时间",
        ["Schedule.Unit.Seconds"] = "秒",
        ["Schedule.Unit.Minutes"] = "分钟",
        ["Schedule.Unit.Hours"] = "小时",
        ["Schedule.IntervalSummary"] = "每 {0} {1}",
        ["Schedule.DailySummary"] = "每天 {0}",
        ["Schedule.DailyUnset"] = "每天（还没填时间）",
        ["FileChange.Any"] = "任何变化",
        ["FileChange.Created"] = "新建",
        ["FileChange.Changed"] = "内容变化",
        ["FileChange.Deleted"] = "删除或改名",
        ["ProcessChange.Started"] = "启动时",
        ["ProcessChange.Stopped"] = "退出时",
        ["ProcessChange.Any"] = "启动或退出",
        ["WindowChange.Appeared"] = "出现时",
        ["WindowChange.Disappeared"] = "消失时",
        ["WindowChange.Any"] = "出现或消失",
        ["WindowLookup.Title"] = "标题",
        ["WindowLookup.Process"] = "程序名",
        ["WindowLookup.ClassName"] = "窗口类名",
        ["Loop.Toggle"] = "再次按键时停止（切换）",
        ["Loop.Hold"] = "按住期间循环（长按）",
        ["Loop.Press"] = "按下时执行一次（按下）",
        ["Loop.Release"] = "松开时执行一次（松开）",
        ["Position.Current"] = "记录当前位置",
        ["Position.Differences"] = "记录位置差值",
        ["ColorMatch.Matches"] = "颜色匹配",
        ["ColorMatch.NotMatches"] = "颜色不匹配",

        ["Palette.Add"] = "添加新动作 (Insert)",
        ["Palette.Undo"] = "撤销上一步操作 (Ctrl + Z)",
        ["Palette.Redo"] = "恢复被撤销的操作 (Ctrl + Y)",
        ["Palette.Edit"] = "编辑选中的步骤（F2 或双击）",
        ["Palette.ToggleEnabled"] = "启用 / 停用选中的步骤 (Ctrl + E)",
        ["Palette.Copy"] = "复制选中的步骤 (Ctrl + C)",
        ["Palette.Cut"] = "剪切选中的步骤 (Ctrl + X)",
        ["Palette.Paste"] = "粘贴到选中步骤的下方 (Ctrl + V)",
        ["Palette.Delete"] = "删除选中的步骤 (Del)",
        ["Palette.Group"] = "把选中的步骤组合为一个顺序执行的分组 (Ctrl + G)",
        ["Palette.Run"] = "运行并调试这个宏 (F5)",
        ["Palette.MoveUp"] = "上移选中的步骤 (Ctrl + ↑)",
        ["Palette.MoveDown"] = "下移选中的步骤 (Ctrl + ↓)",
        ["Palette.Clear"] = "清空全部步骤",
        ["Palette.AdjustDelays"] = "运行速度 —— 按倍率缩放等待、按住与输入间隔",
        ["Palette.RunMacro"] = "执行其他宏 —— 插入一步调用本项目里的其他宏",
        ["Speed.Title"] = "运行速度",
        ["Speed.Explanation"] = "按倍率缩放这个宏的等待与节奏。只在本宏运行时生效，步骤里的数字不会被改动"
            + "——×1 就是完全按原文运行。",
        ["Speed.Summary"] = "{0} 处等待：约 {1} → {2}",
        ["Speed.Detail"] = "另有 {0} 处循环间隔、{1} 处按键 / 鼠标节奏也会一起缩放。",
        ["Speed.NoWaits"] = "这个宏还没有等待步骤，倍率只影响运行时的节奏。",

        ["Speed.Seconds"] = "{0} 秒",
        ["Speed.Milliseconds"] = "{0} 毫秒",

        // ---------------------------------------------------------- add action
        ["Add.Title"] = "添加动作",
        ["Add.EditTitle"] = "编辑动作",
        ["Add.SelectAction"] = "选择动作",
        ["Add.SharedPositionHint"] = "按 Alt + X 可把鼠标当前位置同时填入这两项。",
        ["Add.NoSelection"] = "尚未选择动作",
        ["Add.SelectHint"] = "从列表中选择一个动作，查看它需要填写的参数。",
        ["Add.Parameters"] = "参数",
        ["Add.JsonNode"] = "JSON 节点",
        ["Add.JsonPlaceholder"] = "// 选择一个动作以预览它的 JSON 节点",
        ["Add.NoParameters"] = "这个动作不需要参数。",
        ["Add.Cancel"] = "取消",
        ["Add.Commit"] = "添加步骤",
        ["Add.CommitEdit"] = "保存步骤",
        ["Add.SelectFirst"] = "请先选择一个动作。",
        ["Add.StillNeeded"] = "还缺：{0}",
        ["Add.NestedCondition"] = "选择条件",
        ["Add.NestedAddCondition"] = "添加条件",
        ["Add.Case"] = "添加分支",
        ["Add.NestedEdit"] = "编辑",
        ["Add.StepsInList"] = "这一块里的步骤在编辑器列表里调整：{0}",
        ["Add.AddStepToBlock"] = "添加子步骤",
        ["Add.AddStepToBlockHint"] = "把一步添加到这一块的末尾。这些步骤的前后顺序与删除在编辑器"
            + "列表中调整，宏的结构在那里最直观。",
        ["Add.ExpressionValid"] = "表达式有效",
        ["Add.ExpressionResult"] = "= {0}",
        ["Add.FormulaUse"] = "改写为表达式，例如 $match.x",
        ["Add.FormulaBack"] = "改回普通数字",
        ["Add.FormulaLocked"] = "表达式使用了变量，无法改回普通数字",
        ["Add.FormulaMilliseconds"] = "表达式按毫秒计算。",
        ["Add.Unit.ms"] = "毫秒",
        ["Add.Unit.s"] = "秒",
        ["Add.Unit.min"] = "分",
        ["Add.Unit.h"] = "时",
        ["Add.AdvancedShow"] = "高级选项（{0}）",
        ["Add.AdvancedHide"] = "收起高级选项",
        ["Add.ActionGroup"] = "{0}（{1}）",
        ["Add.RecentlyUsed"] = "最近使用",
        ["Add.Blocks"] = "流程块",
        ["Add.BlocksNote"] = "这些是构成任务流程的骨架：宏执行到此处会按它的设置运行。触发方式中的"
            + "“按住期间循环（长按）”与此无关，那是指整个宏反复重新执行。",
        ["Add.SearchAction"] = "搜索：按键、名称或作用",
        ["Add.ChangeAction"] = "更换",
        ["Add.NoActionFound"] = "目录里没有匹配的动作。",
        ["Add.Category.Control"] = "流程控制",
        ["Add.Category.File"] = "文件",
        ["Add.Category.Clipboard"] = "剪贴板",
        ["Add.Category.Process"] = "程序与命令",
        ["Add.Category.System"] = "系统",
        ["Add.Category.Window"] = "窗口",
        ["Add.Category.Input"] = "键盘与鼠标",
        ["Add.Category.Vision"] = "屏幕与图像",
        ["Add.Category.Ocr"] = "屏幕文字",
        ["Add.Category.Uia"] = "界面元素",
        ["Add.Category.Script"] = "脚本",
        ["Add.Category.Condition"] = "条件",
        ["Add.JitterSign"] = "±",
        ["Add.JitterUnit"] = "%",
        ["Add.JitterHint"] = "每次运行时在这个时长上下浮动的比例。",
        ["Add.JitterRange"] = "每次在 {0} – {1} 之间",
        ["Add.FormulaPlaceholder"] = "$match.x 或 $count + 1",
        ["Add.StepSettings"] = "步骤设置",
        ["Add.BlockSettings"] = "这是整段的设置：内部未处理的失败都算作这一段失败；重试、超时与"
            + "失败后的处理均按这里的设置执行。",
        ["Add.StepComment"] = "备注",
        ["Add.StepCommentHint"] = "显示在步骤下方的备注",
        ["Add.StepTimeout"] = "超时",
        ["Add.StepTimeoutHint"] = "只计算这一步自身的执行时间：执行前、执行后的延迟与重试之间的"
            + "等待都不计入；0 表示不限。块上的超时覆盖整段，因此包含子步骤的等待。",
        ["Add.StepRetry"] = "重试次数",
        ["Add.StepRetryDelay"] = "重试间隔",
        ["Add.StepOnError"] = "失败后",

        ["Add.StepBackoff"] = "重试间隔怎么变",
        ["Add.StepBackoffHint"] = "“每次翻倍”使每次重试的等待翻倍，适合响应较慢的程序；“随机”使"
            + "每次等待在 0.5 到 1.5 倍之间浮动，避免重试间隔完全一致。两者都不会超过 46 小时。",
        ["Add.Backoff.Fixed"] = "每次都一样",
        ["Add.Backoff.Doubling"] = "每次翻倍",
        ["Add.Backoff.Jitter"] = "在半倍到一倍半之间随机",
        ["Add.StepRetryPlanNone"] = "不重试：第一次失败即按右侧的规则处理。",
        ["Add.StepRetryPlanFixed"] = "会再试 {0} 次，每次先等 {1}。",
        ["Add.StepRetryPlanGrowing"] = "会再试 {0} 次，等待依次是 {1}。",
        ["Add.StepRetryPlanRandom"] = "会再试 {0} 次，每次等 {1} 到 {2} 之间的随机时长。",
        ["Add.StepDelayBefore"] = "执行前延迟",
        ["Add.StepDelayAfter"] = "执行后延迟",
        ["Add.StepEnabled"] = "执行这一步",
        ["Add.OnError.Stop"] = "停止整个宏",
        ["Add.OnError.Continue"] = "忽略并继续下一步",
        ["Add.OnError.NextIteration"] = "进入下一轮循环",
        ["Add.OnError.AskUser"] = "暂停并询问（重试 / 跳过 / 停止）",
        ["Expr.Error.Syntax"] = "表达式语法错误：{0}",
        ["Expr.Error.UnknownVariable"] = "表达式用了未定义的变量：{0}",
        ["Expr.Error.UnknownFunction"] = "表达式用了未知的函数：{0}",
        ["Expr.Error.ArgumentCount"] = "函数参数个数不对：{0}",
        ["Expr.Error.TypeMismatch"] = "值的类型不匹配：{0}",
        ["Expr.Error.DivideByZero"] = "不能除以零",
        ["Expr.Error.IndexOutOfRange"] = "列表下标超出范围：{0}",

        // ----------------------------------------------------- expression builder
        ["Add.ExpressionBuilder"] = "运算编辑器…",
        ["Add.ExpressionBuilderHint"] = "打开运算编辑器：所有运算符都做成按钮，可用变量做成下拉列表，"
            + "不用凭记忆手写。",
        ["ExprBuilder.Title"] = "运算编辑器",
        ["ExprBuilder.Help"] = "点运算符或变量即可插入到光标处，也可以直接改下面的表达式。"
            + "输入框下方会显示它算出来的结果。",
        ["ExprBuilder.Operators"] = "运算符",
        ["ExprBuilder.Expression"] = "当前表达式",
        ["ExprBuilder.Variables"] = "插入变量",
        ["ExprBuilder.Insert"] = "插入",
        ["ExprBuilder.Placeholder"] = "$count + 1",
        ["Expr.Op.Add"] = "数字相加，或把两段文本接在一起",
        ["Expr.Op.Subtract"] = "用左边减去右边",
        ["Expr.Op.Multiply"] = "两边相乘",
        ["Expr.Op.Divide"] = "左边除以右边",
        ["Expr.Op.Remainder"] = "相除后剩下的余数",
        ["Expr.Op.Equals"] = "两边相等",
        ["Expr.Op.NotEquals"] = "两边不相等",
        ["Expr.Op.Greater"] = "左边更大",
        ["Expr.Op.GreaterOrEqual"] = "左边大于或等于右边",
        ["Expr.Op.Less"] = "左边更小",
        ["Expr.Op.LessOrEqual"] = "左边小于或等于右边",
        ["Expr.Op.And"] = "两边都成立",
        ["Expr.Op.Or"] = "任一边成立即可",
        ["Expr.Op.Not"] = "把真变假、把假变真",
        ["Expr.Op.Group"] = "用括号把表达式的一部分括起来",
        ["Expr.Op.List"] = "写一个值的列表",
        ["Expr.Op.Text"] = "在引号之间写文本",

        // ------------------------------------------------------------ settings
        ["Settings.Title"] = "设置",
        ["Settings.Language"] = "语言",
        ["Settings.LanguageHint"] = "立即应用到所有窗口。",
        ["Settings.FailureScreenshot"] = "运行失败时保存屏幕截图",
        ["Settings.FailureScreenshotHint"] = "保存到程序所在目录下的 logs 文件夹。宏运行顺利时不会写入任何文件。",
        ["Settings.Note"] = "动作名称和参数文本会在窗口打开时按所选语言显示。",
        ["Settings.Close"] = "关闭",

        ["Confirm.Cancel"] = "取消",
        ["Common.Ok"] = "确定",
        ["Common.Minimize"] = "最小化",
        ["Common.Close"] = "关闭",
        ["Common.OptionalSuffix"] = "{0}（可选）",
        ["Common.StepCount"] = "{0} 个步骤",

        // ------------------------------------------------------------ macro package
        ["Main.OpenProjectTitle"] = "打开宏项目",
        ["Main.ImportProjectTitle"] = "导入宏项目",
        ["Main.SaveProjectTitle"] = "保存宏项目",
        ["Main.CloseAllTitle"] = "关闭全部宏",
        ["Main.CloseAllMessage"] = "从列表中移除所有宏？已保存的宏包不会被修改。",
        ["Package.Filter"] = "Viktor 宏包",
        ["Package.OpenFailed"] = "无法打开该文件",
        ["Package.SaveFailed"] = "无法保存该文件",

        // -------------------------------------------------------- variable center
        ["Variable.Title"] = "变量中心",
        ["Variable.Note"] = "宏可以读取系统变量和全局变量，也可以修改全局变量的值；只有变量中心能创建全局变量。"
            + "局部变量只属于创建它的宏，宏列表里的其他宏读取不到。",
        ["Variable.System"] = "系统变量",
        ["Variable.SystemHint"] = "由 Viktor 提供，这里实时读取当前值；宏只能读取，不能修改。",
        ["Variable.Globals"] = "全局变量",
        ["Variable.GlobalsHint"] = "所有宏共享。在这里创建和编辑；宏里只能修改它们的值，这里的默认值就是宏运行前的初始值。",
        ["Variable.Locals"] = "宏局部变量",
        ["Variable.LocalsHint"] = "只列出宏列表中现有的宏。一个宏只能看到自己的局部变量，宏列表里的其他宏读取不到；"
            + "它们只有在宏运行时才有值。",
        ["Variable.Tab.Current"] = "当前使用变量",
        ["Variable.Tab.Local"] = "局部变量",
        ["Variable.Tab.Global"] = "全局变量",
        ["Variable.Tab.System"] = "系统变量",
        ["Variable.CurrentHint"] = "宏列表里实际使用到的变量，并标注作用域和使用它的宏；系统变量默认不显示。",
        ["Variable.ShowSystem"] = "显示系统变量",
        ["Variable.NoneUsed"] = "宏里还没有使用任何变量。",
        ["Variable.UnknownHint"] = "宏里引用了这个变量，但没有任何步骤定义它。",
        ["Variable.Scope"] = "作用域",
        ["Variable.Owner"] = "所属宏",
        ["Variable.UsedBy"] = "使用的宏",
        ["Variable.NoGlobals"] = "尚无全局变量，可在下方添加。",
        ["Variable.NoLocals"] = "还没有宏创建局部变量。",
        ["Variable.Name"] = "名称",
        ["Variable.Type"] = "类型",
        ["Variable.Value"] = "当前值",
        ["Variable.Refresh"] = "刷新",
        ["Variable.NotSet"] = "未赋值",
        ["Variable.Default"] = "默认值",
        ["Variable.Description"] = "说明",
        ["Variable.Add"] = "添加",
        ["Variable.Close"] = "关闭",
        ["Variable.LocalDescription"] = "由该宏创建。",
        ["Variable.NameIsSystem"] = "“{0}”与系统变量重名。",
        ["Variable.NameTaken"] = "已存在名为“{0}”的全局变量。",
        ["Variable.Scope.System"] = "系统",
        ["Variable.Scope.Global"] = "全局",
        ["Variable.Scope.Local"] = "局部",
        ["Variable.Scope.Unknown"] = "未定义",
        ["Variable.Type.text"] = "文本",
        ["Variable.Type.number"] = "数字",
        ["Variable.Type.bool"] = "布尔",
        ["Variable.Type.color"] = "颜色",
        ["Variable.Type.date"] = "日期",
        ["Variable.Type.list"] = "列表",
        ["Variable.ListPreview"] = "共 {0} 项：{1}",
        ["Variable.EmptyList"] = "空列表",
        ["Variable.InvalidDefault"] = "起始值无法解析为列表",

        // ------------------------------------------------------------ run and debug
        ["Run.Title"] = "运行与调试",
        ["Run.Run"] = "运行",
        ["Run.Step"] = "单步",
        ["Run.Continue"] = "继续",
        ["Run.Stop"] = "停止",
        ["Run.Close"] = "关闭",
        ["Run.Steps"] = "步骤",
        ["Run.Log"] = "运行日志",
        ["Run.Variables"] = "变量监视",
        ["Run.Empty"] = "这个宏还没有步骤。",
        ["Run.Ready"] = "准备就绪",
        ["Run.Running"] = "运行中…",
        ["Run.Paused"] = "已暂停，等待下一步",
        ["Run.Start"] = "开始运行，共 {0} 个步骤。",
        ["Run.Finished"] = "运行结束，共执行 {0} 个步骤。",
        ["Run.Stopped"] = "已停止，共执行 {0} 个步骤。",
        ["Run.Aborted"] = "运行中断，共执行 {0} 个步骤。",
        ["Run.FailurePicture"] = "已把屏幕截图存到 {0}",
        ["Run.FailurePictureFailed"] = "屏幕截图没能保存：{0}",
        ["Run.Skipped"] = "已跳过：这一步处于停用状态",
        ["Run.Retry"] = "第 {0} 次重试",
        ["Run.StopRequested"] = "宏主动要求停止。{0}",
        ["Run.Set"] = "{0} = {1}",
        ["Run.Message"] = "{0}",
        ["Run.Unsupported"] = "引擎尚不支持这个动作：{0}",
        ["Run.ConditionUnavailable"] = "这个条件需要设备层，尚未接入：{0}",
        ["Run.BadExpression"] = "这个值不是有效的表达式：{0}",
        ["Run.BadList"] = "这个值不是列表：{0}",
        ["Run.NotAList"] = "{0} 不是列表",
        ["Run.IndexOutOfRange"] = "下标超出列表范围：{0}",
        ["Run.GlobalMustExist"] = "只有变量中心能创建全局变量，而 {0} 还不存在",
        ["Run.MissingVariable"] = "没有填写变量名",
        ["Run.DivideByZero"] = "不能除以零。",
        ["Run.Failed"] = "该步骤执行失败。",
        ["Run.Timeout"] = "该步骤的运行时间超过了允许的 {0} 毫秒。",
        ["Run.Ask"] = "步骤“{0}”执行失败，请选择接下来的处理方式。",
        ["Run.AskRetry"] = "重试",
        ["Run.AskSkip"] = "跳过这一步",
        ["Run.AskStop"] = "停止宏",
        ["Run.AskTitle"] = "步骤执行失败",
        ["Run.AskComment"] = "步骤备注：{0}",
        ["Run.NoVariables"] = "这个宏还没有使用变量。",
        ["Run.NoDevice"] = "这台机器暂不支持该操作：{0} 尚未接入。",
        ["Run.UnknownKey"] = "无法识别这个键名：{0}",
        ["Run.EmptyChord"] = "这个组合键里没有任何按键。",
        ["Run.PixelOutsideScreen"] = "这个坐标不在屏幕上：{0}",
        ["Run.EmptyRegion"] = "这不是一个可用的屏幕区域：{0}",
        ["Run.CaptureFailed"] = "这块屏幕区域无法复制：{0}",
        ["Run.BadRegion"] = "搜索区域要写成 x,y,宽,高 的形式：{0}",
        ["Run.BadPoints"] = "多点比色里的每个点要写成 x,y,#RRGGBB 的形式：{0}",
        ["Run.BadPattern"] = "这不是一个可用的匹配模式：{0}",
        ["Run.Capture"] = "已截图到 {0}：{1}",
        ["Run.SawColor"] = "像素显示为 {0}。",
        ["Run.WaitColorTimeout"] = "一直没有等到颜色 {0}。",
        ["Run.ImageFound"] = "已找到，保存到 {0}：{1}",
        ["Run.ImageMissing"] = "屏幕上没有，{0} 已置空。",
        ["Run.ImageNotFound"] = "始终没有找到参考图片：{0}",
        ["Run.ClickedImage"] = "已点击匹配位置 {0},{1}",
        ["Run.MissingImage"] = "参考图片读不出来：{0}",
        ["Run.UnknownCondition"] = "无法识别这个条件：{0}",
        ["Run.TextFound"] = "已找到文字，保存到 {0}：{1}",
        ["Run.TextMissing"] = "屏幕上没有这段文字，{0} 已置空。",
        ["Run.TextNotFound"] = "始终没有找到文字：{0}",
        ["Run.ClickedText"] = "已点击“{0}”，位置 {1}",
        ["Run.ElementFound"] = "元素已出现：{0}",
        ["Run.ElementNotFound"] = "元素始终没有出现：{0}",
        ["Run.ElementNotClickable"] = "这个元素点不了：{0}",
        ["Run.ElementNotWritable"] = "这个元素写不进去：{0}",
        ["Run.ElementFilled"] = "已在 {0} 中写入“{1}”",
        ["Run.ClickedElement"] = "已点击元素：{0}",
        ["Run.ElementWhere"] = "已找到元素，保存到 {0}：{1}",
        ["Run.ElementMissing"] = "没有找到这个元素，{0} 已置空。",
        ["Run.SelectedItem"] = "已在 {0} 中选中“{1}”",
        ["Run.ItemNotFound"] = "没有找到要选的那一项：{0}",
        ["Run.MissingItem"] = "这一步没有填写要选择哪一项。",
        ["Run.ElementNotSelectable"] = "这个元素里没有可以选择的内容：{0}",
        ["Run.ElementChecked"] = "已改变 {0} 的勾选状态",
        ["Run.ElementNotCheckable"] = "这个元素不是勾选框：{0}",
        ["Run.ElementExpanded"] = "已改变 {0} 的展开状态",
        ["Run.ElementNotExpandable"] = "这个元素不能展开或收起：{0}",
        ["Run.ScrolledElement"] = "已滚动到可见：{0}",
        ["Run.ElementNotScrollable"] = "这个元素无法滚动到可见：{0}",
        ["Run.ReadTable"] = "已把 {1} 行读入 {0}。",
        ["Run.ElementNotATable"] = "这个元素不是表格：{0}",
        ["Run.RanScript"] = "已运行 {0} 脚本，收回 {1} 个字符。",
        ["Run.ScriptFailed"] = "脚本以退出码 {0} 结束",
        ["Run.ScriptNotTidied"] = "脚本文件已经不在了：{0}",
        ["Run.MissingScript"] = "这一步没有填写要运行的脚本。",
        ["Run.UnknownInterpreter"] = "无法识别这个解释器：{0}",
        ["Run.MissingInterpreter"] = "这一步没有写用哪个程序运行脚本。",
        ["Run.MissingScriptExtension"] = "这一步没有写脚本要用什么后缀。",
        ["Run.WindowNotFound"] = "没有找到这个标题的窗口：{0}",
        ["Run.FocusedWindow"] = "已把窗口调到最前：{0}",
        ["Run.EmptySelector"] = "没有填写要查找的元素选择器。",
        ["Run.MissingWindow"] = "没有填写窗口标题：{0}",
        ["Run.MissingTargetWindow"] = "后台输入需要目标窗口，请先填写目标窗口的标题。",
        ["Run.ReadFile"] = "已读取 {0}，共 {1} 个字符。",
        ["Run.WroteFile"] = "已写入 {0}，共 {1} 个字符。",
        ["Run.AppendedFile"] = "已追加到 {0}，现在共 {1} 个字符。",
        ["Run.DeletedFile"] = "已删除 {0}。",
        ["Run.CopiedFile"] = "已把 {0} 复制到 {1}。",
        ["Run.MovedFile"] = "已把 {0} 移动到 {1}。",
        ["Run.MadeFolder"] = "已创建文件夹 {0}。",
        ["Run.RemovedFolder"] = "已删除文件夹 {0}。",
        ["Run.Unzipped"] = "已把 {0} 解压到 {1}。",
        ["Run.ListedFiles"] = "在 {0} 中找到 {1} 个文件。",
        ["Run.SavedVariables"] = "已把 {1} 个变量保存到 {0}。",
        ["Run.LoadedVariables"] = "已从 {0} 读回 {1} 个变量。",
        ["Run.BadJson"] = "这个文件不是有效的 JSON：{0}",
        ["Run.BadJsonPath"] = "无法解析这个 JSON 路径：{0}",
        ["Run.MissingJsonPath"] = "JSON 的这个位置上没有值。",
        ["Run.FileNotFound"] = "找不到这个文件：{0}",
        ["Run.FolderNotFound"] = "找不到这个文件夹：{0}",
        ["Run.FileExists"] = "目标文件已存在，而当前设置为不覆盖：{0}",
        ["Run.MissingPath"] = "没有填写文件路径。",
        ["Run.FileFailed"] = "这个文件读写失败：{0}",
        ["Run.BadZip"] = "这个文件不是 zip 压缩包，或者压缩包不完整：{0}",
        ["Run.CopiedToClipboard"] = "已复制 {0} 个字符到剪贴板。",
        ["Run.ReadClipboard"] = "已把剪贴板读入 {0}，共 {1} 个字符。",
        ["Run.ClearedClipboard"] = "已清空剪贴板。",
        ["Run.ReadClipboardImage"] = "已把剪贴板上的图片读入 {0}（{1}）。",
        ["Run.NoClipboardImage"] = "剪贴板上没有图片，已清空 {0}。",
        ["Run.CopiedImageToClipboard"] = "已把 {0} 的图片复制到剪贴板。",
        ["Run.ReadClipboardFiles"] = "已把剪贴板上的 {1} 个文件读入 {0}。",
        ["Run.CopiedFilesToClipboard"] = "已把 {0} 个文件放进剪贴板。",
        ["Run.ClipboardChanged"] = "剪贴板已变化，{0} 中保存了 {1} 个字符。",
        ["Run.CopiedFromWindow"] = "已复制所选内容到 {0}，共 {1} 个字符。",
        ["Run.PastedText"] = "已把文本放进剪贴板并粘贴。",
        ["Run.Pasted"] = "已发送粘贴快捷键。",
        ["Run.ClipboardTimeout"] = "剪贴板一直没有变化。",
        ["Run.ClipboardBusy"] = "另一个程序正占用剪贴板。",
        ["Run.ClipboardWriteFailed"] = "剪贴板没有接受这段文本。",
        ["Run.StartedProgram"] = "已启动 {0}，进程 id 为 {1}。",
        ["Run.ProgramFound"] = "{0} 正在运行，进程 id 为 {1}。",
        ["Run.ProgramNotFound"] = "始终没有等到 {0} 启动。",
        ["Run.ProcessExited"] = "进程 {0} 已结束，退出码 {1}。",
        ["Run.ProcessTimeout"] = "进程 {0} 没有在限定时间内结束。",
        ["Run.BadProcessId"] = "这不是一个进程 id：{0}",
        ["Run.ListedPrograms"] = "共找到 {0} 个正在运行的程序。",
        ["Run.StoppedProgram"] = "已停止 {0}，共关闭 {1} 个进程。",
        ["Run.CommandFinished"] = "{0} 已结束，退出码 {1}。",
        ["Run.CommandStarted"] = "正在运行 {0}，它打印的内容会写进日志。",
        ["Run.CommandOutput"] = "> {0}",
        ["Run.CommandError"] = "! {0}",
        ["Run.UnknownSystemField"] = "无法识别这个系统字段：{0}",
        ["Run.Power"] = "已请求系统执行：{0}，提示 {1} 秒。",
        ["Run.PowerRefused"] = "Windows 不接受对这台电脑执行该操作。",
        ["Run.LockRefused"] = "Windows 没有锁定屏幕。",
        ["Run.AbortRefused"] = "没有正在倒计时的关机可以取消。",
        ["Run.UnknownPowerAction"] = "无法识别这个电源动作：{0}",
        ["Run.Volume"] = "现在音量是 {0}%。",
        ["Run.SoundOff"] = "声音已关闭。",
        ["Run.SoundOn"] = "声音已打开。",
        ["Run.AudioRefused"] = "Windows 不接受这次声音调整：{0}",
        ["Run.UnknownVolumeAction"] = "无法识别这个音量动作：{0}",
        ["Run.NoForegroundWindow"] = "当前没有最前面的窗口，无法执行。",
        ["Run.NoImeContext"] = "当前窗口没有可切换的输入法，它的键盘布局直接产生字符。",
        ["Run.ImeRefused"] = "Windows 没有把输入法切到{0}。",
        ["Run.LayoutNotFound"] = "这台机器上没有安装匹配的键盘布局：{0}",
        ["Run.LayoutNotSwitched"] = "已请求当前窗口切换到 {0}，但它始终没有完成切换。",
        ["Run.Brightness"] = "屏幕亮度现在是 {0}%。",
        ["Run.BrightnessRefused"] = "没有屏幕接受这个亮度。",
        ["Run.UnknownBrightnessAction"] = "无法识别这个亮度动作：{0}",
        ["Run.UnknownInputMethodAction"] = "无法识别这个输入法动作：{0}",
        ["Run.MissingName"] = "没有填写名称。",
        ["Run.MissingProgram"] = "没有填写程序名。",
        ["Run.ProgramFailed"] = "这个程序无法启动或运行：{0}",
        ["Run.ElevationRefused"] = "已请求以管理员身份启动 {0}，但这个请求被拒绝了。",
        ["Run.ElevationNoEnvironment"] = "{0} 不能同时以管理员身份启动又自带环境变量。",
        ["Run.BadEnvironment"] = "这一行不是 NAME=value 的写法：{0}",
        ["Run.CommandTimeout"] = "命令没有在限定时间内结束：{0}",
        ["Run.ActivatedWindow"] = "已把窗口调到最前：{0}",
        ["Run.MinimizedWindow"] = "已最小化窗口：{0}",
        ["Run.MaximizedWindow"] = "已最大化窗口：{0}",
        ["Run.RestoredWindow"] = "已把窗口恢复成正常大小：{0}",
        ["Run.MovedWindow"] = "已移动并调整窗口大小：{0}",
        ["Run.ClosedWindow"] = "已请求关闭窗口：{0}",
        ["Run.WindowAppeared"] = "窗口已出现：{0}",
        ["Run.WindowTimeout"] = "始终没有等到这个标题的窗口：{0}",
        ["Run.WindowFailed"] = "这个窗口不接受该操作：{0}",
        ["Run.ListedWindows"] = "共找到 {0} 个打开的窗口。",
        ["Run.WindowBox"] = "{0} 位于 {1}",
        ["Run.Speed"] = "正以 ×{0} 的速度运行，与步骤中写的不一致。",
        ["Run.SpeedTip"] = "这个宏正在以与步骤中不同的速度运行。",
        ["Run.CalledMacro"] = "正在执行“{0}”：{1} 个步骤。",
        ["Run.MacroNotFound"] = "本项目里没有名为“{0}”的宏。",
        ["Run.MacroTooDeep"] = "宏之间的互相调用层级过深：{0}",
        ["Run.BadMacroArgument"] = "这一行不是传给宏的 NAME=value 写法：{0}",
        ["Run.BreakOutsideLoop"] = "break 不在任何循环里，没有可以跳出的循环。",
        ["Run.ContinueOutsideLoop"] = "continue 不在任何循环里，没有可以跳到下一轮的循环。",
        ["Run.DeviceFailed"] = "维克多之外的组件出错：{0}",
        ["Run.Caught"] = "执行失败，转入捕获步骤。",
        ["Run.Finally"] = "正在执行收尾步骤。",
        ["Add.SystemReadOnly"] = "“{0}”是系统变量，宏只能读取，不能修改。",
        ["Add.GlobalMustExist"] = "全局变量“{0}”不存在，请先在变量中心创建。",

        ["Run.WaitedFor"] = "等待在 {0} 毫秒后成立：{1}。",
        ["Run.WaitGaveUp"] = "等了 {0} 毫秒仍不成立，按设置继续往下走：{1} 一直没有成立。",
        ["Run.WaitTimeout"] = "等待超时，{0} 始终没有成立。",
        ["Run.MissingCondition"] = "这一步没有填写要等待的条件。",

        // system variable descriptions
        ["Variable.sys.macroLoop.desc"] = "整个宏已经循环的次数。",
        ["Variable.sys.loopIndex.desc"] = "当前循环体执行到第几轮，只在循环体内部可见。",
        ["Variable.sys.date.desc"] = "当前日期，例如 2026-10-05。",
        ["Variable.sys.dateLong.desc"] = "当前日期和星期，例如 2026-10-05 星期一。",
        ["Variable.sys.time.desc"] = "当前时间，例如 09:30:00。",
        ["Variable.sys.dateTime.desc"] = "当前日期和时间，例如 2026-10-05 09:30:00。",
        ["Variable.sys.year.desc"] = "当前年份。",
        ["Variable.sys.month.desc"] = "当前月份（1-12）。",
        ["Variable.sys.day.desc"] = "当前日（1-31）。",
        ["Variable.sys.weekday.desc"] = "当前星期几。",
        ["Variable.sys.hour.desc"] = "当前小时（0-23）。",
        ["Variable.sys.minute.desc"] = "当前分钟（0-59）。",
        ["Variable.sys.second.desc"] = "当前秒（0-59）。",
        ["Variable.sys.timestamp.desc"] = "Unix 时间戳（秒）。",
        ["Variable.sys.mouseX.desc"] = "当前鼠标的 X 坐标。",
        ["Variable.sys.mouseY.desc"] = "当前鼠标的 Y 坐标。",
        ["Variable.sys.mouseColor.desc"] = "鼠标所指位置的颜色，例如 #RRGGBB。",
        ["Variable.sys.screenWidth.desc"] = "主屏幕宽度。",
        ["Variable.sys.screenHeight.desc"] = "主屏幕高度。",
        ["Variable.sys.machineName.desc"] = "计算机名。",
        ["Variable.sys.userName.desc"] = "当前登录用户名。",
        ["Variable.sys.clipboard.desc"] = "剪贴板中的文本。",
        ["Variable.sys.random.desc"] = "0 到 1 之间的随机数。",
    };
}
